### ISSUE TITLE
More info on pretrained models

### ISSUE THREAD

**Issue by faroit** [deezer/spleeter#1]
First, congrats to your release. Glad to have more music separation ready to use :-)

Do you have some more information regarding 

* were the pretrained models just trained on MUSDB18?
* If not, would the models be still performing as good as state of the art when trained on just MUSDB18?
* what SDR values could we expect from these models on MUSDB18 test?

**Comment by faroit** [comment]
@romi1502 thanks for the info. 

I think, especially or the research community, it would be cool to also present reproducible scores when just trained on MUSDB18. That way you prevent people from using non-ideal parameters and maybe report scores that are too low. Oh and also we can save a bit of energy for the environment ;-)

**Comment by mmoussallam** [comment]
Hi @faroit Thanks for your Feedback. 

Training on musdb is definitely something we can do but I'm not sure how much value it would bring to end users.
Our intent with Spleeter is not so much to compare ourselves with the latest separation models but rather to provide a fast and ready-to-use separation tool for researchers doing other tasks (e.g. transcription..). I'm afraid releasing multiple models trained on different datasets would complicate things for users.

**Comment by decivilizator** [comment]
Could you please share how large was your dataset for the pretrained models?

**Comment by faroit** [comment]
> Training on musdb is definitely something we can do but I'm not sure how much value it would bring to end users.

> I'm afraid releasing multiple models trained on different datasets would complicate things for users.

@mmoussallam I understand that but at one point people will use this to train on their own data and might publish results based on this repo.

I already trained and evaluated on MUSDB18 and it seems that there are some issues - See #81
It would be great if you could help to update the training configs for MUSDB18. Another options would be to maintain a fork of spleeter on sigsep to host a pretrained models on MUSDB18 for the source separation community, what do you think?

**Comment by faroit** [comment]
@mmoussallam I am closing this issue since it is not related to the pretrained beans model. Feel free to reply here or in #81
