### ISSUE TITLE
[Bug] Why can't python find any file?

### ISSUE THREAD

**Issue by omgwtfbbqpls** [deezer/spleeter#100]
I'm trying to run this script in the command prompt with my python installation. No matter how I try and type the file path it can't find any file. I used backward slashes, tried replacing the spaces with underscores, didn't work.
So I decided not to include any filepath and just type "test.mp3" and put the file in the System32 folder (where the command is being run?), but it can't find the file either (example below).
Then I decided to run it in another directory (C:) and move the file there, but the stupid thing just started downloading another copy of the model. And failed to find the file. Again.

```
C:\Windows\System32>spleeter separate -i test.mp3 -o audio_output -p spleeter:4stems
INFO:spleeter:Loading audio b'test.mp3' from 0.0 to 600.0
WARNING: Logging before flag parsing goes to stderr.
I1115 17:51:26.542378  8392 adapter.py:77] Loading audio b'test.mp3' from 0.0 to 600.0
WARNING:spleeter:[WinError 2] The system cannot find the file specified
W1115 17:51:26.560380  8392 adapter.py:88] [WinError 2] The system cannot find the file specified
```

```
C:\Windows\System32>spleeter separate -i C:\Windows\System32\test.mp3 -o audio_output -p spleeter:4stems
INFO:spleeter:Loading audio b'C:\\Windows\\System32\\test.mp3' from 0.0 to 600.0
WARNING: Logging before flag parsing goes to stderr.
I1115 18:16:55.413825 10072 adapter.py:77] Loading audio b'C:\\Windows\\System32\\test.mp3' from 0.0 to 600.0
WARNING:spleeter:[WinError 2] The system cannot find the file specified
W1115 18:16:55.428826 10072 adapter.py:88] [WinError 2] The system cannot find the file specified
```

OS - Windows 7
Installation type - Uhhh, pip?
RAM available - In total? 8 GB
Hardware spec - GTX 1050 Ti

Are there any plans for a GUI? I really really really hate terminal commands because of garbage like this.

Really looking forward to a response on how to write the filepath, as this program looks amazing. Cheers.

**Comment by islammohamedd1** [comment]
Having the same problem here on windows 10

**Comment by SecretUnicorn** [comment]
You need to install ffmpeg and add it to your PATH variable. That fixed it for me

**Comment by omgwtfbbqpls** [comment]
> 
> 
> @SecretUnicorn You need to install ffmpeg and add it to your PATH variable. That fixed it for me

Thanks, it works now. I followed the instructions here: https://youtu.be/tgnuOSLPwMI?t=314

The problem now is it can't find files with spaces in the filename/filepath - it seems to think the space indicates two different files. How do I write the command so it doesn't do that?

And my other problem is it keeps outputting the files in system32. What command will make it output elsewhere?

**Comment by SecretUnicorn** [comment]
Filenames with spaces should be in quotes for example "First Test.mp3". With the Output path I cannot Help you though sry
