### ISSUE TITLE
WARNING:spleeter:module 'ffmpeg' has no attribute 'probe'  

### ISSUE THREAD

**Issue by gibe9000** [deezer/spleeter#101]
## Description

I am having a problem, getting the an error message  

WARNING:spleeter:module 'ffmpeg' has no attribute 'probe'  

I installed ffmpeg via a zip from https://ffmpeg.zeranoe.com/builds/ 

Also made a PATH to the bin folder of ffmpeg but still nothing

## Step to reproduce

1.
Installed python 3.7.5 64bit
download spleeter from github
pip install spleeter
download and unzip ffmpeg from https://ffmpeg.zeranoe.com/builds/ 
create PATH for ffmpeg
pip install ffmpeg
install tensorflow==1.14.0 (instead of 2.0.0 because i got error message from it)

2.
run separate command: spleeter separate -i gilli.mp3 -p spleeter:2stems -o gillistems2

3.
Got error: WARNING:spleeter:module 'ffmpeg' has no attribute 'probe'

## Output

PS C:\Users\Christoffer\Downloads\VA-MusicBits_Mixtape_Vol._9-WEB-MP3-2018-MusicBits> spleeter separate -i gilli.mp3 -p spleeter:2stems -o gillistems2
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:spleeter:Extracting downloaded 2stems archive
INFO:spleeter:2stems model file(s) extracted
INFO:spleeter:Loading audio b'gilli.mp3' from 0.0 to 600.0
WARNING:spleeter:module 'ffmpeg' has no attribute 'probe'
PS C:\Users\Christoffer\Downloads\VA-MusicBits_Mixtape_Vol._9-WEB-MP3-2018-MusicBits>

## Environment

| OS                | Windows 64bit
| Installation type |  / pip

**Comment by osvaldo1963** [comment]
try 
`pip uninstall ffmpeg`
and 
`pip install ffmpeg-python`

**Comment by gibe9000** [comment]
Okay i found the solution with your help :))
What you suggested unfortunately didn't work. but then i tried:
`pip uninstall ffmpeg-python`
and as you suggested
`pip install ffmpeg-python`
And it worked! So thanks alot with the help :)

**Comment by ayanasser** [comment]
I try your solution and it works with the mentioned error, 
but it gave me another error
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe': 'ffprobe'

any help ?

**Comment by TheRealPoseidon** [comment]
> I try your solution and it works with the mentioned error,
> but it gave me another error
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe': 'ffprobe'
> 
> any help ?

hi~
I also encounter the same FileNotError about 'ffprobe'. Did you solve it?

**Comment by ayanasser** [comment]
@TheRealPoseidon 
you should install ffmpeg through apt-get install ffmpeg, not from pip, 
This solved my Error

**Comment by gustavofelicidade** [comment]
I'm getting the same error but I use windows 10

**Comment by insidewhy** [comment]
I've started getting this issue, ffmpeg-python is installed via `Pipenv`. `ffmpeg.__file__` shows it's importing from the right place. Using python `3.9.7`.

`print(dir(ffmpeg))` gives me:

```
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

**Comment by gustavofelicidade** [comment]
Hi guys,  I solve the problem here. Just did a ffmpeg download and added it to the path as shown in this tutorial: https://windowsloop.com/install-ffmpeg-windows-10/#download-ffmpeg

and after I uninstalled ffmpeg-python, and reinstalled ffmpeg-python again and the "no attribute 'probe'" error disappeared.

**Comment by oliverban** [comment]
> Hi guys, I solve the problem here. Just did a ffmpeg download and added it to the path as shown in this tutorial: https://windowsloop.com/install-ffmpeg-windows-10/#download-ffmpeg
> 
> and after I uninstalled ffmpeg-python, and reinstalled ffmpeg-python again and the "no attribute 'probe'" error disappeared.

Just re-did this and still not working.....
