### ISSUE TITLE
[Discussion] Can't install Spleeter using pip in MacOS 10.13.6

### ISSUE THREAD

**Issue by MacStevins** [deezer/spleeter#102]
When I try to install spleeter using `pip install spleeter`, it prints out:

```
ERROR: Could not find a version that satisfies the requirement spleeter (from versions: none)
```

**Comment by TardisPeanut** [comment]
Yeah same problem here in Windows as well

**Comment by JaiWyn** [comment]
I was having the same problem. Uninstalled python 3.8 and installed 3.7.5 instead. Worked then, not sure why

**Comment by tuancuong92** [comment]
These steps are worked for me:
1. brew install ffmpeg (also install python 3.7.5)
2. pip3 install spleeter

**Comment by Faylixe** [comment]
Only Python 3.6 and 3.7 version are supported by now.
