### ISSUE TITLE
[Bug] Trailing slash on output path will break the process

### ISSUE THREAD

**Issue by aidv** [deezer/spleeter#103]
## Description

When specifying the output path, a trailing slash will render the process useless.

## Step to reproduce

Incorrect: `spleeter separate -i "C:\Users\user\Desktop\spleeter-repo\song.mp3" -p spleeter:5stems -o "C:\Users\user\Desktop\spleeter-repo\output\"`

Correct: `spleeter separate -i "C:\Users\user\Desktop\spleeter-repo\song.mp3" -p spleeter:5stems -o "C:\Users\user\Desktop\spleeter-repo\output"`

## Output

```bash
...
 np_resource = np.dtype([("resource", np.ubyte, 1)])
c:\anaconda\envs\spleeter-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\anaconda\envs\spleeter-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
...
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 |
| Installation type | Conda             |
| RAM available     | 16GB                            |
| Hardware spec     | GT610, i7 960            |

## Additional context

N/A

**Comment by jontonsoup4** [comment]
This might be solely a windows bug. I tested using trailing slashes on Mac and it works as expected.

**Comment by greatfinders** [comment]
i have countless of thoses lines too  '

 np_resource = np.dtype([("resource", np.ubyte, 1)])
c:\anaconda\envs\spleeter-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\anaconda\envs\spleeter-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])


even if it seems to work (sometimes i don't have vocals, sometimes i don't have instrumental when using 2stems
and if i use longer audios it stop after ffmpeg reading correctly the audio so i think thoses lines are an issue

**Comment by Faylixe** [comment]
> i have countless of thoses lines too and it's not related to the ""
> 
> np_resource = np.dtype([("resource", np.ubyte, 1)])
> c:\anaconda\envs\spleeter-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> c:\anaconda\envs\spleeter-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> np_resource = np.dtype([("resource", np.ubyte, 1)])
> 
> even if it seems to work (sometimes i don't have vocals, sometimes i don't have instrumental when using 2stems
> and if i use longer audios it stop after ffmpeg reading correctly the audio so i think thoses lines are an issue

It is not. Please read FAQ about warnings, memory requirements, and FFmpeg related issues.



> ## Description
> When specifying the output path, a trailing slash will render the process useless.
> 
> ## Step to reproduce
> Incorrect: `spleeter separate -i "C:\Users\user\Desktop\spleeter-repo\song.mp3" -p spleeter:5stems -o "C:\Users\user\Desktop\spleeter-repo\output\"`
> 
> Correct: `spleeter separate -i "C:\Users\user\Desktop\spleeter-repo\song.mp3" -p spleeter:5stems -o "C:\Users\user\Desktop\spleeter-repo\output"`
> 
> ## Output
> ```shell
> ...
>  np_resource = np.dtype([("resource", np.ubyte, 1)])
> c:\anaconda\envs\spleeter-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> c:\anaconda\envs\spleeter-gpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> ...
> ```
> 
> ## Environment
> OS	Windows 10
> Installation type	Conda
> RAM available	16GB
> Hardware spec	GT610, i7 960
> ## Additional context
> N/A

Not an issue for UNIX based system. It maybe is for Windows although your provided log trace do not relate to the problem you mention. Please reopen the issue with detailed error logs.
