### ISSUE TITLE
[Bug] Issue with non UTF-8 characters in Python path

### ISSUE THREAD

**Issue by RandomTypek** [deezer/spleeter#109]
## Description

Spleeter refuses to start if Python's installation path contains a non UTF-8 character.

## Step to reproduce

Python's path has to have a non UTF-8 character in it, eg. "Š" (in my case: C:\Users\Šimon\AppData\Local\Programs\Python\Python37)

1. Installed using pip
2. Run as normal
3. Got SyntaxError

## Output

```File "C:\Users\Šimon\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 1
SyntaxError: Non-UTF-8 code starting with '\x9a' in file C:\Users\Šimon\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | pip |
| RAM available     | 8GB |
| Hardware spec     | I think this is irrelevant |

## Additional context

Can be easily fixed by adding the following line into spleeter-script.py:

#-*- coding: iso-8859-2 -*-

**Comment by mmoussallam** [comment]
the `spleeter-script.py` file seems to be generated by the `setuptools` package during the installation. so we can't really force the encoding here.

Does the full command `python -m spleeter separate` work ?

**Comment by RandomTypek** [comment]
Yes, after removing the added line in spleeter-script.py, I can confirm that the full command works as expected
