### ISSUE TITLE
[Discussion] Why is the model rebuilt every time?

### ISSUE THREAD

**Issue by aidv** [deezer/spleeter#112]
Anyone wants to explain to me why the model is rebuilt every time?

My rationale is that since the model can be recycled for a batch, why can't the model be saved as a file and loaded next time a separation is executed?

It just doesn't make sense to me.

I think that the model should be rebuilt only when asked to do so.

**Comment by romi1502** [comment]
The `separate` command of `spleeter` is able to process several files at once, and the model is then build and loaded a single time (as documented in the [Wiki](https://github.com/deezer/spleeter/wiki/2.-Getting-started#batch-processing)):
```bash
spleeter separate -i /path/to/audio1.mp3 /path/to/audio2.wav /path/to/audio3.mp3 -o /output_path.
```
If you want to put Spleeter in a server with on demand separation, then you can use the `Separator` object of the[ python API](https://github.com/deezer/spleeter/wiki/4.-API-Reference#separator) that builds and loads the model once. Then you can use the `separate` and `separate_to_file` methods as many times as you want without rebuilding the model.

So there are already ways of not rebuilding the model every time :).

**Comment by aidv** [comment]
Would be possible to access the API from, say, a NodeJS app?
