### ISSUE TITLE
Illegal instruction: 4 using separate on Mac OS 10.13.6 

### ISSUE THREAD

**Issue by TeleselforSlim** [deezer/spleeter#113]
spleeter opens and all help menus function but when I attempt to split the audio_example.mp3 from the spleeter-master folder created by unzipping spleeter-master.zip in my Downloads folder i receive the error message "Illegal instruction:4" and Python crashes a .txt document containing the error report after crash is attached.

python3 version 3.7.5 in Terminal Version 2.8.3 using bash shell within Mac OS 10.13.6.

1. ffmpeg 4.2.1-2 was first installed using homebrew 
      "brew install ffmpeg"
2. libsndfile was previously installed version 1.0.28, reinstalled using 
      "brew reinstall libsndfile" 
3. spleeter was installed using pip3
      "cd ~/Downloads/spleeter-master/
        pip3 install spleeter"
    Installation successful
4. Run 
      "separate -i audio_example.mp3 -o output" command within directory ~/Downloads/spleeter-master/
5. Error returned
      "Illegal instruction: 4"

## Output

```bash
COMPUTER:spleeter-master zacharylawlor$ spleeter separate -i audio_example.mp3 -o output
Illegal instruction: 4
COMPUTER:spleeter-master zacharylawlor$ 

```
[error.txt](https://github.com/deezer/spleeter/files/3857173/error.txt)

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS|
| Installation type | pip3|
| RAM available     | 16G                             |
| Hardware spec     | GPU:NVIDIA GeForce GT 120 / CPU: Quadcore Xeon 2.66|

**Comment by mmoussallam** [comment]
Hi

It's not easy for us to reproduce your crash but can we suggest using conda for the install on your machine ?

**Comment by TeleselforSlim** [comment]
No problem. conda method works. I'm trying to cut the number of steps to launch down and Python seemed best for that. I'll take another stab at it this weekend and see if i can resolve it on my own. Are you having success running it in MacOS?

**Comment by Christilut** [comment]
Same problem here on an older macbook. 
Mid-2010 model with High Sierra 10.13.6
Python 3.7.5

I'm using the python API with pip.

Is this because of older CPU's not supporting certain features? Maybe we can [add a flag](https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10) ?

**Comment by underson14** [comment]
can you describe how you install? i have the same macbook. i have installed via pip and via conda and still shows illegal instruction.

**Comment by Christilut** [comment]
Just as per instructions on the spleeter help pages. Maybe clear everything and just install via conda to make sure nothing is conflicting?
