### ISSUE TITLE
[Discussion] High CPU load

### ISSUE THREAD

**Issue by aidv** [deezer/spleeter#115]
I'm running Spleeter using `spleeter-gpu`and it causes extremely high CPU load when running 3 instances of Spleeter at once.

Would anyone care to explain why this is happening?

I'm sure it's not a bug or anything, I'm just curious as to why it's happening.

**Comment by Faylixe** [comment]
Definitively not a bug. Spleeter is a high computation process, and the GPU version will only performs Tensorflow GPU related computation into the GPU device, other operation are performed into CPU (such as audio loading, processing, model loading, etc, etc, etc), it also use multiprocessing for track writing to disk. No surprise it is burning a CPU is you run three instance of it.

**Comment by aidv** [comment]
Makes sense. Thanks for clarifying.

So basically, even though the GPU might be used, it's not necessarily where the actual splitting occurs, hence the high CPU load?

**Comment by deseipel** [comment]
I see it max out my CPU just using one instance.  Granted its only for a few seconds.  But it takes out the audio while I'm livestreaming.  

Windows 10
Processor	Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz, 2904 Mhz, 8 Core(s), 16 Logical Processor(s)
GeForce RTX 3060 12GB RAM
