### ISSUE TITLE
[Discussion] FileNotFoundError When Trying to Train

### ISSUE THREAD

**Issue by clockworkred458** [deezer/spleeter#116]
### **Steps:**

1. Installed using anaconda
2. Run as: spleeter train -p sirens_config.json -d sirens_train.csv
3.  FileNotFoundError: [Errno 2] File b'configs/sirens_train.csv' does not exist: b'configs/sirens_train.csv'

sirens _train.csv definitely exists so I'm not sure what the issue is. any help would be great thanks!

**Comment by LanfearCai** [comment]
So you've had solution? I met the same problem.
