### ISSUE TITLE
[Discussion] Another formats for example

### ISSUE THREAD

**Issue by Gr33nEyes** [deezer/spleeter#119]
Can I use WAV, AIFF, FLAC as example files?

**Comment by Faylixe** [comment]
You can use any audio format that would be supported by ``ffmpeg``. We currently support export with following codec :

- WAV
- MP3
- OGG
- M4A
- WMA
- FLAC

**Comment by redbar0n** [comment]
@Faylixe when using a codec such as M4A, would it be the same as exporting to WAV and then using ffmpeg to convert (lossily) to M4A? Or does it export directly to M4A without loss?
