### ISSUE TITLE
Feature request: Add demos to the README

### ISSUE THREAD

**Issue by Joshfindit** [deezer/spleeter#12]
Some (like myself) are very curious about the methods and results, but don’t want or need to run the project ourselves.

Ideally a couple examples with starting file and resulting stems.
Maybe even at least one “ideal” example, and a least one example where the project still struggles, creating non-ideal output.

**Comment by mmoussallam** [comment]
Hi Josh,

Thanks for the suggestion, we're setting up a [Google Colab](https://colab.research.google.com/github/deezer/spleeter/blob/master/spleeter.ipynb). So far it has only the example file but we'll consider adding other samples with various separation performances.

**Comment by ZFTurbo** [comment]
I was impressed by project results and create small video with examples on some very good known music videos:
https://www.youtube.com/watch?v=IHSGrGXp_oo

**Comment by mmoussallam** [comment]
There's no easy way to add audio to the README but I guess the google colab solved this.
