### ISSUE TITLE
Distributing/combining training?

### ISSUE THREAD

**Issue by DAW-GUN** [deezer/spleeter#122]
Is there a way to have multiple users train different sets of stems and then later combine their efforts into one model?

**Comment by mmoussallam** [comment]
Theoretically you could train a single model sequentially,  each user training on its data at a time and then passing on to the other to "continue" the training. 

In a more distributed fashion, if you have N models trained independently on various sets, you could use ensembling techniques to average the spectrograms they produce. But there are no guarantee it would perform better.

**Comment by DAW-GUN** [comment]
Thanks for your feedback. Any thoughts as to how that can be done using the command line? Or can you suggest where I can find the info? I looked at the documentation and couldn't figure out how to do it.

**Comment by mmoussallam** [comment]
That's definitely not something you can do with the command line, you'll have to dig into the python API to do that.

**Comment by DAW-GUN** [comment]
Sorry - I was too specific. Instead, can you give me an example of what you were thinking of when you said, "Theoretically you could train a single model sequentially, each user training on its data at a time and then passing on to the other to "continue" the training." ?
