### ISSUE TITLE
[Bug] Minor code error in Wiki

### ISSUE THREAD

**Issue by jkeast** [deezer/spleeter#124]
Not quite a bug, but there is an error in the wiki's "API Reference" section:
Under the header "RAW waveform based separation" the first line of example code is `from spleeter.utils.audio.adapter import get_default_audio_adapter`
There is no module named `spleeter.utils.audio` --- this code should instead be `from spleeter.audio.adapter import get_default_audio_adapter`

**Comment by Faylixe** [comment]
Yes, we just deployed a new version with some API changes yesterday. We would update the documentation accordingly ASAP :)
