### ISSUE TITLE
[Bug] Minor bug in result path

### ISSUE THREAD

**Issue by rguilloteau** [deezer/spleeter#125]
## Description

There is a small issue in the Google Colab Notebook. The path given to listen the results is not the good one. The output path given is `audio_example/output`. In fact, the real output directory is `audio_example.mp3/output`. I found also this little mistake in the README.

## Step to reproduce

Just use the Google Colab Notebook

## Output

![Screenshot of the output](https://user-images.githubusercontent.com/38552534/69408568-27136e00-0cff-11ea-9f59-d53f840428d4.png)

**Comment by Faylixe** [comment]
> That's odd. It did use to write to `output/audio_example` (without the file extension in the directory name). This looks like a regression, possibly introduced in [d771fba](https://github.com/deezer/spleeter/commit/d771fbae34a5e4cd9dcc732e42c72491afa42b6f).

Yeah sound like a regression indeed. We introduce a file path formatting syntax in the new version, the default one should not output that way although. I will check that ASAP :)

**Comment by Faylixe** [comment]
Bug busted ! We will release a patch version (1.5.5) ASAP.
