### ISSUE TITLE
[Bug] Wron Output folder in Colab notebook

### ISSUE THREAD

**Issue by ohld** [deezer/spleeter#126]
When I run the Colab code it saves all produced sounds into a strange folder, so I had to manually rename the folder:

![image](https://user-images.githubusercontent.com/5613295/69439617-628e5680-0d58-11ea-8e34-eff01569ad42.png)

This is definitely wrong :) 

The link to colab:
https://colab.research.google.com/github/deezer/spleeter/blob/master/spleeter.ipynb

**Comment by Faylixe** [comment]
Duplicate bug. Fixed by next coming patch release.

**Comment by Faylixe** [comment]
Please reinstall Spleeter with 1.4.5 version and retry :)
