### ISSUE TITLE
[Bug] name your bug

### ISSUE THREAD

**Issue by Mooorad** [deezer/spleeter#129]
hi, sorry for my bad English I'm French
My issue : Terminal says : No such file or directory

I've read somewhere that "be sure to be in the spleeter folder if you are using cloned repository or replace audio_example.mp3 by a valid path to an audio file)", but I can't find where is the spleeter folder

Many thanks in advance !

**Comment by Faylixe** [comment]
Please follow the documentation for detailed installation. Closing the issue as it does not respect issue templating.
