### ISSUE TITLE
[Bug] Tuple formatting incorrectly included in output directory name

### ISSUE THREAD

**Issue by johnwmillr** [deezer/spleeter#130]
## Description

I am using the [separator.py](https://github.com/deezer/spleeter/blob/master/spleeter/separator.py) file to include `spleeter` in my own Python development. The [separate_to_file](https://github.com/deezer/spleeter/blob/85ff00797f6c615c62885793923eca952e9e791f/spleeter/separator.py#L93) function is erroneously including parentheses in the name of the output directory. The user does not have a way to avoid this formatting.

Example:
  > Input filename: `GilScottHeron_WeAlmostLostDetroit.mp3`
  > Output directory name : `('GilScottHeron_WeAlmostLostDetroit', '.mp3')/`

## Step to reproduce

1. Installed using `pip`
2. Run as a Python script
3. Got no error. The output directory name formatting is tuple.

```python
from spleeter.spleeter.separator import Separator
separator = Separator('spleeter:2stems')

filein = 'GilScottHeron_WeAlmostLostDetroit.mp3'
fileout = './stems'
separator.separate_to_file(filein, fileout, codec='mp3')
```

## Output
Output directory name : `./stems/('GilScottHeron_WeAlmostLostDetroit', '.mp3')/`

Expected output: `./stems/GilScottHeron_WeAlmostLostDetroit/`

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS |
| Installation type | `pip`         |
| RAM available     | 8 GB                             |
| Hardware spec     | CPU: 3.2 GHz Intel Core i5, GPU: NVIDIA GeForce GT 755M 1 GB |

## Additional context

The reason for this bug is [line 124 in `separator.py`](https://github.com/deezer/spleeter/blob/85ff00797f6c615c62885793923eca952e9e791f/spleeter/separator.py#L124). There needs to be a `[0]` added after the output of `splitext` so that the directory name is created from a `string`, not a `tuple`.

**Comment by Faylixe** [comment]
Thanks for spotting the bug and proposing fix :).

We will integrate your PR ASAP !

**Comment by johnwmillr** [comment]
Great! Thanks for making this awesome package available!
