### ISSUE TITLE
Documentation for "F" parameter in config file?

### ISSUE THREAD

**Issue by DAW-GUN** [deezer/spleeter#132]
From what I read, the F parameter in the config file sets the max frequency for training. I have not been able to find any documentation for this. The closest I could find is this description:

> Number of frequency bins to be processed (frequency above F are note processed)

Can you direct me to some documentation about this, or describe to me how to set the parameter?
For example, if my training stems go to 22000 Hz, what value would I put in F to train all the way up to 22000? My goal is to create a model that can then separate files up to 22000 Hz. 

Am I on the right or wrong track?

**Comment by romi1502** [comment]
The `F` parameter is used to reduce the input spectrograms size (and thus memory footprint and computation time) at the training stage. The frequency dimension of the input spectrograms (and thus of the target spectrogram) is truncated at `F`, and thus the model only learn until `F`

Note that if you perform training with the provided U-net architecture, the downsampling/upsampling structure of the model requires that `F` is a power of `2` (actually there are other values that could fit, but I don't want to go into details here).

So then, if you your spectrogram uses 4096 sample long windows, the number of frequency bins of your spectrogram (output of the STFT) will be `2049` and then you can choose `F=2048`(you'll then have almost fullband until 22050Hz), or `F=1024` (half-band, until about 11KHz), or anything lower that is a power of two.
