### ISSUE TITLE
[Discussion] How can I override the save to file step?

### ISSUE THREAD

**Issue by Scylla2020** [deezer/spleeter#135]
I've been trying to process multiple files at once using the separate_to_file function and would like to be able to specify a name for each file every loop instead of the default names of accompaniment and vocals.. Is there a way to do this, maybe a function I can override? I tried to just rename the files once they are created but the separate process that creates them doesn't seem to shut off afterwards so access to modify the file gets denied. Trying to kill the corresponding process terminates my script which is not ideal for my use case as I would like to integrate an interface. Thanks

**Comment by Faylixe** [comment]
You can use the recently introduced `filename_format` parameter while allow you to provide a Python formattable string.
