### ISSUE TITLE
[Bug] Fatal error in launcher

### ISSUE THREAD

**Issue by psylion** [deezer/spleeter#137]
## Description

..:> spleeter -h
produce:
Fatal error in launcher: Unable to create process using '"**d:\bld\spleeter_1574438388570\_h_env\python.exe**" C:\Users\----\Anaconda3\Scripts\spleeter.exe" -h'

Looks like the conda provide a binary pointing to a missing place ... there is no bld on my D: drive
## Step to reproduce

1. Installed using: conda install -c conda-forge spleeter
2. Run as Administrator
3. Got `...` Fatal error in launcher:  Unable to create process using '"d:\bld\spleeter_1574438388570\_h_env\python.exe" 

## Environment
|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 |
| Installation type | Conda            |
| RAM available     | 64Go                             |
| Hardware spec     |Nvidia GTX 1030 / Intel i9-9900 @3.60GHz|

**Comment by ngoname** [comment]
I've got the same error

**Comment by theboyks** [comment]
Also ran into this issue. Tried to remove the package and reinstall but same problem. I installed in addition to the normal package the spleeter-gpu as well to test and some spleeter commands seemed to work but of course it was looking for the CUDA driver. Seems like the main package is just missing a file.

**Comment by Stefvw26** [comment]
I've got the same error

**Comment by mmoussallam** [comment]
Hi everyone, this seems to be an issue of anaconda execution priviledge. Possibly you have installed Anaconda for administrator only (not ALL users).

People in this[ stackoverflow thread ](https://stackoverflow.com/questions/57339230/unable-to-create-process-using-c-bld-scrapy-1564674375870-h-env-python-exe) have  successfully overcome  this using either:

## Method 1
force reinstall of the package using pip:

`pip install --force-reinstall spleeter`

## Method 2
erase and reinstall Anaconda:

1. Use Add/Remove program to uninstall Anaconda
2. Install Anaconda again and make sure to select "Install for all users" during process.

Hope this helps

**Comment by alexburr** [comment]
This doesn't appear to help. Like @psylion, I have nothing in my "D:" drive (in fact it's an optical drive) so I don't understand why it's looking there at all.

**Comment by theboyks** [comment]
For me, this was apparently due to an old install of Miniconda. After uninstalling miniconda completely from add/remove programs and reinstalling the issue resolved itself.

**Comment by theboyks** [comment]
Hm yeah. After uninstall/reinstall of miniconda and spleeter same issues. No folder in D:\ either as noted above.
![Capture](https://user-images.githubusercontent.com/58204524/69683309-37ae4600-1069-11ea-90a9-3d86a25d0118.PNG)

**Comment by HansHermann123** [comment]
I have installed miniconda for all users from the start and I get the same error :-/

**Comment by psylion** [comment]
> Hi everyone, this seems to be an issue of anaconda execution priviledge. Possibly you have installed Anaconda for administrator only (not ALL users).
> 
> People in this[ stackoverflow thread ](https://stackoverflow.com/questions/57339230/unable-to-create-process-using-c-bld-scrapy-1564674375870-h-env-python-exe) have successfully overcome this using either:
> 
> ## Method 1
> force reinstall of the package using pip:
> 
> `pip install --force-reinstall spleeter`
> 
> ## Method 2
> erase and reinstall Anaconda:
> 
> 1. Use Add/Remove program to uninstall Anaconda
> 2. Install Anaconda again and make sure to select "Install for all users" during process.
> 
> Hope this helps

Method 1 Works for me
I just `pip install --force-reinstall spleeter` and now it works

Thanks @mmoussallam

**Comment by HansHermann123** [comment]
I could install it now, but I get an error at runtime about failing to load the TensorFlow lib (despite it was installed successfully). 
I installed Python 3.7.5, installed spleeter using pip from an administrator shell.

**Comment by mevsme** [comment]
The same error :( 12.07.2019

**Comment by ojaillet** [comment]
Same error for me, is there an issue ? 

Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_1574775894867\_h_env\python.exe"  "C:\ProgramData\Anaconda3\Scripts\spleeter.exe" separate -i spleeter/

**Comment by psylion** [comment]
Bug Closed: Solution provided above

**Comment by ojaillet** [comment]
OK, finally works with PIP method , but it wasn't so simple ! Thanks

**Comment by Caserol23** [comment]
> OK, finally works with PIP method , but it wasn't so simple ! Thanks

hey bro, you use the method that force spleeter install on stackoverflow?

**Comment by classikd** [comment]
I had the same error, i solved it by running:
`python -m spleeter separate`

Instead of :
`spleeter separate`

**Comment by Kaszanas** [comment]
@classikd solution worked just fine from within the Anaconda Prompt.

**Comment by aoakenfo** [comment]
After several attempts using conda, miniconda, and pip with various kinds of errors. pip --force-reinstall finally got it working, 

I'm curious...can this be released as a command-line Windows exe in the future? Or do the number of deps make this difficult to package? (I don't do a lot of python, so forgive me.)

**Comment by normann1974** [comment]
Same problem here when using miniconda installed for all users. Where does the "D:\blb\..." stuff come from? It seems to occur on all installations with the problem, and it definitely has nothing to do with my computer. D: is the optical drive. It has to be hardcoded in some source or binary somewhere.

**Comment by TUTUBIG** [comment]
> > Hi everyone, this seems to be an issue of anaconda execution priviledge. Possibly you have installed Anaconda for administrator only (not ALL users).
> > People in this[ stackoverflow thread ](https://stackoverflow.com/questions/57339230/unable-to-create-process-using-c-bld-scrapy-1564674375870-h-env-python-exe) have successfully overcome this using either:
> > ## Method 1
> > force reinstall of the package using pip:
> > `pip install --force-reinstall spleeter`
> > ## Method 2
> > erase and reinstall Anaconda:
> > 
> > 1. Use Add/Remove program to uninstall Anaconda
> > 2. Install Anaconda again and make sure to select "Install for all users" during process.
> > 
> > Hope this helps
> 
> Method 1 Works for me
> I just `pip install --force-reinstall spleeter` and now it works
> 
> Thanks @mmoussallam

method 2 could not solve this problem
