### ISSUE TITLE
[Discussion] How to correctly set bitrate?

### ISSUE THREAD

**Issue by Alessandro1996** [deezer/spleeter#138]
I have set command in order to have vocal and accomaniment in flac format, at a bitrate of 320kbps in 'output' destination folder.
What I wrote:

`spleeter separate -i 'songName.flac' -p spleeter:2stems -c flac -b 320k -o output`

What i get is two flac files (ok), but with higher bitrate than the one request by parameter `-b 320k`

Is there something wrong in wrinting the command? How should the bitrate parameter be written? (there's no explanation on that by reading the manual)

**Comment by mmoussallam** [comment]
Hi Alessandro,

Flac is a lossless compression format and it's output bitrate depends on the audio that you are compressing (you can think of it as zip on audio files), therefore setting a target bitrate in this case does not make sense and the parameter is ignored by ffmpeg at the encoding step.

**Comment by Alessandro1996** [comment]
Hi mmoussallam,
Thank you for the answer.
So for each lossless input file (flac, wav, ...) there's no way to set output's bitrate, am I right?

**Comment by OmarAshraf2030** [comment]
MusicRemover.com is available on Godaddy!

**Comment by boltomli** [comment]
For cases such as PCM wave, the bitrate is actually calculated by other parameters, like sampling rate, bit depth and channels. Multiply all together, probably. It's not an independent variable.
