### ISSUE TITLE
[Bug] vocals and accompaniment with high frequencies cut

### ISSUE THREAD

**Issue by Alessandro1996** [deezer/spleeter#139]
## Description
I split vocals and accompaniment from a song with this command:

`spleeter separate -i 'songName.flac' -p spleeter:2stems -c flac -o output`

The original flac file is recordered till 21 kHz, as shown in this picture:

![originalSongSpectrum](https://user-images.githubusercontent.com/37804468/69636768-9cf93b80-1057-11ea-94e5-742bc990ffd5.png)

The vocals.flac and accompaniment.flac have high frequencies cut to 11 kHz, as shown in these pictures:

![vocals](https://user-images.githubusercontent.com/37804468/69636864-d336bb00-1057-11ea-92c8-305d37fd1e5e.png)

![accompaniment](https://user-images.githubusercontent.com/37804468/69636878-da5dc900-1057-11ea-9080-49d7c51152db.png)

How to get the output files with high frequencies? Is there a way to already set this setting, or could it be a future feature?

**Comment by mmoussallam** [comment]
Hi Alessandro, yes this is normal : https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-

**Comment by romi1502** [comment]
We just updated the [FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-) to provide a new way of performing separation above 11kHz.
