### ISSUE TITLE
[Bug] Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by evgenyan1989** [deezer/spleeter#145]
Hello.
When I try to use spleeter, I am getting this error - Illegal instruction (core dumped)
All installations was without any errors, but I can't understand how to solve this error

**Comment by axil76** [comment]
Hello 
I have the same problem
spleeter separate -i audio_example.mp3 -o audio_output -p spleeter:4stems
Illegal instruction

file audio_example.mp3
`audio_example.mp3: Audio file with ID3 version 2.4.0MPEG ADTS, layer III, v1, 192 kbps, 44.1 kHz, Stereo`

the tool seems to work 

spleeter -h

> usage: spleeter [-h] {separate,train,evaluate} ...
> 
> positional arguments:
>   {separate,train,evaluate}
>     separate            Separate audio files
>     train               Train a source separation model
>     evaluate            Evaluate a model on the musDB test dataset
> 
> optional arguments:
>   -h, --help            show this help message and exit

My server 
lscpu

> Architecture:          x86_64
> CPU op-mode(s):        32-bit, 64-bit
> Byte Order:            Little Endian
> CPU(s):                16
> On-line CPU(s) list:   0-15
> Thread(s) per core:    1
> Core(s) per socket:    4
> Socket(s):             4
> NUMA node(s):          1
> Vendor ID:             GenuineIntel
> CPU family:            6
> Model:                 15
> Model name:            Intel(R) Xeon(R) CPU           E7330  @ 2.40GHz
> Stepping:              11
> CPU MHz:               2393.918
> BogoMIPS:              4787.83
> Virtualization:        VT-x
> L1d cache:             32K
> L1i cache:             32K
> L2 cache:              3072K
> NUMA node0 CPU(s):     0-15
> Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca lahf_lm dtherm tpr_shadow vnmi flexpriority
> 

How do you debug ?
Thank you ^^
See you soon

**Comment by evgenyan1989** [comment]
> Hello
> I have the same problem
> spleeter separate -i audio_example.mp3 -o audio_output -p spleeter:4stems
> Illegal instruction
> 
> file audio_example.mp3
> `audio_example.mp3: Audio file with ID3 version 2.4.0MPEG ADTS, layer III, v1, 192 kbps, 44.1 kHz, Stereo`
> 
> the tool seems to work
> 
> spleeter -h
> 
> > usage: spleeter [-h] {separate,train,evaluate} ...
> > positional arguments:
> > {separate,train,evaluate}
> > separate            Separate audio files
> > train               Train a source separation model
> > evaluate            Evaluate a model on the musDB test dataset
> > optional arguments:
> > -h, --help            show this help message and exit
> 
> My server
> lscpu
> 
> > Architecture:          x86_64
> > CPU op-mode(s):        32-bit, 64-bit
> > Byte Order:            Little Endian
> > CPU(s):                16
> > On-line CPU(s) list:   0-15
> > Thread(s) per core:    1
> > Core(s) per socket:    4
> > Socket(s):             4
> > NUMA node(s):          1
> > Vendor ID:             GenuineIntel
> > CPU family:            6
> > Model:                 15
> > Model name:            Intel(R) Xeon(R) CPU           E7330  @ 2.40GHz
> > Stepping:              11
> > CPU MHz:               2393.918
> > BogoMIPS:              4787.83
> > Virtualization:        VT-x
> > L1d cache:             32K
> > L1i cache:             32K
> > L2 cache:              3072K
> > NUMA node0 CPU(s):     0-15
> > Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca lahf_lm dtherm tpr_shadow vnmi flexpriority
> 
> How do you debug ?
> Thank you ^^
> See you soon

I still can't find solution =(( 
Is there anybody knows how to fix this error?

**Comment by axil76** [comment]
I found that 

https://tech.amikelive.com/node-887/how-to-resolve-error-illegal-instruction-core-dumped-when-running-import-tensorflow-in-a-python-program/

**Comment by Faylixe** [comment]
Not a valid issue, please fill issue according to the provided template.

**Comment by axil76** [comment]
that is to say ?
I did some testing :
```
 python3.6 -c 'import tensorflow as tf;'
Illegal instruction
```

> pip3.6 uninstalled tensorflow-1.14.0

> pip3.6 install tensorflow==1.5

```
python3.6 -c 'import tensorflow as tf; print(tf.__version__)'
1.5.0
```
now I have another error message 
No module named 'tensorflow.compat'

**Comment by axil76** [comment]
import tensorflow as tf; print(tf.__version__)
dir(tf)
the compat function exists

**Comment by evgenyan1989** [comment]
> that is to say ?
> I did some testing :
> 
> ```
>  python3.6 -c 'import tensorflow as tf;'
> Illegal instruction
> ```
> 
> > pip3.6 uninstalled tensorflow-1.14.0
> 
> > pip3.6 install tensorflow==1.5
> 
> ```
> python3.6 -c 'import tensorflow as tf; print(tf.__version__)'
> 1.5.0
> ```
> 
> now I have another error message
> No module named 'tensorflow.compat'

I done the same, and have the same problems =))Trying to find solution today =)
