### ISSUE TITLE
[Bug] Typo in wiki page

### ISSUE THREAD

**Issue by boltomli** [deezer/spleeter#146]
## Description

In the wiki page <https://github.com/deezer/spleeter/wiki/1.-Installation>, `If you do not feel confortable` is a typo, where it should be `comfortable`.

## Step to reproduce

Just open the wiki page.

## Output

N/A

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows / Linux / MacOS / other |
| Installation type | Conda / pip / other             |
| RAM available     | XGo                             |
| Hardware spec     | GPU / CPU / etc ...             |

**Comment by mmoussallam** [comment]
Fixed ! Thank you :+1:
