### ISSUE TITLE
[Bug] name your bug

### ISSUE THREAD

**Issue by mattmau99** [deezer/spleeter#147]
## Description

When I try to run the example in the README I get this error:

## Step to reproduce

Follow steps in README
## Output

```bash
Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_1574775894867\_h_env\python.exe
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows|
| Installation type | Conda |
| RAM available     | 16Go                             |
| Hardware spec     | Intel UHD Graphics 620/ Intel i7 8550U/|

**Comment by Faylixe** [comment]
Duplicate with #149
