### ISSUE TITLE
[Feature] Add Version Flag

### ISSUE THREAD

**Issue by dts350z** [deezer/spleeter#148]
## Description

There should be a version flag. Ideally both for the code and the model

**Comment by Faylixe** [comment]
That not a bad idea. As for the library it won't take long. Although it will requires a little bit of work for the model as we are not downloading any metadata from it (and user could totally download model from another source, or have it trained locally).

We need to think about it, meanwhile I flag this issue for next release as we will at least implement version option for the library.
