### ISSUE TITLE
[Bug] python path hardcoded in launcher?

### ISSUE THREAD

**Issue by dts350z** [deezer/spleeter#149]
## Description

>spleeter -h
Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_1574775894867\_h_env\python.exe"  "C:\Users\Glenn.THEBEAST\Anaconda3\Scripts\spleeter.exe" -h'

## Step to reproduce

1. Installed using 
git clone https://github.com/Deezer/spleeter
conda install -c conda-forge spleeter

2. Run as
>spleeter -h

3. Got  error Fatal error in launcher

>spleeter -h
Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_1574775894867\_h_env\python.exe"  "C:\Users\Glenn.THEBEAST\Anaconda3\Scripts\spleeter.exe" -h'

Note that "d:\bld" doesn't exist on my computer.  

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows|
| Installation type | Conda            |
| RAM available     | 32GB                             |
| Hardware spec     | Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, 3696 Mhz, 6 Core(s), 12 Logical Processor(s) / Adapter Description	NVIDIA GeForce GTX 1070
           |

## Additional context

for 1.48 (compared to 1.4 anyway) it seems like you dropped the conda environment support.

Original install instructions (that worked for me on the initial release version) were:

conda install -c anaconda git
git clone https://github.com/Deezer/spleeter
conda env create -f spleeter/conda/spleeter-cpu.yaml
conda activate spleeter-cpu
spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output

In this version there is no yaml file so it seems you are expecting people to use their base conda environment? 

also note the install output looks a little unusual (see "failed with") :

>conda install -c conda-forge spleeter
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Glenn.THEBEAST\Anaconda3

  added / updated specs:
    - spleeter

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _tflow_select-2.3.0        |              mkl           3 KB
    conda-4.7.12               |           py37_0         3.0 MB  conda-forge
    libmklml-2019.0.5          |                0        17.4 MB
    tensorflow-1.14.0          |mkl_py37h7908ca0_0           5 KB
    tensorflow-base-1.14.0     |mkl_py37ha978198_0        35.8 MB
    ------------------------------------------------------------
                                           Total:        56.2 MB

The following NEW packages will be INSTALLED:

  _tflow_select      pkgs/main/win-64::_tflow_select-2.3.0-mkl
  absl-py            conda-forge/win-64::absl-py-0.8.1-py37_0
  astor              conda-forge/noarch::astor-0.7.1-py_0
  ffmpeg             conda-forge/win-64::ffmpeg-4.2-h6538335_0
  ffmpeg-python      conda-forge/noarch::ffmpeg-python-0.2.0-py_0
  gast               conda-forge/noarch::gast-0.3.2-py_0
  grpcio             conda-forge/win-64::grpcio-1.23.0-py37h3db2c7e_0
  keras-applications conda-forge/noarch::keras-applications-1.0.8-py_1
  keras-preprocessi~ conda-forge/noarch::keras-preprocessing-1.1.0-py_0
  libmklml           pkgs/main/win-64::libmklml-2019.0.5-0
  libprotobuf        conda-forge/win-64::libprotobuf-3.11.0-h1a1b453_0
  markdown           conda-forge/noarch::markdown-3.1.1-py_0
  norbert            conda-forge/noarch::norbert-0.2.1-py_0
  protobuf           conda-forge/win-64::protobuf-3.11.0-py37he025d50_0
  spleeter           conda-forge/win-64::spleeter-1.4.8-py37_0
  tensorboard        conda-forge/win-64::tensorboard-1.14.0-py37_0
  tensorflow         pkgs/main/win-64::tensorflow-1.14.0-mkl_py37h7908ca0_0
  tensorflow-base    pkgs/main/win-64::tensorflow-base-1.14.0-mkl_py37ha978198_0
  tensorflow-estima~ conda-forge/win-64::tensorflow-estimator-1.14.0-py37h5ca1d4c_0
  termcolor          conda-forge/noarch::termcolor-1.1.0-py_2

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.10.16~ --> conda-forge::ca-certificates-2019.11.28-hecc5488_0
  certifi               pkgs/main::certifi-2019.9.11-py37_0 --> conda-forge::certifi-2019.11.28-py37_0

The following packages will be SUPERSEDED by a higher-priority channel:

  conda                                           pkgs/main --> conda-forge
  openssl              pkgs/main::openssl-1.1.1d-he774522_3 --> conda-forge::openssl-1.1.1d-hfa6e2cd_0
  pandas             pkgs/main::pandas-0.25.3-py37ha925a31~ --> conda-forge::pandas-0.25.1-py37he350917_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
tensorflow-base-1.14 | 35.8 MB   | ############################################################################ | 100%
_tflow_select-2.3.0  | 3 KB      | ############################################################################ | 100%
conda-4.7.12         | 3.0 MB    | ############################################################################ | 100%
libmklml-2019.0.5    | 17.4 MB   | ############################################################################ | 100%
tensorflow-1.14.0    | 5 KB      | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by Faylixe** [comment]
Hi and thanks the detailed issue :).

Indeed we removed environment file as we have now Spleeter package directly available in Conda-forge. Nothing prevent though to use a custom environment in which you are installing spleeter from conda-forge.

Several issues were reported with this strange `d:\bld` path on Windows since we migrated to conda forge. We will keep this one open as reference and let you know as long as we found a solution to this problem.

**Comment by Faylixe** [comment]
And for the record no, the path is not hardcoded :D. The spleeter executable is automatically generated during installation by pip / conda.

**Comment by dts350z** [comment]
How would one have both cpu and gpu installs, the way this is setup now? It seems like they conflict.

**Comment by Faylixe** [comment]
> How would one have both cpu and gpu installs, the way this is setup now? It seems like they conflict.

Well, the initial goal was to provide an "easier" installation method for non tech people. The shorter the better, and having a command line which is path / location agnostic is always better for someone who discover a terminal for a first time than a file based approach.

The idea is that someone familiar with conda just need to know that the package is available in conda-forge and deal with it. As I said, nothing prevent you to use your own conda environment file :

```yaml
name: spleeter-env

channels:
  - conda-forge

dependencies:
  - python=3.7
  - spleeter
```

(Actually if you can try and tell me if the environment approach works with this envfile that would be great :D).

**Comment by dts350z** [comment]
OK I will do that in a VM. Is the git clone step still required?

**Comment by dts350z** [comment]
Fresh install of Anaconda on windows 10 VM, using your yaml file:


(base) C:\Users\IEUser>conda env create -f "C:\Users\IEUser\Anaconda3\spleeter-env.yaml"
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
hdf5-1.10.5          | 35.1 MB   | ####################################################################################################### | 100%
grpcio-1.23.0        | 1.0 MB    | ####################################################################################################### | 100%
idna-2.8             | 100 KB    | ####################################################################################################### | 100%
python-3.7.3         | 17.7 MB   | ####################################################################################################### | 100%
python-dateutil-2.8. | 220 KB    | ####################################################################################################### | 100%
pysocks-1.7.1        | 27 KB     | ####################################################################################################### | 100%
numpy-1.17.3         | 4.6 MB    | ####################################################################################################### | 100%
keras-applications-1 | 30 KB     | ####################################################################################################### | 100%
ca-certificates-2019 | 182 KB    | ####################################################################################################### | 100%
sqlite-3.30.1        | 1.1 MB    | ####################################################################################################### | 100%
keras-preprocessing- | 33 KB     | ####################################################################################################### | 100%
urllib3-1.25.7       | 159 KB    | ####################################################################################################### | 100%
pandas-0.25.1        | 9.6 MB    | ####################################################################################################### | 100%
pytz-2019.3          | 237 KB    | ####################################################################################################### | 100%
pyreadline-2.1       | 141 KB    | ####################################################################################################### | 100%
mkl-service-2.3.0    | 52 KB     | ####################################################################################################### | 100%
zlib-1.2.11          | 236 KB    | ####################################################################################################### | 100%
pip-19.3.1           | 1.9 MB    | ####################################################################################################### | 100%
cffi-1.13.2          | 220 KB    | ####################################################################################################### | 100%
tensorboard-1.14.0   | 3.2 MB    | ####################################################################################################### | 100%
tensorflow-1.14.0    | 5 KB      | ####################################################################################################### | 100%
openssl-1.1.1d       | 4.7 MB    | ####################################################################################################### | 100%
libblas-3.8.0        | 3.5 MB    | ####################################################################################################### | 100%
astor-0.7.1          | 22 KB     | ####################################################################################################### | 100%
scipy-1.3.1          | 14.3 MB   | ####################################################################################################### | 100%
protobuf-3.11.0      | 583 KB    | ####################################################################################################### | 100%
win_inet_pton-1.1.0  | 7 KB      | ####################################################################################################### | 100%
libprotobuf-3.11.0   | 2.2 MB    | ####################################################################################################### | 100%
absl-py-0.8.1        | 158 KB    | ####################################################################################################### | 100%
tensorflow-estimator | 646 KB    | ####################################################################################################### | 100%
requests-2.22.0      | 84 KB     | ####################################################################################################### | 100%
future-0.18.2        | 739 KB    | ####################################################################################################### | 100%
norbert-0.2.1        | 13 KB     | ####################################################################################################### | 100%
ffmpeg-python-0.2.0  | 25 KB     | ####################################################################################################### | 100%
wrapt-1.11.2         | 44 KB     | ####################################################################################################### | 100%
wheel-0.33.6         | 52 KB     | ####################################################################################################### | 100%
termcolor-1.1.0      | 6 KB      | ####################################################################################################### | 100%
certifi-2019.11.28   | 148 KB    | ####################################################################################################### | 100%
h5py-2.10.0          | 949 KB    | ####################################################################################################### | 100%
gast-0.3.2           | 11 KB     | ####################################################################################################### | 100%
setuptools-42.0.1    | 680 KB    | ####################################################################################################### | 100%
pyopenssl-19.0.0     | 81 KB     | ####################################################################################################### | 100%
six-1.13.0           | 22 KB     | ####################################################################################################### | 100%
wincertstore-0.2     | 13 KB     | ####################################################################################################### | 100%
liblapack-3.8.0      | 3.5 MB    | ####################################################################################################### | 100%
libmklml-2019.0.5    | 17.4 MB   | ####################################################################################################### | 100%
pycparser-2.19       | 171 KB    | ####################################################################################################### | 100%
markdown-3.1.1       | 60 KB     | ####################################################################################################### | 100%
ffmpeg-4.2           | 23.4 MB   | ####################################################################################################### | 100%
cryptography-2.8     | 567 KB    | ####################################################################################################### | 100%
werkzeug-0.16.0      | 259 KB    | ####################################################################################################### | 100%
libcblas-3.8.0       | 3.5 MB    | ####################################################################################################### | 100%
chardet-3.0.4        | 184 KB    | ####################################################################################################### | 100%
tensorflow-base-1.14 | 35.8 MB   | ####################################################################################################### | 100%
spleeter-1.4.8       | 112 KB    | ####################################################################################################### | 100%
_tflow_select-2.3.0  | 3 KB      | ####################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate spleeter-env
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\IEUser>conda activate spleeter-env

(spleeter-env) C:\Users\IEUser>spleeter separate -i "C:\Users\IEUser\Music\Love Alive.flac" -o "C:\Users\IEUser\Music\Love Alive.flac" -p spleeter:4stems
Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_1574775894867\_h_env\python.exe"  "C:\Users\IEUser\Anaconda3\envs\spleeter-env\Scripts\spleeter.exe" separate -i "C:\Users\IEUser\Music\Love Alive.flac" -o "C:\Users\IEUser\Music\Love Alive.flac" -p spleeter:4stems'

(spleeter-env) C:\Users\IEUser>

**Comment by TheIntelloBox** [comment]
Yes please fix this issue. :/

**Comment by antimYT** [comment]
this worked for me:
`pip install --force-reinstall spleeter`

**Comment by jimhanks** [comment]
> this worked for me:
> `pip install --force-reinstall spleeter`
Ah! Yes, that worked for me as well. Was pulling my hair out as I had it working a week ago and then it didn't for some unknown reason. Finally reinstalled everything, did the force-reinstall and I'm back in business again.

For what it's worth, the first time I ran the 'separate' command, I got a different error:
FileExistsError: [Errno 17] Cannot create a file when that file already exists:
'audio_output\\audio_example'

but just running it again, both stems were created.

**Comment by siebrand030** [comment]
> this worked for me:
> `pip install --force-reinstall spleeter`

Yes, thank you!

**Comment by dts350z** [comment]
but the point is to fix the conda-forge method.

mixing pip and conda is likely to mess up your conda environment long term,
yeah?

**Comment by mevsme** [comment]
yeah, conda sucks.  pip force reinstall works :+1:

**Comment by FinlayDaG33k** [comment]
pip force reinstall doesn't seem to do anything here:
```
ERROR: Could not find a version that satisfies the requirement spleeter (from versions: none)
ERROR: No matching distribution found for spleeter
```

**Comment by mmoussallam** [comment]
I'm closing this issue since it's similar to #154  just leaving the short answer here if people come across it and don't want the long discussion:

The `spleeter`  shortcut command appears to be wrongfully installed using conda on windows but you can use the alternative:
`python -m spleeter separate`
