### ISSUE TITLE
[Bug] Does not process my mp3

### ISSUE THREAD

**Issue by dudedad** [deezer/spleeter#150]
## Description

spleeter crashs when I feed it my own mp3 file (instead of the "audio_example.mp3" ).

It does not produce any error messages or output files.

## Step to reproduce

[Watch the video here.](https://www.dropbox.com/s/ijv5n3xf3rk0cns/Demo%20success%20and%20then%20failure.mp4?dl=0)

**It works when I docker run it like this:**
docker run     -v $AUDIO_IN:/input     -v $AUDIO_OUT:/output     -v $MODEL_DIRECTORY:/model     -e MODEL_PATH=/model     researchdeezer/spleeter      separate -i audio_example.mp3   -o /output -p spleeter:5stems

**It crashes when I run it like this:**
docker run     -v $AUDIO_IN:/input     -v $AUDIO_OUT:/output     -v $MODEL_DIRECTORY:/model     -e MODEL_PATH=/model     researchdeezer/spleeter      separate -i  /input/growinup.mp3   -o /output -p spleeter:5stems

[This is the audio file I am working on](https://www.dropbox.com/s/t4wlfcfta19x5pd/growinup.mp3?dl=0) . ( mp3 192k) 

[Here is a screenshot of my directory structure ](https://www.dropbox.com/s/bswyvp4qdixic1f/spleeter%20file%20structure.png?dl=0)(showing the /input , /output , /model directories

## Output

Nothing.   No errors, no output files

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                |  MacOS / 10.14.6 |
| Installation type | docker      |
| RAM available     | 16 GB                         |
| Hardware spec     | 2018 Macbook Pro 15 inch  2.6 GHz Intel Core i7 |

## Additional context

Tried a lot of different things troubleshooting this.... I even opened my mp3 in vlc and "converted" it and saved it as a plain mp3

**Comment by Faylixe** [comment]
No link or file upload here for legal reasons. Shutting down the issue. (Plus read the manual for memory issues)
