### ISSUE TITLE
[Bug] /input/[file.mp3]: No such file or directory

### ISSUE THREAD

**Issue by dudedad** [deezer/spleeter#152]
## Description

Using Docker, I can successfully run the default 2stem command using the audio_example.mp3
However, when I try to use my own file, which is located in the /input folder, I get a ff probe error with message "/input/growinup.mp3: No such file or directory"

I can immediately do an ls and see the file.

## Step to reproduce

1. docker start with 4 GB of memory:
VBoxManage modifyvm default --memory 4096

2. docker-machine start

3)docker-machine env

4) $(docker-machine env)

5) docker run     -v $AUDIO_IN:/input     -v $AUDIO_OUT:/output     -v $MODEL_DIRECTORY:/model     -e MODEL_PATH=/model     researchdeezer/spleeter      separate -i /input/growinup.mp3   -o /output -p spleeter:5stems
2. Got `file not found ` error

## Output

```bash
ERROR:spleeter:An error occurs with ffprobe (see ffprobe output below)

ffprobe version 4.1.4-1~deb10u1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
/input/growinup.mp3: No such file or directory

kens-mbp:~ kenadler$ ls /Users/kenadler/input/growinup.mp3
/Users/kenadler/input/growinup.mp3
kens-mbp:~ kenadler$ echo $AUDIO_IN
/input
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS |
| Installation type | docker       |
| RAM available     | 4GB                             |
| Hardware spec     | macbook pro 2018          |

## Additional context

it will work if I do:

docker run     -v $AUDIO_IN:/input     -v $AUDIO_OUT:/output     -v $MODEL_DIRECTORY:/model     -e MODEL_PATH=/model     researchdeezer/spleeter      separate -i audio_example.mp3   -o /output -p spleeter:5stems

**Comment by carchub** [comment]
I'm getting the same error, though I'm unsure why. Following this in case there's any development, sorry for the lack of skills necessary to help.

**Comment by dudedad** [comment]
The trick is to define the full path name in the $Audo_In.   Don't use a relative path.
