### ISSUE TITLE
[Bug] Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_1574775894867_h_env\python.exe"  "C:\Users\(Me)\Anaconda3\Scripts\spleeter.exe" separate -i spleeter/BLEACH.mp3 -p spleeter:4stems -o output'

### ISSUE THREAD

**Issue by NXG2005** [deezer/spleeter#154]
So I have been trying to install spleeter for the past 4 or 5 hours now and i have installed so many other things in order to make sure that is works, and when i copy the commands, it says that it is unable to create process using '"d:\bld\spleeter_1574775894867_h_env\python.exe"  "C:\Users\(Me)\Anaconda3\Scripts\spleeter.exe" separate -i spleeter/BLEACH.mp3 -p spleeter:4stems -o output' and the same thing happens when I copy and paste the command that is on here. Am I doing something wrong?

**Comment by cantenac57** [comment]
Same issue, exactly same problem...

**Comment by cantenac57** [comment]
NXG2005 try this : 
python -m spleeter separate  -i spleeter/BLEACH.mp3 -p spleeter:4stems -o output

it worked for me...

**Comment by mmoussallam** [comment]
Added an entry in the FAQ section regarding this. It's still not clear to us what is causing this:
https://github.com/deezer/spleeter/wiki/5.-FAQ#launcher-error

**Comment by mmoussallam** [comment]
Hi everyone, 

I'm doing a bit of cleaning and no-one complained about this for a long time (and there are instructions in the FAQ to overcome) so I'm closing this.
