### ISSUE TITLE
[Discussion] What's the difference between Xstems and Xstems-finetune models ?

### ISSUE THREAD

**Issue by divideconcept** [deezer/spleeter#156]
The github release links to 2 versions for each steams model (2/4/5) : Xstems and Xstems-finetune.
What's the difference between the 2 kind of models, and how/why would you use one over the other ?

**Comment by romi1502** [comment]
The Xstems-finetune contains extra optimizer parameters that makes it possible to continue training on your own data (fine-tune the model with your own data). Other than that, they are the same as the Xstems models.
If you just want to perform separation, the Xstems-finetune models are useless as the extra optimizer parameters won't be used (and the model files are quite bigger).
