### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by solidgamer** [deezer/spleeter#159]
Hello, I have following error when trying to use spleeter. I followed all the guidelines and ffmpeg is installed (with pip). I used python 3.7.5 and win10. I add PATHS in env. variable. We can see in the trace that it does find the directory of ffmpeg so it's not the problem. I tried first with anaconda but it was not working at all. I spend a lot of hours trying to find solution for the problem, but I do not understand python and what i need to change in the code to make it work. Im starting to get really furstrated,

Could you please help?

>spleeter separate -i File.mp3 -o audio_output

Traceback (most recent call last):
  File "C:\Users\<name>\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.4.8', 'console_scripts', 'spleeter')()
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 43, in entrypoint
    synchronous=False
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 122, in separate_to_file
    sample_rate=self._sample_rate)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\audio\ffmpeg.py", line 63, in load
    probe = ffmpeg.probe(path)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Thanks and Regards

**Comment by fibo** [comment]
Is that `C:\Users<name>` for real? If you actually see it, it is strange.

Try to add the complete path of the *File.mp3*, for instance

    spleeter separate -i C:\Users\<name>\Documents\File.mp3 -o audio_output

or if your MSDos prompt is in the same folder where you have your File.mp3, just

      spleeter separate -i .\File.mp3 -o audio_output

**Comment by solidgamer** [comment]
Hi, thanks for answer. the "C:\Users<name>" is typo as I replaced the real name

I tried as you indicated both commands with the full path, I was already in the right folder on the cmd msdos prompt but it does exactly the same error

spleeter separate -i C:\Users\<name>\Music\SpleeterTrain\Intro.mp3 -o audio_output
Traceback (most recent call last):
  File "C:\Users\<name>\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in <module>
    load_entry_point('spleeter==1.4.8', 'console_scripts', 'spleeter')()
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 43, in entrypoint
    synchronous=False
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 122, in separate_to_file
    sample_rate=self._sample_rate)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\audio\ffmpeg.py", line 63, in load
    probe = ffmpeg.probe(path)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\<name>\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by aghaee1367** [comment]
i have same problem !!!

**Comment by aghaee1367** [comment]
> Hello, I have following error when trying to use spleeter. I followed all the guidelines and ffmpeg is installed (with pip). I used python 3.7.5 and win10. I add PATHS in env. variable. We can see in the trace that it does find the directory of ffmpeg so it's not the problem. I tried first with anaconda but it was not working at all. I spend a lot of hours trying to find solution for the problem, but I do not understand python and what i need to change in the code to make it work. Im starting to get really furstrated,
> 
> Could you please help?
> 
> > spleeter separate -i File.mp3 -o audio_output
> 
> Traceback (most recent call last):
> File "C:\Users<name>\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in
> load_entry_point('spleeter==1.4.8', 'console_scripts', 'spleeter')()
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter__main__.py", line 54, in entrypoint
> main(sys.argv)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter__main__.py", line 46, in main
> entrypoint(arguments, params)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 43, in entrypoint
> synchronous=False
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 122, in separate_to_file
> sample_rate=self._sample_rate)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\audio\ffmpeg.py", line 63, in load
> probe = ffmpeg.probe(path)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\ffmpeg_probe.py", line 20, in probe
> p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in **init**
> restore_signals, start_new_session)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child
> startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> Thanks and Regards

i have same problem !!!   i try with "pip" package management for download and install Lib
after install Anaconda package management and run command 
>conda install -c conda-forge spleeter
everything ok and create 2 file in out folder

**Comment by mmoussallam** [comment]
Hi, seems to be an ffmpeg issue can you share the output of `ffprobe <your_file>` please ?

**Comment by mmutee** [comment]
I am having the same issue, using Pip (python 3.6.2 x64) method to install Spleeter.

`D:\Python362\Scripts>python -m spleeter separate -i test.mp3 -p spleeter:2stems -o out

Traceback (most recent call last):
  File "D:\Python362\lib\site-packages\spleeter\audio\ffmpeg.py", line 63, in load
    probe = ffmpeg.probe(path)
AttributeError: module 'ffmpeg' has no attribute 'probe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python362\lib\runpy.py", line 193, in _run_module_as_main    "__main__", mod_spec)
  File "D:\Python362\lib\runpy.py", line 85, in _run_code    exec(code, run_globals)
  File "D:\Python362\lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "D:\Python362\lib\site-packages\spleeter\__main__.py", line 54, in entrypoint    main(sys.argv)
  File "D:\Python362\lib\site-packages\spleeter\__main__.py", line 46, in main    entrypoint(arguments, params)
  File "D:\Python362\lib\site-packages\spleeter\commands\separate.py", line 43,in entrypoint    synchronous=False
  File "D:\Python362\lib\site-packages\spleeter\separator.py", line 122, in separate_to_file    sample_rate=self._sample_rate)
  File "D:\Python362\lib\site-packages\spleeter\audio\ffmpeg.py", line 64, in load    except ffmpeg._run.Error as e:
AttributeError: module 'ffmpeg' has no attribute '_run'`

These are the packages list in my python installation
D:\Python362\Lib\site-packages

> ffmpeg
> ffmpeg_python-0.2.0.dist-info
> ffmpeg-1.4.dist-info
> ffprobe
> ffprobe_python-1.0.3.dist-info
> ffprobe-0.5.dist-info

I read in one of the threads here that this could be because of missing ffmpeg, but I seem to have ffmpeg and ffprobe. I am not familiar with Python packages or Python programming. The wiki mentioned the PIP method which I used. I have even copied ffprobe.exe beside the spleeter.exe in D:\Python362\Scripts\

Also, Should I make a new thread for this? Thanks!

**Comment by Anandhfullstack** [comment]
> Hello, I have following error when trying to use spleeter. I followed all the guidelines and ffmpeg is installed (with pip). I used python 3.7.5 and win10. I add PATHS in env. variable. We can see in the trace that it does find the directory of ffmpeg so it's not the problem. I tried first with anaconda but it was not working at all. I spend a lot of hours trying to find solution for the problem, but I do not understand python and what i need to change in the code to make it work. Im starting to get really furstrated,
> 
> Could you please help?
> 
> > spleeter separate -i File.mp3 -o audio_output
> 
> Traceback (most recent call last):
> File "C:\Users<name>\AppData\Local\Programs\Python\Python37\Scripts\spleeter-script.py", line 11, in
> load_entry_point('spleeter==1.4.8', 'console_scripts', 'spleeter')()
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter__main__.py", line 54, in entrypoint
> main(sys.argv)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter__main__.py", line 46, in main
> entrypoint(arguments, params)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\commands\separate.py", line 43, in entrypoint
> synchronous=False
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\separator.py", line 122, in separate_to_file
> sample_rate=self._sample_rate)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\spleeter\audio\ffmpeg.py", line 63, in load
> probe = ffmpeg.probe(path)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\site-packages\ffmpeg_probe.py", line 20, in probe
> p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in **init**
> restore_signals, start_new_session)
> File "c:\users<name>\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child
> startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> Thanks and Regards

I have the same issue is it possible to solve?
![error](https://user-images.githubusercontent.com/45931976/71167236-4a462480-228f-11ea-8b89-4a9268880e44.PNG)

**Comment by mmutee** [comment]
Anandhfullstack, I am not a Python programmer myself so can't say this with confidence. You haven't mentioned if you have installed the binaries of FFMPEG (i.e., ffmpeg.exe. ffprobe.exe etc from ffmpeg.org or someother site). You need to do that and add its location to your PATH. (e.g., c:\program files\ffmpeg\bin\", this is in addition to the FFMPEG Python package.

**Comment by Anandhfullstack** [comment]
![path](https://user-images.githubusercontent.com/45931976/71171207-318e3c80-2298-11ea-8cb8-af2e3d9c23f7.PNG)
Hi I installed and added to that path but it did not work

**Comment by mmutee** [comment]
I am not sure if I have ever seen PATH variable containing just one entry. For example one my system has this stored in PATH (Win 7, administrator)

F:\Python3\Python37-32\Scripts\;F:\Python3\Python37-32\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\80\Tools\Binn\;C:\Program Files\QuickTime\QTSystem\;C:\Program Files\waf;C:\Python27\;C:\Python27\Scripts;C:\Program Files\LOVE

**Comment by Anandhfullstack** [comment]
I solved the issue by replacing ffmpeg ,ffplay,ffprobe files in same  folder _main_.py file located

**Comment by mmutee** [comment]
Great.
