### ISSUE TITLE
setuptools package version requirement during installation

### ISSUE THREAD

**Issue by erdaldogan** [deezer/spleeter#16]
I got the following error when I was installing spleeter via pip. I didn't had setuptools installed on my system previously. Just to let you know.

ERROR: tensorboard 1.14.0 has requirement setuptools>=41.0.0, but you'll have setuptools 40.8.0 which is incompatible.

**Comment by Faylixe** [comment]
Which version of Python are you using and which OS please ?

**Comment by aadibajpai** [comment]
In general, the command to update setuptools would be `pip install -U setuptools`. Use pip3 if that's what you use.

**Comment by erdaldogan** [comment]
@Faylixe macOS Mojave 10.14.6 & Python 3.7.4

I ran pip3 install spleeter

**Comment by Faylixe** [comment]
You should then try

```bash
pip install -U setuptools
```

as suggested by @aadibajpai or 

```bash
pip3 install setuptools>=41.0.0
```

We will update `PyPi` package to reflect the `setuptools` dep explicitly

**Comment by aadibajpai** [comment]
> We will update `PyPi` package to reflect the `setuptools` dep explicitly

Since it's a subdependency if you start doing this the rabbit hole might be too deep :P 

Imho the error message is self explanatory :)

**Comment by Faylixe** [comment]
Well actually we are using `setuptools` in *Spleeter* installation script so it still make sense :)

**Comment by aadibajpai** [comment]
> Well actually we are using `setuptools` in _Spleeter_ installation script so it still make sense :)

You mean here (https://github.com/deezer/spleeter/blob/master/setup.py)?
