### ISSUE TITLE
[Discussion] No GPU stress

### ISSUE THREAD

**Issue by aidv** [deezer/spleeter#161]
Curious as to why activity monitor on Windows tells me that my GPU is barely used during `spleeter-gpu`.

I know for a fact that `spleeter-gpu` is running because my spleeter sessions complete A LOT faster now compared to when I run `spleeter-cpu`.

Usage: 3%
Dedicated GPU-Memory: 0,7 / 8,0 GB
GPU-Memory: 0,8 / 16,0 GB
Shared GPU-Memory: 0,1 / 8,0 GB

Why is this happening?
How can I take advantage of this?

Could on-board graphics be involved here?

**Comment by mmoussallam** [comment]
Since you have OOM in your Gpu's on another issue I assume this has been solved :)

**Comment by aidv** [comment]
@mmoussallam yes. I forgot to close and refer to the other post. Thanks for closing
