### ISSUE TITLE
[Bug] Critical issue with "Serving" temp dir

### ISSUE THREAD

**Issue by aidv** [deezer/spleeter#165]
#82  Description

It seems like the "Serving" temp dir doesn't get cleared causing the whole hard drive to fill up.

## Step to reproduce reproduce the behavior: -->

1. Use Spleeter many times
2. Done

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 |
| Installation type | Conda             |
| RAM available     | 32GB                             |
| Hardware spec     | Any             |

**Comment by enx1998** [comment]
Hi,
I have the same problem: temporary folder /tmp/serving isn't emptied after the separate process is completed

**Comment by martinratinaud** [comment]
Hi All
Me neither
I ended up cleaning it manually after each update

Anyway thank you very much for this awesome tool. I built https://www.edityouraudio.com with it to spread the love you gave :-)

**Comment by floydback** [comment]
Is _/tmp/serving/.../variables/model.data-00000-of-00001_ and _pretrained_models/2stems/model.data-00000-of-00001_ files are the same? Why? Is it normal?

**Comment by martinratinaud** [comment]
@mmoussallam can you explained why you closed this ?

Thanks you

**Comment by mmoussallam** [comment]
Oops sorry I did not meant to close this one.

**Comment by expectopatronum** [comment]
I changed the last lines of `to_predictor` to:

```
    versions = sorted(versions)
    latest = str(versions[-1])
    old = versions[:-1]
    for o in old:
        print("removing", o)
        shutil.rmtree(str(o), ignore_errors=True)
```
to remove all old models because it also filled my hard drive when running several experiments.
