### ISSUE TITLE
spleeter:2stems protocole not found

### ISSUE THREAD

**Issue by eoeintu** [deezer/spleeter#167]
Hi,

I installed python, pip and splitter on windows 7. Everything sounded to work fine with the different steps to do, but when I test spleeter with a track, I received this mistake. Here is a screenshot,

does anyone has an idea of where it could come from ?

here what I wrote first : spleeter separate -i "mytrack.mp3" spleeter:2stems -o splits
the last line below my screenshot is : spleeter:2stems protocole not found

![image](https://user-images.githubusercontent.com/58628824/70374940-ba9c8f80-18f8-11ea-9bc7-23cb190731ee.png)

thanks in advance,
eo

**Comment by HaxtorMoogle** [comment]
I have the same problem see https://github.com/deezer/spleeter/issues/164

**Comment by eoeintu** [comment]
Hi Haxtor, I find a half solution by avoiding to write spleeter2stems.
So then the line is :

spleeter separate -i "trak.mp3" -o splits

tell me if it works for you (with this way you can only have 2 stems files : voice and accompaniement, for the 4 stems separation, I still don't have solutions)

**Comment by instrumusics** [comment]
I've found a fix! C:
You can try this:
python -m spleeter separate -i 'BOMB.mp3' -p spleeter:2stems -o output

**Comment by aprizm** [comment]
I have tried your method of omitting the mode and it works. Is it a memory problem maybe ?

**Comment by mmoussallam** [comment]
Hi there,

It seems you forgot to add the `-p` before the `spleeter:2stems` so FFprobe thinks it's a file name and does not understand it.

the complete command should look like: `spleeter separate -i '<your/file.mp3>' -p spleeter:2stems -o output`

**Comment by EliGe15532** [comment]
> Hi there,
> 
> It seems you forgot to add the before the so FFprobe thinks it's a file name and does not understand it.`-p``spleeter:2stems`
> 
> the complete command should look like: `spleeter separate -i '<your/file.mp3>' -p spleeter:2stems -o output`

But when run "spleeter separate -i '<your/file.mp3>' -p spleeter:2stems -o output" as you said,it came that:
Usage: spleeter separate [OPTIONS] FILES...
Try 'spleeter separate --help' for help.

Error: Missing argument 'FILES...'.


and when run "spleeter separate -p spleeter:2stems your/file.mp3 -o output",it came that:
ERROR:spleeter:No embedded configuration 2tems found


By the way, when run "spleeter separate spleeter:2stems your/file.mp3 -o output",it came that:
ERROR:spleeter:An error occurs with ffprobe (see ffprobe output below)

ffprobe version 6.0-essentials_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
spleeter:2tems: Protocol not found


Like:
![image](https://github.com/deezer/spleeter/assets/148624723/f18c1b7f-0f4b-4a9a-920a-aa7081450851)
Could you help me to deal with it?
