### ISSUE TITLE
[Discussion] I tried this mp3，and always be failed

### ISSUE THREAD

**Issue by eminfan** [deezer/spleeter#173]
[flower road.zip](https://github.com/deezer/spleeter/files/3940275/flower.road.zip)
pls unzip it and get a mp3. I do not know why this song can not be done. Pls help me.

**Comment by eminfan** [comment]
my memory is only 8G，is it too small for the 6.8M song?

**Comment by mmutee** [comment]
Hello

I used the online version of Spleeter (splitter.ai) to process it. The processed vocals.wav is mindblowing, it beautifully separated male/female vocals, speech part and the complete choir section. So what do you mean when you say it fails?

My installation of Spleeter on my machine fails (crashes) if my song is too long, so I split files into smaller chunks to process them.

**Comment by eminfan** [comment]
> Hello
> 
> I used the online version of Spleeter (splitter.ai) to process it. The processed vocals.wav is ..........

Thank you！The spleeter software is aowsome. The problem is the momery of my computer is only 8G, and it's too small. When I changed to 32G, then it works well.
