### ISSUE TITLE
I want to make it a full band. What should I do next

### ISSUE THREAD

**Issue by tbwhsb88** [deezer/spleeter#177]

**Comment by VIRGINKLM** [comment]
Indeed it's not much of a use if it's not full band.

**Comment by tbwhsb88** [comment]
所以，我希望你能告诉我，在哪里可以使它成为一个完整的乐队！


或就该走的方向提供一些建议！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"VIRGINKLM"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 上午7:51
收件人:&nbsp;"deezer/spleeter"<spleeter@noreply.github.com&gt;;
抄送： &nbsp;“✎₯㎕James_Bobo” <595284940@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题： &nbsp;回复：[deezer / spleeter]我想组成一支完整的乐队。我下一步该怎么做（＃177）




的确，如果不是全波段的话，这没什么用。
  
—
You are receiving this because you authored the thread.
直接发送回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by mmutee** [comment]
Hi. Do you mean full audio bandwidth?

**Comment by tbwhsb88** [comment]
yeah,I hope it's audio bandwidth is complete, if you have ever been to pytorch version of the separation, do you think it goes with spleeter difference in what place?
https://github.com/sigsep/open-unmix-pytorch




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mmutee"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 凌晨0:24
收件人: "deezer/spleeter"<spleeter@noreply.github.com&gt;; 
抄送: "&amp;#x270E;&amp;#x20AF;&amp;#x3395;James_Bobo"<595284940@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [deezer/spleeter] I want to make it a full band. What should I do next (#177)




你好 您是指完整的音频带宽吗？
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by mmutee** [comment]
I wasn't aware of Open Unmix project, thanks for that. If you search around, you will find this question has been asked before. Here is the FAQ entry for this query:

[](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-)

Here is a detailed discussion of the issue. #2 

What I understand is that Spleeter is not learning from frequencies above 11khz, hence that section is discarded, but there are workarounds that will disable this automatic cutoff, mentioned in FAQ and the thread mentioned.

Also if you want to test, I saw the splitter.ai version of Spleeter has the option to enable/disable 11khz cutoff.

**Comment by romi1502** [comment]
We've just updated the [FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-) to provide a new way of performing separation above 11kHz. Also configs that perform separation up to 16kHz were packaged in spleeter as mentioned in the [wiki](https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-models-up-to-16khz)
