### ISSUE TITLE
[Discussion] Confused. Using GPU

### ISSUE THREAD

**Issue by aidv** [deezer/spleeter#182]
I had it working for a while and now it doesn't anymore.

Does anyone have exact instructions on how to make Spleeter use the GPU rather than the CPU?

**Comment by alexku44** [comment]
also interested in this question

**Comment by alexku44** [comment]
> I had it working for a while and now it doesn't anymore.
> 
> Does anyone have exact instructions on how to make Spleeter use the GPU rather than the CPU?

GPU work !!!  cudatoolkit 10.0.130 cudnn 7.3.1

**Comment by aidv** [comment]
@alexku44 Please leave instructions so that more people can get it to work.

**Comment by alexku44** [comment]
> @alexku44 Please leave instructions so that more people can get it to work.
I don’t speak English, I can’t describe everything clearly. upload video
[https://www.youtube.com/watch?v=AptFt3oRH8A](url)

**Comment by mmoussallam** [comment]
Hi @aidv  did you manage to have it work ?

**Comment by aidv** [comment]
@mmoussallam yes sir but it's quite confusing still because I had to try different things and I don't know exactly what I did to get it to work.

Currently this is my step-by-step instruction:

Save the following data to a `.txt` file:
```
tensorflow-gpu==1.14.0
pandas==0.25.1
requests
pip
museval==0.3.0
musdb==0.3.1
norbert==0.2.1
spleeter
ffmpeg-python
```

### Instructions
1. Uninstall any CUDA drivers except of 10.0
2. Install CUDA 10.0 if not installed
3. Install Anaconda
4. Remove all spleeter related files in `c:\users\username\anaconda\pkgs\` and `C:\users\username\anaconda\Lib\site-packages`
5. Open Anaconda shell
6. Remove Conda environments using the following commands:
```conda remove spleeter
conda remove spleeter-cpu
conda remove spleeter-gpu
conda remove --name spleeter --all
conda remove --name spleeter-cpu --all
conda remove --name spleeter-gpu --all
```

7. Remove git clone of spleeter in your project folder, wherever you've put it
8. Run `conda install -c conda-forge spleeter-gpu`
9. Run `pip install -r config.txt`
10. Verify by running `spleeter separate -i "input.mp3" -p spleeter:5stems -o "output"`



This is the best I have so far.

**Comment by xielangtc** [comment]
> @mmoussallam yes sir but it's quite confusing still because I had to try different things and I don't know exactly what I did to get it to work.
> 
> Currently this is my step-by-step instruction:
> 
> Save the following data to a `.txt` file:
> 
> ```
> tensorflow-gpu==1.14.0
> pandas==0.25.1
> requests
> pip
> museval==0.3.0
> musdb==0.3.1
> norbert==0.2.1
> spleeter
> ffmpeg-python
> ```
> 
> ### Instructions
> 1. Uninstall any CUDA drivers except of 10.0
> 2. Install CUDA 10.0 if not installed
> 3. Install Anaconda
> 4. Remove all spleeter related files in `c:\users\username\anaconda\pkgs\` and `C:\users\username\anaconda\Lib\site-packages`
> 5. Open Anaconda shell
> 6. Remove Conda environments using the following commands:
> 
> ```
> conda remove spleeter-cpu
> conda remove spleeter-gpu
> conda remove --name spleeter --all
> conda remove --name spleeter-cpu --all
> conda remove --name spleeter-gpu --all
> ```
> 
> 1. Remove git clone of spleeter in your project folder, wherever you've put it
> 2. Run `conda install -c conda-forge spleeter-gpu`
> 3. Run `pip install -r config.txt`
> 4. Verify by running `spleeter separate -i "input.mp3" -p spleeter:5stems -o "output"`
> 
> This is the best I have so far.

conda can auto-install the dependency pkg during the installing spleeter. why still need to run the  command "pip install -r config.txt"

**Comment by arretxe** [comment]
how do I install cudatoolkit 10.0.130 cudnn 7.3.1?
