### ISSUE TITLE
[Discussion] Fatal Error?!

### ISSUE THREAD

**Issue by Caserol23** [deezer/spleeter#184]
`(base) C:\Users\JSHOP-V2\Downloads\Compressed\spleeter>spleeter separate -i sple
eter/tonio.mp3 -p spleeter:5stems -o output
Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_157477
5894867\_h_env\python.exe"  "C:\ProgramData\Anaconda3\Scripts\spleeter.exe" sepa
rate -i spleeter/tonio.mp3 -p spleeter:5stems -o output'

(base) C:\Users\JSHOP-V2\Downloads\Compressed\spleeter>spleeter separate -i sple
eter/tonio.mp3 -p spleeter:5stems -o output
Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_157477
5894867\_h_env\python.exe"  "C:\ProgramData\Anaconda3\Scripts\spleeter.exe" sepa
rate -i spleeter/tonio.mp3 -p spleeter:5stems -o output'

(base) C:\Users\JSHOP-V2\Downloads\Compressed\spleeter>spleeter separate -i sple
eter/tonio.mp3 -p spleeter:4stems -o output
Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_157477
5894867\_h_env\python.exe"  "C:\ProgramData\Anaconda3\Scripts\spleeter.exe" sepa
rate -i spleeter/tonio.mp3 -p spleeter:4stems -o output'

(base) C:\Users\JSHOP-V2\Downloads\Compressed\spleeter>spleeter separate -i sple
eter/tonio.mp3 -p spleeter:4stems -o output
Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_157477
5894867\_h_env\python.exe"  "C:\ProgramData\Anaconda3\Scripts\spleeter.exe" sepa
rate -i spleeter/tonio.mp3 -p spleeter:4stems -o output'

(base) C:\Users\JSHOP-V2\Downloads\Compressed\spleeter>conda activate spleeter-c
pu
Could not find conda environment: spleeter-cpu
You can list all discoverable environments with `conda info --envs`.

(base) C:\Users\JSHOP-V2\Downloads\Compressed\spleeter>conda install -c conda-fo
rge spleeter
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(base) C:\Users\JSHOP-V2\Downloads\Compressed\spleeter>spleeter separate -i sple
eter/audio_example.mp3 -p spleeter:2stems -o output
Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_157477
5894867\_h_env\python.exe"  "C:\ProgramData\Anaconda3\Scripts\spleeter.exe" sepa
rate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output'`

![Untitled](https://user-images.githubusercontent.com/16409238/70866626-d55bad80-1f63-11ea-875b-43a632a9f19e.png)

I use and followed through instructions...
Anaconda Throws me Fatal Error within Launcher...

Specs:

Video Card: GTX-2080T
CPU: Core 2 Duo (Quad-core)
8GB RAM

**Comment by mmoussallam** [comment]
Similar to https://github.com/deezer/spleeter/issues/154 try the command `python -m spleeter separate instead of `spleeter separate`
