### ISSUE TITLE
[Bug] Neither installation method does not work 

### ISSUE THREAD

**Issue by port22** [deezer/spleeter#185]
Using Anaconda Distribution, after `conda install` it tries to search python on `d:\` although it's the DVD drive:
```
Fatal error in launcher: Unable to create process using '"d:\bld\spleeter_1574775894867_h_env\python.exe"
```

Uninstalled Anaconda, installed python 3.8.0 and tried to install via pip:
```
> pip install spleeter
ERROR: Could not find a version that satisfies the requirement spleeter (from versions: none)
ERROR: No matching distribution found for spleeter
```

Reproduce it via docker:
```docker run -it --rm python bash -c 'pip install spleeter'```

Also: there is no Docker Image like `deezer/spleeter` on Dockerhub:

```
root@58a0a4365a3f:/# docker pull deezer/spleeter
Using default tag: latest
Error response from daemon: pull access denied for deezer/spleeter, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by mmoussallam** [comment]
Similar to https://github.com/deezer/spleeter/issues/154 closing it to avoid doubles
