### ISSUE TITLE
[Discussion] your question: confuse about GPU when Itry to train the model .

### ISSUE THREAD

**Issue by DaerTaeKook** [deezer/spleeter#187]
the command is :CUDA_VISIBLE_DEVICES='1' python __main__.py train -p /home/tae/spleeter_master/configs/4stems/base_config.json -d /home/tae/musdb18hq ,  using the tensorflow-gpu,But the utilization ratio is zero.How can I use the GPU to train my own model through the __main()__?

**Comment by mmoussallam** [comment]
Hi, please use the issue template with all your setup info so that we can help
