### ISSUE TITLE
[Discussion] Questions regarding pre-trained models

### ISSUE THREAD

**Issue by NickAcPT** [deezer/spleeter#190]
So, first of all, thanks for releasing this!
This is a super amazing project that I hope to see improve in the future.

I'm opening this issue because I read that newer pre-trained models were gonna be released soon, and I was wondering if it'll happen in the near future or if this is gonna be kept like this. Seeing that only one commit has been done (to the README file) over in 23 days, I was wondering if this is gonna be worked on in the future.

Again, thanks a lot for the effort you've all put into this amazing project.

**Comment by mmoussallam** [comment]
Hi @NickAcPT 

Thanks for your message.We've just released new models allowing higher frequencies to be generated (in version 1.4.9) but we cannot guarantee that newer models will be released on a regular basis.
