### ISSUE TITLE
[Feature] Use shared memory from the GPU

### ISSUE THREAD

**Issue by NickAcPT** [deezer/spleeter#191]
## Description
Since I'm using a laptop, my GPU (GTX 1050) has both dedicated memory (4 GB) and shared memory (it depends on the system's RAM).

The idea behind this request is that sometimes I get an OOM because it only has 4 GB of ram that get used.
Thus, it would be awesome to have spleeter use the whole RAM that's available.
![Image with an example of available memory of a GPU](https://i.imgur.com/xnWu6FM.png)

**Comment by aidv** [comment]
I think, but not sure, that that's out of devs control.
I assume it has to be a Tensorflow thing rather than a Spleeter thing.

**Comment by aidv** [comment]
Maybe @mmoussallam can confirm?  :)
