### ISSUE TITLE
[Discussion] Separation of live audio from microphone

### ISSUE THREAD

**Issue by Rahul-Sindhu** [deezer/spleeter#194]
Hi,
I'd like to separate audio coming from the microphone, how do you suggest I should proceed. Is it possible? I'm currently creating small duration files and using them, but it doesn't seem like a clean approach.

**Comment by markus-wa** [comment]
Have you found a 'clean' solution for this?

**Comment by jsacrist** [comment]
I do not think this is possible at the moment.  The extended-abstract paper they published on ISMIR 2019 has a footnote at the end of the very first page that says:
    
> [...] the model cannot be applied in real-time as it needs buffering

http://archives.ismir.net/ismir2019/latebreaking/000036.pdf

**Comment by markus-wa** [comment]
Thanks for the clarification @jsacrist 🙂

**Comment by varenc** [comment]
this issue appears prominently in Google searches, so if you found this first like I did...

Check out [vstSpleeter](https://github.com/gvne/vstSpleeter) where despite the challenges @gvne implemented a real time VST interface to Spleeter! Also I've found @diracdeltas's [popular fork](https://github.com/diracdeltas/vstSpleeter) of it helpful, particularly for the macOS build instructions.

more discussion and details on gvne's implementation in #276
