### ISSUE TITLE
[Bug] Training with Custom dataset

### ISSUE THREAD

**Issue by TaegyunKwon** [deezer/spleeter#196]
## Description

I'm trying to train a model with custom dataset (Subset of SLAKH). Audio files are consists of flac files with 16k sample rates. But seems it's not working properly.
Following the instructions, I created csv files and config json file, and started training with following command
$spleeter train -p configs/my_config.json -d {my_dataset_location}

When I run it, GRAM of GPU 0 is occupied but GPU utilization is zero (rarely shows low utilization ~4% for a second). It does not shows any other message (include Tensorboard log), so I suspect training process is extremely slow, or it's not working properly.
I tried with small dataset(10 files) as well, but got same result.

I tried this in Ubuntu 16.04, and tried both build from source with device_target='gpu' (tensorflow==1.14.0),
and conda spleeter-gpu version.

Have anyone trained spleeter with custom dataset?
And is this code still works with sr=16000?

```
my_config.json
{
    "train_csv": "configs/train.csv",
    "validation_csv": "configs/validation.csv",
    "model_dir": "{my_model_dir}",
    "mix_name": "mix",
    "instrument_list": ["piano", "guitar", "bass", "drums", "strings"],
    "sample_rate":16000,
    "frame_length":4096,
    "frame_step":1024,
    "T":512,
    "F":1024,
    "n_channels":1,
    "n_chunks_per_song":4,
    "separation_exponent":2,
    "mask_extension":"zeros",
    "learning_rate": 1e-4,
    "batch_size":32,
    "training_cache":"cache/training",
    "validation_cache":"cache/validation",
    "train_max_steps": 100000,
    "throttle_secs":600,
    "random_seed":3,
    "save_checkpoints_steps":1,
    "save_summary_steps":5,
    "model":{
        "type":"unet.unet",
        "params":{
               "conv_activation":"ELU",
               "deconv_activation":"ELU"
        }
    }
}
```
## Step to reproduce

1. Installed using `conda install -c conda-forge spleeter-gpu`
2. create train / validation csv and config.json
2. Run as `train -p configs/config.json -d {dataset_location}`
3. after several "INFO:spleeter:Audio data loaded successfully" messages, not thing changes.

## Output

```
$spleeter train -p configs/my_config.json -d CUSTOM_DATASET_PATH
INFO:spleeter:Start model training
INFO:spleeter:Loading audio b'/home/svcapp/userdata/musicai/slakh2100_flac//train/Track00008/strings/strings.flac' from 159.5815833333333 to 179.5815833333333
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Loading audio b'/home/svcapp/userdata/musicai/slakh2100_flac//train/Track00003/strings/strings.flac' from 0.5 to 20.5
...
INFO:spleeter:Audio data loaded successfully
```
and nothing happens for few hours (for ~12 hours)

## Environment

|                               |                                  |
| -----------------| ------------------------------- |
| OS                         | Ubuntu 16.04
| Installation type  | Conda , source  |
| RAM available     |  256GB                |
| Hardware spec   | GPU:  TITAN Xp |

**Comment by aidv** [comment]
I'm having the same issue, only I haven't let it run for 12 hours.
Documentation clearly states that with GPU, training could be up to 100x faster than realtime.

**Comment by divideconcept** [comment]
> I'm having the same issue, only I haven't let it run for 12 hours.
> Documentation clearly states that with GPU, training could be up to 100x faster than realtime.

The doc never said that training was 100x faster than realtime, it says that about the separation process (when your training is already done).

**Comment by aidv** [comment]
Aaah yes you're correct. It is in fact for separation only.

**Comment by pmamieva** [comment]
Hello. I see you are using ""sample_rate":16000," while SLAKH sample rate is 44100 Hz. If you intend your model to separate up to and including 16 kHz, i think you should change the ""F":1024," line to ""F":1536,". Best.

**Comment by stickyninja3** [comment]
Hi divideconcept, did you ever solve this problem and get the training working?

I am having the same issue using Windows 10.

**Comment by Juan-Carlos-Rodero-Sales-Bose** [comment]
I've had a similar issue when using a 16k sampling rate for training, it loads all the data and just hangs.

**Comment by vegertar** [comment]
Same issue too, with 44100 sample rate, all data loaded, and CPU is busy hanging on 150%, but no file modifications after model folder created
