### ISSUE TITLE
Error when freezing model

### ISSUE THREAD

**Issue by waqas117** [deezer/spleeter#198]
## Description
 gives error when I'm trying to freez model 

## Step to reproduce

1. checked using `tensorflow 1.14` and `tensorflow 1.15`
2. using output_node_names as `output_node_names = "save_1/restore_all"`
3. Got `Input 0 of node import/save_1/AssignVariableOp was passed float from import/batch_normalization/beta:0 incompatible with expected resource.` error

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS             |  MacOS  
| Installation type | pip

**Comment by mmoussallam** [comment]
Hi @waqas117 

Closing this but you may want to check #155
