### ISSUE TITLE
error trying to run separation

### ISSUE THREAD

**Issue by yamtssfa** [deezer/spleeter#20]
BUG
running this command is not successful in creating the output files & gives messages
spleeter separate -i audio_example.mp3 -o audio_output

produces mutiple messages similar to the following:
c:\users\bryan\.conda\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])

## Your Setup
windows 10 64

In particular:
miniconda

**Comment by Faylixe** [comment]
Please check [FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-do-i-have-some-stems-not-written-to-disk-)

**Comment by yamtssfa** [comment]
I read the faq and tried to run with a duration of 1 ( -d 1) second but still have same issue.  Didnt mean to originally call it a bug , is probably something to do with my installation. I dont know much about git or python.
I have an i7 processor and 12 gb ram.
I really excited to try this so any help is much appreciated!
