### ISSUE TITLE
.bat file will not run for the 11khz filter off 

### ISSUE THREAD

**Issue by Mixerrog** [deezer/spleeter#201]
I  edited all the Stems files under the  configs file edited to "mask_extension":"average" & can get the 11khz filter turned off when manually running the file but when trying to make a drag & drop over a .bat shortcut, I always get the stems with the 11khz filter on.  How can this be fixed please? 

I get the error -- Configuration file spleeter/configs/4stems/base_config11.json  not found even though I created a file (base_config11.json with "mask_extension":"average") with that name & instructions in the same place as the original "base_config.json". I even tried editing the original "base_config.json" with "mask_extension":"average" but when I run it from a ,bat, it always runs with the 11khz filter on.

Thanks, Roger

**Comment by Mixerrog** [comment]
I was able to fix the issue.

**Comment by bespokecomponents** [comment]
Hi, how did you fix this please. I would really like to know how to get unfiltered tracks. Thanks!

**Comment by bespokecomponents** [comment]
> I was able to fix the issue.


Hi, how did you fix this please. I would really like to know how to get unfiltered tracks. Thanks!
