### ISSUE TITLE
[Discussion] What are the recommended CPU and memory？

### ISSUE THREAD

**Issue by yoorxee** [deezer/spleeter#202]
What are the recommended CPU and memory？

Conventional processing music files， Example：filename-》MP3，7bm

**Comment by kiratdeluxe** [comment]
for 2stems, 8gb and for 4 and 5 more i don't know exactly . i have to buy more now to be safe i have bought 32gb.

**Comment by mmoussallam** [comment]
Closing this issue for now.

For the record, it's very hard to predict how much computing and memory resources are needed, depending on your system, and the installation method it will have a rather large impact.

In the latests version (1.5) we implement a different backend to load the audio, which often results in a much reduced memory footprint.
