### ISSUE TITLE
[Bug] spleeter on docker usnig nvidia gpu return error

### ISSUE THREAD

**Issue by kiratdeluxe** [deezer/spleeter#204]
## Description
i run spleeter on a docker container, when i exec nvidia-docker run -v $(pwd)/output:/output researchdeezer/spleeter:gpu 

i have an error .
as i can't get into the container with bash login to see what happen, i'm stuck

## Step to reproduce

1. after installing :
ii  nvidia-driver-440                                 440.33.01-0ubuntu1                     amd64        NVIDIA driver metapackage
ii  cuda                                              10.2.89-1                              amd64        CUDA meta-package
ii  cuda-10-2                                         10.2.89-1                              amd64        CUDA 10.2 meta-package
ii  nvidia-docker2                                    2.2.2-1                                all          nvidia-docker CLI wrapper
ii  docker-ce                                         5:19.03.3~3-0~ubuntu-disco             amd64        Docker: the open-source application container engine
ii  docker-ce-cli                                     5:19.03.3~3-0~ubuntu-disco             amd64        Docker CLI: the open-source application container engine

and download container :
researchdeezer/spleeter
researchdeezer/spleeter:gpu

2. i run 
sudo docker run -v $(pwd)/output:/output researchdeezer/spleeter separate -i audio_example.mp3 -o /output
everything is fine i have my 2 audio file but when i exec this two :

sudo nvidia-docker run -v $(pwd)/output:/output researchdeezer/spleeter:gpu separate -i audio_example.mp3 -o /output
or 
sudo docker run --runtime=nvidia -v $(pwd)/output:/output researchdeezer/spleeter:gpu separate -i audio_example.mp3 -o /output

3. Got `...` error
i have the following error :
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"spleeter\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled
## Output
the normal out would be this :

INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:spleeter:Validating archive checksum
INFO:spleeter:Extracting downloaded 2stems archive
INFO:spleeter:2stems model file(s) extracted
INFO:spleeter:File /output/('audio_example', '.mp3')/accompaniment.wav written
INFO:spleeter:File /output/('audio_example', '.mp3')/vocals.wav written

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
|  OS |  Ubuntu Linux 19.10 |
| Installation type | docker        |
| RAM available     | 8Go                             |
| Hardware spec     | nvidia gtx 760 / intel i5 -4690 CPU @ 3.50GHz/ ssd |

## Additional context

none

**Comment by 4matic** [comment]
I have the same error.

| |  |
--- | ---
OS | Ubuntu Linux 16.04
Installation type | docker
RAM available | 32GB
Hardware spec | nvidia gtx 770 / intel i7-4770S CPU @ 3.10GHz / ssd

**Comment by kiratdeluxe** [comment]
Hello everybody after some searching, i have activated the --verbose option like this :

nvidia-docker run -v $AUDIO_OUT:/output -v $AUDIO_IN:/input -v $MODEL_DIRECTORY:/model -e MODEL_PATH=/model researchdeezer/spleeter separate -p spleeter:4stems --verbose -i /input/the_organ_brother.mp3 -o /output

and i could finally see something interesting in the log :
2020-02-11 07:04:08.024697: W tensorflow/core/framework/allocator.cc:107] Allocation of 681443328 exceeds 10% of system memory.
as i watch my memory, i could see my memory dropping under 144Mb and the spleeter stop shortly after.

so it seems for 2stems, spleeter work well under 8gb but for 4 and 5 stems i need more.

pay attention to the syntaxe. the place of the -p is important.

**Comment by kiratdeluxe** [comment]
Hello everybody after some searching, i have activated the --verbose option like this :

nvidia-docker run -v $AUDIO_OUT:/output -v $AUDIO_IN:/input -v $MODEL_DIRECTORY:/model -e MODEL_PATH=/model researchdeezer/spleeter separate -p spleeter:4stems --verbose -i /input/the_organ_brother.mp3 -o /output

and i could finally see something interesting in the log :
2020-02-11 07:04:08.024697: W tensorflow/core/framework/allocator.cc:107] Allocation of 681443328 exceeds 10% of system memory.
as i watch my memory, i could see my memory dropping under 144Mb and the spleeter stop shortly after.

so it seems for 2stems, spleeter work well under 8gb but for 4 and 5 stems i need more.

pay attention to the syntaxe. the place of the -p is important.

**Comment by avindra** [comment]
Hey @kiratdeluxe it seems you didn't resolve the problem with the`gpu` image. As far as I can tell, your new command changed the base image to `researchdeezer/spleeter:latest` which is not the GPU based image that is throwing the following error:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"spleeter\": executable file not found in $PATH": unknown.
```

I'm able to get into the container if I override the entrypoint:

```bash
$ docker run --runtime=nvidia --rm  -ti --entrypoint /bin/bash -v $(pwd)/output:/output researchdeezer/spleeter:gpu

(base) root@ef578d221773:/output#
```

Then from there, I'm able to run `spleeter` (taken directly from actual use case)

```
(base) root@ef578d221773:/output# spleeter separate -i arewe.mp3 -o output/    
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:spleeter:Validating archive checksum
INFO:spleeter:Extracting downloaded 2stems archive
INFO:spleeter:2stems model file(s) extracted
INFO:spleeter:File output/arewe/accompaniment.wav written
INFO:spleeter:File output/arewe/vocals.wav written
```
