### ISSUE TITLE
[Bug] Output folder name ending with a dot

### ISSUE THREAD

**Issue by Christilut** [deezer/spleeter#207]
## Description

The output folder name gets changed by Windows if the filename (before the extension) ends with a dot.

For example, if the input filename is `F.O.O..mp3` (notice 2 dots) then Spleeter will create a folder named `F.O.O`

## Step to reproduce

1. Installed using `conda`

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows  |
| Installation type | Conda|

**Comment by mmoussallam** [comment]
HI @Christilut 

Indeed, that's the normal Windows behavior. I'm afraid there's not much we can do here to change that.
