### ISSUE TITLE
[Discussion] I wanna convert checkpoint to .pb file

### ISSUE THREAD

**Issue by kno3a87** [deezer/spleeter#209]
Hi,
I wanna convert checkpoint to .pb file.
I checked "[Discussion] Using Spleeter pretrained tensorflow models directly #155", but I cannot understand...

>You can use the following snippet to create the event file. model_file is something like 2stems/model.data-00000-of-00001, and log_dir is the directory where to write the event file.
```
with session.Session(graph=ops.Graph()) as sess:
    with gfile.FastGFile(model_file, "rb") as f:
      graph_def = graph_pb2.GraphDef()
      graph_def.ParseFromString(f.read())
      importer.import_graph_def(graph_def)

    pb_visual_writer = summary.FileWriter(log_dir)
    pb_visual_writer.add_graph(sess.graph) 
```

Where is the graph_pb2?

please reply me🙇🏻‍♀️

**Comment by kno3a87** [comment]
In the first place, where are you saving in checkpoint format?

**Comment by atharvashirude** [comment]
Did you find any solution?
