### ISSUE TITLE
Example script doesn't seem to be working.

### ISSUE THREAD

**Issue by crobertsbmw** [deezer/spleeter#21]
I'm just following the instructions found in the README, and I was able to successfully run the scripts, and I get two output files, vocals.wav and accompaniment.wav, but both the files sound exactly the same as the original. I am not hearing any difference between the three.

This is exactly what I ran:
```
git clone https://github.com/Deezer/spleeter
conda env create -f spleeter/conda/spleeter-cpu.yaml
conda activate spleeter-cpu
spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output
```
On the last line I get a bunch of Tensorflow warnings.
```
INFO:tensorflow:Using config: {'_model_dir': 'pretrained_models/2stems', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.7
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x13a157eb8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Could not find trained model in model_dir: pretrained_models/2stems, running initialization to predict.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From /anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/model/functions/unet.py:29: The name tf.keras.initializers.he_uniform is deprecated. Please use tf.compat.v1.keras.initializers.he_uniform instead.

INFO:tensorflow:Apply unet for vocals_spectrogram
INFO:tensorflow:Apply unet for accompaniment_spectrogram
INFO:tensorflow:Done calling model_fn.
WARNING:tensorflow:From /anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.int32
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string
INFO:tensorflow:Loading audio b'spleeter/audio_example.mp3' from 0.0 to 600.0
INFO:tensorflow:File output/audio_example/vocals.wav written
INFO:tensorflow:File output/audio_example/accompaniment.wav written
```
I'm running on a mac with Conda.

**Comment by Faylixe** [comment]
Log indicates that some error occurs while looking for model. Those models are downloaded from Github automatically when not found. Sound like a lack of error handling here when downloading such model, did you retry since ?

**Comment by ivymarco** [comment]
I have the same issue that got 2 same track as original one. both GPU/CPU mode tried.GPU is NVidia 1060. And tried CPU mode on other computer(as no NVidia GPU), same issue. Suppose all components would be downloaded automatic, any step might be missing? 

I downloaded \ installed GIT \ ANACONDA and ran below commands.

git clone https://github.com/Deezer/spleeter
conda env create -f spleeter/conda/spleeter-cpu.yaml
conda activate spleeter-cpu
spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output

Got same as above error

INFO:tensorflow:Could not find trained model in model_dir: pretrained_models/2stems, running initialization to predict.
INFO:tensorflow:Calling model_fn.

Also asked my friend to try on other location, same result.
![spleeter](https://user-images.githubusercontent.com/57347781/68177956-063fde80-ffc5-11e9-8ca6-35b2c70d5dda.JPG)

Any thing we could do?

**Comment by ivymarco** [comment]
> I'm just following the instructions found in the README, and I was able to successfully run the scripts, and I get two output files, vocals.wav and accompaniment.wav, but both the files sound exactly the same as the original. I am not hearing any difference between the three.
> 
> This is exactly what I ran:
> 
> ```
> git clone https://github.com/Deezer/spleeter
> conda env create -f spleeter/conda/spleeter-cpu.yaml
> conda activate spleeter-cpu
> spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output
> ```
> 
> On the last line I get a bunch of Tensorflow warnings.
> 
> ```
> INFO:tensorflow:Using config: {'_model_dir': 'pretrained_models/2stems', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': gpu_options {
>   per_process_gpu_memory_fraction: 0.7
> }
> , '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x13a157eb8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
> INFO:tensorflow:Could not find trained model in model_dir: pretrained_models/2stems, running initialization to predict.
> INFO:tensorflow:Calling model_fn.
> WARNING:tensorflow:From /anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/model/functions/unet.py:29: The name tf.keras.initializers.he_uniform is deprecated. Please use tf.compat.v1.keras.initializers.he_uniform instead.
> 
> INFO:tensorflow:Apply unet for vocals_spectrogram
> INFO:tensorflow:Apply unet for accompaniment_spectrogram
> INFO:tensorflow:Done calling model_fn.
> WARNING:tensorflow:From /anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.where in 2.0, which has the same broadcast rule as np.where
> INFO:tensorflow:Graph was finalized.
> INFO:tensorflow:Running local_init_op.
> INFO:tensorflow:Done running local_init_op.
> WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string
> WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.int32
> WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string
> INFO:tensorflow:Loading audio b'spleeter/audio_example.mp3' from 0.0 to 600.0
> INFO:tensorflow:File output/audio_example/vocals.wav written
> INFO:tensorflow:File output/audio_example/accompaniment.wav written
> ```
> 
> I'm running on a mac with Conda.

Hi Robbert, I fixed the problem by manually downloaded the trained module for 2istems with below URL link

https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz

Just put it to C:\Users\username\pretrained_models\2stems

Then run the script again, you cld find 2 tracks with different layout.

Nice day.

Alan
