### ISSUE TITLE
[Discussion] How can I convert model to CoreML?

### ISSUE THREAD

**Issue by kno3a87** [deezer/spleeter#210]
I wanna make CoreML.
I make .pb file from checkpoint, but I don't understand converting CoreML.
Please teach me🙇🏻‍♀️

**Comment by xk7155148** [comment]
> I wanna make CoreML.
> I make .pb file from checkpoint, but I don't understand converting CoreML.
> Please teach me🙇🏻‍♀️
https://github.com/tf-coreml/tf-coreml
これを使うと、多分出来る

**Comment by kno3a87** [comment]
I saw the _Tensorflow conversion section in the Neural network guide_ and tried _TensorFlow 1 converter_ from this website, but I can't...
```
import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = 'Protobufs/Binary_Protobuf.pb',
                     mlmodel_path = 'separate_model.mlmodel',
                     output_feature_names = ['softmax:0'],
                     input_name_shape_dict = {'conv_n_filters' : [16, 32, 64, 128, 256, 512]},
                     minimum_ios_deployment_target='12')    

```
I don't know what to write "output_feature_names", "input_name_shape_dict" and "minimum_ios_deployment_target", so I wrote somehow...
First of all, the way to make .pb file may be different...😭

**Comment by xk7155148** [comment]
I try to make coreml library under Windows.
Because I don't have a linux or OSX environment.😭
I can try to solve this problem, but it take some time.

**Comment by kno3a87** [comment]
Thank you for your doing!!
Please let me know if it takes time...!

**Comment by mmoussallam** [comment]
Hi there

It's not something that we have tried so far but you can have a look at the conversation in #155 to get inspiration.

Good luck

**Comment by kno3a87** [comment]
I saw it, but I cannot...

>I saw the Tensorflow conversion section in the Neural network guide and tried TensorFlow 1 converter from this website, but I can't...
>```
>import tfcoreml as tf_converter
>tf_converter.convert(tf_model_path = 'Protobufs/Binary_Protobuf.pb',
>                     mlmodel_path = 'separate_model.mlmodel',
>                     output_feature_names = ['softmax:0'],
>                     input_name_shape_dict = {'conv_n_filters' : [16, 32, 64, 128, 256, 512]},
>                     minimum_ios_deployment_target='12')    
>```
>I don't know what to write "output_feature_names", "input_name_shape_dict" and "minimum_ios_deployment_target", so I wrote somehow...
>First of all, the way to make .pb file may be different...😭

**Comment by Turing311** [comment]
I've found a way to use pretrained models in Android / iOS APPs.

**Comment by KostyaAtarik** [comment]
@Turing311 and how did you manage to do it?

**Comment by john0322** [comment]
@KostyaAtarik 
https://github.com/FaceOnLive/Spleeter-Android-iOS

**Comment by gigadeplex** [comment]
> @KostyaAtarik https://github.com/FaceOnLive/Spleeter-Android-iOS

data phishing? 🗡️

**Comment by KostyaAtarik** [comment]
I managed to convert it to .mlmodel myself, but it wasn't an easy process

**Comment by sclsj** [comment]
> I managed to convert it to .mlmodel myself, but it wasn't an easy process

How did you do it? I want to use the Neural Engine on m1 for spleeter, and I think the only way to do that is with coreML.

**Comment by fwcd** [comment]
I have managed to convert the non-Fourier transform parts of Spleeter to Core ML. The STFT unfortunately seems to be unsupported, so some external preprocessing would be required.

The script can be found here: https://github.com/fwcd/spleeter-pytorch

**Comment by KostyaAtarik** [comment]
FFT/RFFT/IFFT/IRFFT were introduced in [coremltools 6.2](https://github.com/apple/coremltools/releases/tag/6.2) and Spleeter uses RFFT / IRFFT under the hood. I think it should be possible to convert Spleeter to Core ML completely, but it may require some code changes

**Comment by fwcd** [comment]
That's interesting indeed, but wouldn't the exact same STFT be required to reliably use the pretrained models? Perhaps with some fine-tuning one could get around this

**Comment by fwcd** [comment]
Ah those look pretty promising, thanks! Still a bit painful to do without `Tensor.unfold`, but that seems like a more reasonable problem to tackle...
