### ISSUE TITLE
Installation issues with new spleeter

### ISSUE THREAD

**Issue by MrBasssman65** [deezer/spleeter#213]
Hi everyone.  I hope you can help someone out of their element.  A friend of mine put me onto this and helped me get the original installed.  When trying to update to the new version I get the following errors:
 spleeter :  The term spleeter is not recognized as the name of a cmdlet, function, script file or operable program.
Check the spelling of the name, or if a path was included, verify that the path was correct and try again.
At line:1 char:1
+ spleeter separate -i Gunfighter.wav -p spleeter:4stems -o splits
+ ~~~~~~~~
       + Category Info               : Object Not Found:  (spleeter:String)  [ ], Command Not Found Exception
       + FullyQualifiedErrorID  : CommandNotFoundException
Obviously, I don't know what I am supposed to be looking for or where to find it.  Apparently the new installation went somewhere else and it no longer recognizes commands based from my Spleeter folder in Downloads. I updated conda, re-installed Python 3.7 and removed the old spleeter and installed the new one.  I was using Powershell to launch this.  Hope some one can help fix this or provide me a detailed way to totally uninstall everything and start from scratch.  Thanks.

**Comment by mmoussallam** [comment]
Hi,

Can you try by replacing the `spleeter` command with `python -m spleeter`  please ?

**Comment by MrBasssman65** [comment]
Thanks I tried that.  I was able to find a solution that was posted in issue #137.  The author had problems with tensorflow and the suggestion in an answer was to force reinstall spleeter which worked for me.  You might want to post that suggestion when nothing else works.  The command was:  pip install --force-reinstall spleeter
________________________________

**Comment by mmoussallam** [comment]
Thanks, we'll do!

**Comment by ovrdrvn** [comment]
Tried with python -m and got: No module named spleeter.__main__; 'spleeter' is a package and cannot be directly executed

**Comment by MrBasssman65** [comment]
Thanks for replying.  I have done that.  It works................but with a caveat.  I can't use it when starting from (base).  It only works when (spleetertest) is activated.  Therefore, I now leave it on all the time so that it does not keep attempting to download stems.
________________________________

**Comment by ovrdrvn** [comment]
My installation has anaconda in my user directory and a spleeter directory at the same level. If I cd into the spleeter diretory and run the command with the python call, it finds spleeter but a new error comes:   ModuleNotFoundError: No module named 'tensorflow'
