### ISSUE TITLE
[Discussion] How much time should training take?

### ISSUE THREAD

**Issue by aidv** [deezer/spleeter#215]
I'm training my first model and it's been running for well over 30 minutes.

The dataset consists of 50 audio files at 1 minutes each, and a validation dataset of 5 files at 1 minute each.

So validation dataset is 10% the size of the training data set.

I can see that both the CPU and GPU CUDA is being used in the task manager.

All I'm seeing in the command line is the following:
```
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
```

Is something wrong?

**EDIT:**
I also tried with 10 files for training and 1 file for validation.
I can see the CUDA meter in task manager rise, then fall for a short while, and the rise, and then fall again, over and over again.

I assume something is being processed, but it shouldn't take 2 hours, should it?

**Comment by aidv** [comment]
I reinstalled Spleeter for CPU and this is what the CPU usage looks like for 10 song dataset (1min songs) that has been running for 30 minutes:

<img width="314" alt="cpu" src="https://user-images.githubusercontent.com/5313040/71622072-c156b380-2bd3-11ea-82b6-692b53915799.PNG">

**Comment by aidv** [comment]
Ugh this is so frustrating. Nothing in the documentation either other than `making the separation process very fast (more than 100x realtime)`.

In that case my 1 minute song could be processed up to 100 times faster, e.g 0.6 sec, so 10 songs would take 6 seconds.

Even if CPU is slower than GPU, if it did it in realtime it would take only 10 minutes, but still, well above 1 hour has passed now.

Can absolutely no one in the Spleeter dev team address this concern?

I'm eager to train my own models. I have so many different datasets by now :(

**Comment by aidv** [comment]
Ok so I added the argument `--verbose` and in fact it seems like something is going on.
I get the following output

```
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:Audio data loaded successfully
INFO:tensorflow:loss = 5.335146, step = 1
INFO:tensorflow:global_step/sec: 0.195653
INFO:tensorflow:loss = 4.650765, step = 11 (51.112 sec)
INFO:tensorflow:global_step/sec: 0.19864
INFO:tensorflow:loss = 4.1607137, step = 21 (50.892 sec)
INFO:tensorflow:global_step/sec: 0.189612
INFO:tensorflow:loss = 5.6790705, step = 31 (52.189 sec)
INFO:tensorflow:global_step/sec: 0.199982
INFO:tensorflow:loss = 5.627528, step = 41 (50.426 sec)
```

But question still remains: How long should this take?

**Comment by eerilqin** [comment]
Dude, how can you tell me the detailed steps? I don't know anything about this, but I feel this thing is great, I want to learn, and I don't know where to start. The point is that English is not very good.

**Comment by aidv** [comment]
Training using `spleeter-gpu` stopped working completely.
I went back to `spleeter-cpu` but now it's going to take forever.

**Comment by aidv** [comment]
@eerilqin I'm pretty new too. I suggest just going through the wiki and reading as many issues as possible. And also trial and error.

**Comment by aidv** [comment]
I just realized that the config training file has a key that says `train_max_steps` that is set to `1000000`.

My CPU does aprox 712 steps per hour, so training on my CPU will take ~58 days. YIKES!

**Comment by aidv** [comment]
I solved my question with this script that I made.

The basic formula to estimate training duration is as following:
`(max_steps - elapsed_steps) / steps_per_second`
where
`steps_per_second = elapsed_steps / elapsed_time`
and
`elapsed_time = now_time - start_time`

Or something. I'm too tired after trying to figure this out for too long.

This should be implemented into Spleeter @mmoussallam @Faylixe 

```
var fs       = require('fs')
const spawn_ = require('child_process').spawn
var rimraf   = require("rimraf")

rimraf('cache', ()=>{})
rimraf('unverb', ()=>{})


function secondsToDhms(seconds) {
    seconds = Number(seconds);
    var d = Math.floor(seconds / (3600*24));
    var h = Math.floor(seconds % (3600*24) / 3600);
    var m = Math.floor(seconds % 3600 / 60);
    var s = Math.floor(seconds % 60);
    
    var dDisplay = d > 0 ? d + (d == 1 ? " day, " : " days, ") : "";
    var hDisplay = h > 0 ? h + (h == 1 ? " hour, " : " hours, ") : "";
    var mDisplay = m > 0 ? m + (m == 1 ? " minute, " : " minutes, ") : "";
    var sDisplay = s > 0 ? s + (s == 1 ? " second" : " seconds") : "";
    return dDisplay + hDisplay + mDisplay + sDisplay;
}

var log_path = './log.txt'
function newLog(){
    try { fs.unlinkSync(log_path) } catch(e){ }
    try {
        fs.closeSync(fs.openSync(log_path, 'w'))
        console.log('Log created.')
    } catch(e){
        console.log('FAILED TO CREATE LOG')
        console.log(e)
    }
}
newLog()

function log(msg){
    fs.appendFile(log_path, msg + '\n', function(err) { if(err) { return console.log(err); } });
}

var config = JSON.parse(fs.readFileSync('./train_config.json').toString())

var file = fs.readFileSync('./train_train.csv').toString()
var lines = file.split('\n')
var file_count = lines.length - 1

function spawn(opt){
    return new Promise((resolve, reject)=>{
        var spawn_obj = spawn_(opt.cmd, { shell: true });

        var full_output = ''
        spawn_obj.stdout.on('data', function (data) { full_output += data.toString(); if (opt.stdout) opt.stdout(data); });
        spawn_obj.stderr.on('data', function (data) { full_output += data.toString(); if (opt.stderr) opt.stderr(data); });
        spawn_obj.on('exit', function (code) {
            resolve(full_output)
        })
    })
}


var loaded = 0


var start_time
var countdown = {
    timer: undefined,
    time: 0
}

var triggers = {
    '\r\n': data => {
        //console.log(data)
    },

    'INFO:spleeter:Loading audio': data => {
        loaded++
        //console.log(`${loaded} / ${file_count} completed`)
    },

    'step =': data => {
        var steps = parseInt(data.split('step = ')[1].split(' ')[0])
        if (!start_time){
            start_time = new Date()
            console.log('STARTING. Please hold...')
            return
        }

        var now = new Date()
        var timeDiff = now - start_time
        timeDiff /= 1000;
        
        var steps_per_second = steps / timeDiff
        var ETA = (config.train_max_steps - steps) / steps_per_second
        //console.log(`${steps_per_second} steps per second`)

        countdown.time = ETA
        clearInterval(countdown.timer)
        countdown.timer = setInterval(()=>{
            countdown.time--
            console.log(`${secondsToDhms(countdown.time)} remaining`)
        }, 1000)
    },

    'Model training done': ()=>{
        console.log('DONE')
    }
}

function tryParseProgress(data_in){
    log(data_in)
    var split = data_in.split('\r\n')
    for (var i in split){
        var data = split[i]
        for (var key in triggers){
            if (data.indexOf(key) > -1){
                triggers[key](data)
            }
        }
    }
}

var commands = [
    'c:/users/user/anaconda3/Scripts/activate.bat c:/users/user/anaconda3/',
    ''
]

var args = [
    'python -m',
    'spleeter train -p train_config.json -d e:/ --verbose'
]

var full_cmd = commands.join(' & ') + ' ' + args.join(' ')

spawn({
    cmd: full_cmd,
    stdout: (data)=>{ tryParseProgress(data.toString()) },
    stderr: (data)=>{ tryParseProgress(data.toString()) },
}).then( full_output => {
    clearInterval(countdown.timer)
    console.log('DONE')
}).catch(e =>{
    console.log('Rejected at Spleeter.begin()'.red)
    console.log(e)
})
```

**Comment by hassan8971** [comment]
It's been a long time since you have opened this issue, but dude were you able to train your own model finally? and how long did it take?
And would you tell me please how to use this nodejs script you've put above?

**Comment by Pereitor** [comment]
> Ugh this is so frustrating. Nothing in the documentation either other than `making the separation process very fast (more than 100x realtime)`.
> 
> In that case my 1 minute song could be processed up to 100 times faster, e.g 0.6 sec, so 10 songs would take 6 seconds.
> 
> Even if CPU is slower than GPU, if it did it in realtime it would take only 10 minutes, but still, well above 1 hour has passed now.
> 
> Can absolutely no one in the Spleeter dev team address this concern?
> 
> I'm eager to train my own models. I have so many different datasets by now :(

Hi,

You are doing a lot of calculations, yet I think you missed the most basic point:

> Ugh this is so frustrating. Nothing in the documentation either other than `making the separation process very fast (more than 100x realtime)`.
> 
> In that case my 1 minute song could be processed up to 100 times faster, e.g 0.6 sec, so 10 songs would take 6 seconds.

Nope. Using the tool for separating is not the same as TRAINING it. You are mixing de-mixing times and training times.
Maybe you could DEMIX 10 songs in 6 seconds.
TRAINING the model to learn to demix them is gonna take a lot more.

> My CPU does aprox 712 steps per hour, so training on my CPU will take ~58 days? YIKES!

That seems to be more on par with that I read some time ago about a couple of weeks or so using a GPU with 16 GB RAM and CUDA drivers.
