### ISSUE TITLE
Wiki page points to missing file for musdb_config.json

### ISSUE THREAD

**Issue by ahatzz11** [deezer/spleeter#22]
# Bad link in wiki

The 'train your model section' on the wiki page has a bad link: https://github.com/deezer/spleeter/wiki/2.-Getting-started#train-model

Specifically:

> A JSON configuration file such as this one that gathers all parameters needed for training and paths to CSV file.

The current link is: https://github.com/deezer/spleeter/blob/master/configs/mudsb_config.json

The correct link is https://github.com/deezer/spleeter/blob/master/configs/musdb_config.json

Just a flip of the `s` and `d`

**Comment by Faylixe** [comment]
Thanks for the issue ! I fixed it ;)
