### ISSUE TITLE
[Discussion] Anyone had success in updating source to work using AMD GPU on MacBook Pro w/ PlaidML

### ISSUE THREAD

**Issue by rayanarman** [deezer/spleeter#221]
Anyone had success in updating source to work using AMD GPU on MacBook Pro w/ PlaidML?

I can get custom model training/inference to work via CPU perfectly fine on macbook, but could not get it to use the built in AMD GPU. I tried installing python plaidML and updating source to adjust tensorflow inits to use the plaidML GPU link. This didn't work! and unfortunately I no longer have my code adjustments.

Has anyone else tried this? Am I missing something? 

Thanks!

**Comment by mmoussallam** [comment]
Hi @rayanarman 

Since we use tensorflow and Cuda underneath, there's no way you will get that running on non-NVIDIA devices easily.. unless your card support a valid CUDA install that's simply not possible.
