### ISSUE TITLE
[Bug] 4stems mode stops executing without output and exception reported

### ISSUE THREAD

**Issue by Rohan-Kishibe** [deezer/spleeter#225]
## Description

While 2stems mode works sucessfully, 4stems mode fails. In cmd I use this command: 
python -m spleeter separate -i D:\spleeter\src\temp.mp3 -p spleeter:4stems -o D:\spleeter\
and after a while it stops and ends with:
OMP: Info #250: KMP_AFFINITY: pid 13616 tid 18408 thread 28 bound to OS proc set 1
OMP: Info #250: KMP_AFFINITY: pid 13616 tid 5420 thread 29 bound to OS proc set 3
OMP: Info #250: KMP_AFFINITY: pid 13616 tid 14956 thread 30 bound to OS proc set 5
OMP: Info #250: KMP_AFFINITY: pid 13616 tid 16504 thread 31 bound to OS proc set 7
PS C:\Users\user>

## Step to reproduce

1. Installed using `conda`
2. Run as `command in cmd`
3. Got `no result and no exception reported` error

## Output
```
nothing....
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows  |
| Installation type | Conda             |
| RAM available     | XGo                             |
| Hardware spec     | CPU             |

## Additional context

I didn't let the model download automatically in the first run because it's too slow; instead I download from the release and put it in /pretrained_models/4stems.

**Comment by mmoussallam** [comment]
Hi @Rohan-Kishibe 

Not sure what's happening here and I don't know how to help you. Would it be possible to delete the models and try the automatic download again ?

**Comment by Christilut** [comment]
I'm running into the same problem. No real useful error but lots of `OMP` output:

```
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids. OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-11 OMP: Info #156: KMP_AFFINITY: 12 available OS procs OMP: Info #157: KMP_AFFINITY: Uniform topology OMP: Info #179: KMP_AFFINITY: 1 packages x 6 cores/pkg x 2 threads/core (6 total cores) OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map: OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0 OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 0 thread 1 OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 1 thread 0 OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 1 thread 1 OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 2 thread 0 OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 0 core 2 thread 1 OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 3 thread 0 OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 0 core 3 thread 1 OMP: Info #171: KMP_AFFINITY: OS proc 8 maps to package 0 core 4 thread 0 OMP: Info #171: KMP_AFFINITY: OS proc 9 maps to package 0 core 4 thread 1 OMP: Info #171: KMP_AFFINITY: OS proc 10 maps to package 0 core 5 thread 0 OMP: Info #171: KMP_AFFINITY: OS proc 11 maps to package 0 core 5 thread 1 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 14160 thread 0 bound to OS proc set 0 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 15400 thread 1 bound to OS proc set 2 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 1836 thread 2 bound to OS proc set 4 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 15504 thread 3 bound to OS proc set 6 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 14408 thread 4 bound to OS proc set 8 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 7848 thread 5 bound to OS proc set 10 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 7028 thread 6 bound to OS proc set 1 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 14520 thread 7 bound to OS proc set 3 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 9820 thread 8 bound to OS proc set 5 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 16092 thread 9 bound to OS proc set 7 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 8816 thread 10 bound to OS proc set 9 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 16624 thread 11 bound to OS proc set 11 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 15492 thread 12 bound to OS proc set 0 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 17136 thread 13 bound to OS proc set 2 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 3252 thread 14 bound to OS proc set 4 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 16248 thread 15 bound to OS proc set 6 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 15152 thread 16 bound to OS proc set 8 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 17380 thread 17 bound to OS proc set 10 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 296 thread 18 bound to OS proc set 1 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 10420 thread 19 bound to OS proc set 3 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 16480 thread 20 bound to OS proc set 5 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 6704 thread 21 bound to OS proc set 7 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 6956 thread 22 bound to OS proc set 9 OMP: Info #250: KMP_AFFINITY: pid 16796 tid 16824 thread 23 bound to OS proc set 11 
```

Removing the models and trying again does work but occasionally this happens again

**Comment by Christilut** [comment]
I'm pretty sure this is a memory issue... I'm running spleeter in a Windows 10 VM with Hyper-V and I'm getting this problem maybe 80% of the time with 4GB of memory.

If I up it to 8GB, the problems occurs maybe 20% of the time.

My host PC has 32GB and it never occurs.

@mmoussallam can you try to recreate this in a VM? I'm using the Hyper-V VM from [Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)

**Comment by NachalnikKamchatki** [comment]
> I'm pretty sure this is a memory issue... I'm running spleeter in a Windows 10 VM with Hyper-V and I'm getting this problem maybe 80% of the time with 4GB of memory.
> 
> If I up it to 8GB, the problems occurs maybe 20% of the time.
> 
> My host PC has 32GB and it never occurs.

Totally agree with you. These are memory problems. I have 16GB of RAM, but if I take 5stems, then such an error can occur.

**Comment by kiratdeluxe** [comment]
i can concur, if you add the verbose mode --verbose you will certainly see somthing like that :
2020-02-11 07:04:08.024697: W tensorflow/core/framework/allocator.cc:107] Allocation of 681443328 exceeds 10% of system memory.
and my memory was at less than 144mb

where to put the verbose mode:
spleeter separate -p spleeter:4stems --verbose -i /input/the_organ_brother.mp3 -o /output

for the docker container with nvidia :

nvidia-docker run -v $AUDIO_OUT:/output -v $AUDIO_IN:/input -v $MODEL_DIRECTORY:/model -e MODEL_PATH=/model researchdeezer/spleeter separate -p spleeter:4stems --verbose -i /input/the_organ_brother.mp3 -o /output

the bug i have closed :

https://github.com/deezer/spleeter/issues/204
