### ISSUE TITLE
I can't find the output folder where the files are going to? 

### ISSUE THREAD

**Issue by sullivanstrong** [deezer/spleeter#226]
Where can I find the output folder where the .wav files go to?

**Comment by julienbeisel** [comment]
When I use Spleeter with the 2stems model, a directory with the same name as my audio file is created in my working directory and inside that directory I can find the 2 separate tracks created (vocals & accompaniment)

**Comment by Angelmmiguel** [comment]
I had the same issue when using the docker image. I executed the following command and got these logs:

```
docker run --rm -v $(pwd):/app -v $(pwd)/audio.mp3:/audio.mp3 researchdeezer/spleeter:latest separate -i /audio.mp3 -o /app
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:spleeter:Validating archive checksum
INFO:spleeter:Extracting downloaded 2stems archive
INFO:spleeter:2stems model file(s) extracted
```

I didn't get any output at all. Then, I reduced the length of the song from 3 minutes to 30 seconds by cutting some parts and it worked:

```
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:spleeter:Validating archive checksum
INFO:spleeter:Extracting downloaded 2stems archive
INFO:spleeter:2stems model file(s) extracted
INFO:spleeter:File /app/('audio', '.mp3')/accompaniment.wav written
INFO:spleeter:File /app/('audio', '.mp3')/vocals.wav written
```

I'm not sure if there's a limitation in the docker environment.

**Comment by yamamushi** [comment]
It's because Docker is running out of memory, you need to increase your available resources and then it should extract properly to your specified output directory. 

I've found 6gb to work for me so far, but to be honest I didn't really test with anything lower. 

More info here: https://stackoverflow.com/questions/44417159/docker-process-killed-with-cryptic-killed-message

**Comment by Angelmmiguel** [comment]
Will try that @yamamushi. Thanks!
