### ISSUE TITLE
24bit audio

### ISSUE THREAD

**Issue by stickyninja3** [deezer/spleeter#227]
Just a quick question.  I have noticed 2 things when running spleeter.  1. the limit on the frequency (upto 11k, and i will have a play with the 16k models soon), which i have been reading about in the wiki.

What about 24bit audio.  I have also noticed that the files get converted to 16bit rather than retaining the full 24bits.  The bitrate option is that only for lossy compression?

If i wanted to go to 24bit, what do i need to change in the code to do this?

Thanks,
Alec

**Comment by mmoussallam** [comment]
Hi @stickyninja3 

You can probably tweak the output a bit in the code to modify the bitrate (passing it as an argument to ffmpeg). You should not expect too much of it though, as any difference would probably be hard to notice over the separation artefacts.

**Comment by faroit** [comment]
@stickyninja3 you can just pass the `codec=pcm_s24le` to write as 24bit files
