### ISSUE TITLE
[Question] Training error

### ISSUE THREAD

**Issue by cheffplayer** [deezer/spleeter#228]
I looked at your wiki and saw that it was possible to train a new model with our own data. I have went about setting up everything that the wiki states, but the furthest I can get is this error message:

> TypeError: x and y must have the same dtype, got tf.string != tf.int32

The command I am executing is

> spleeter train -p musdb_config.json -d D:\spleeter

My config file is as follows:

> {
>     "train_csv": "musdb_train.csv",
>     "validation_csv": "musdb_validation.csv",
>     "model_dir": "musdb_model",
>     "mix_name": "mix",
>     "instrument_list": ["synth", "drums", "guitar"],
>     "sample_rate":44100,
>     "frame_length":4096,
>     "frame_step":1024,
>     "T":512,
>     "F":1024,
>     "n_channels":2,
>     "n_chunks_per_song":1,
>     "separation_exponent":2,
>     "mask_extension":"zeros",
>     "learning_rate": 1e-4,
>     "batch_size":4,
>     "training_cache":"cache/training",
>     "validation_cache":"cache/validation",
>     "train_max_steps": 100000,
>     "throttle_secs":600,
>     "random_seed":3,
>     "save_checkpoints_steps":300,
>     "save_summary_steps":5,
>     "model":{
>         "type":"unet.unet",
>         "params":{
>                "conv_activation":"ELU",
>                "deconv_activation":"ELU"
>         }
>     }
> }

Both my .csv are in correct format

> drums_path,guitar_path,synth_path,mix_path,duration
> train/christmas2drums.wav,train/christmas2guitar.wav,train/christmas2synth.wav,train/christmas2.wav,205.872‬

I have no idea what I am doing wrong, I wish there was a step-by-step tutorial on training our own models. Also, I am using the most latest version of spleeter-gpu installed by conda

**Comment by aidv** [comment]
You're not the only one having issues with training, I do too, and it seems like the Spleeter dev team has no interest in helping the community :/

**Comment by mmoussallam** [comment]
Hi @cheffplayer 

It's not easy for us to help you if you don't provide the details we ask for in the Bug issue template, namely : what is the platform you use? how did you install spleeter ? what exact code are you running to get this message ?

**Comment by aidv** [comment]
@cheffplayer did you manage to solve this?

**Comment by johndpope** [comment]
double check your validation csv - when I put 1 line in it with the same values as train.csv - it worked.
(also make sure there's no errors thrown while training - you need all the dependencies installed. conda install -c conda-forge ffmpeg libsndfile )
