### ISSUE TITLE
Example file only generated single stem

### ISSUE THREAD

**Issue by futuresushi** [deezer/spleeter#23]
Hello! I installed Git and Conda using a method linked below then installed and activated the Conda environment per the instructions in your guide (though I had to perform an additional step priming Conda for the Bash environment to actually use the Activate command).

When running with the example script using the 2stems parameter, I get the separated vocals as a wav file in the output folder, but it does not seem to generate the accompaniment file.

## Terminal output

`Matthew@Matthew-PC MINGW64 ~
$ conda activate spleeter-cpu
(spleeter-cpu)
Matthew@Matthew-PC MINGW64 ~
$ spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output
INFO:tensorflow:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:tensorflow:Using config: {'_model_dir': 'pretrained_models\\2stems', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.7
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E7DADDA2E8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\spleeter\model\functions\unet.py:29: The name tf.keras.initializers.he_uniform is deprecated. Please use tf.compat.v1.keras.initializers.he_uniform instead.

INFO:tensorflow:Apply unet for vocals_spectrogram
INFO:tensorflow:Apply unet for accompaniment_spectrogram
INFO:tensorflow:Done calling model_fn.
WARNING:tensorflow:From c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\ops\array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
WARNING:tensorflow:From c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from pretrained_models\2stems\model
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.int32
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string
INFO:tensorflow:Loading audio b'spleeter/audio_example.mp3' from 0.0 to 600.0
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-7
OMP: Info #213: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #276: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #156: KMP_AFFINITY: 8 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #191: KMP_AFFINITY: 1 socket x 4 cores/socket x 2 threads/core (4 total cores)
OMP: Info #215: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to socket 0 core 0 thread 1
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to socket 0 core 1 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to socket 0 core 1 thread 1
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to socket 0 core 2 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to socket 0 core 2 thread 1
OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to socket 0 core 3 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to socket 0 core 3 thread 1
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 11752 thread 0 bound to OS proc set 0
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 4472 thread 1 bound to OS proc set 2
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 4284 thread 2 bound to OS proc set 4
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 3380 thread 3 bound to OS proc set 6
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 4688 thread 4 bound to OS proc set 1
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 652 thread 5 bound to OS proc set 3
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 12860 thread 6 bound to OS proc set 5
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 3492 thread 7 bound to OS proc set 7
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 8212 thread 8 bound to OS proc set 0
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 12364 thread 9 bound to OS proc set 2
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 3224 thread 10 bound to OS proc set 4
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 6032 thread 11 bound to OS proc set 6
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 6368 thread 12 bound to OS proc set 1
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 5108 thread 13 bound to OS proc set 3
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 3324 thread 14 bound to OS proc set 5
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 9792 thread 15 bound to OS proc set 7
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 1132 thread 16 bound to OS proc set 0
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 9304 thread 17 bound to OS proc set 2
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 7064 thread 18 bound to OS proc set 4
OMP: Info #251: KMP_AFFINITY: pid 6044 tid 7540 thread 19 bound to OS proc set 6
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
c:\users\matthew\miniconda3\envs\spleeter-cpu\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])`

## Your Setup

In particular:

- OS: Windows 10
- Execution Environment : Conda/Git installed using the following guide: https://www.earthdatascience.org/workshops/setup-earth-analytics-python/setup-git-bash-conda/

**Comment by futuresushi** [comment]
When running with a longer file (a ~10MB file for a 4m:39s song) it seemed to hang on the 
`INFO:tensorflow:Loading audio b'spleeter/condos.mp3' from 0.0 to 600.0` 
step forever. I assume there must be something wrong with the setup environment because I would think 8 cores could handle that just fine

**Comment by Faylixe** [comment]
Please check [FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-do-i-have-some-stems-not-written-to-disk-).
