### ISSUE TITLE
Mixerrog

### ISSUE THREAD

**Issue by Mixerrog** [deezer/spleeter#232]
## Description

Spleeter Training Files?

## Additional information

Discordance mentioned the BEAN dataset, that contains:

24,097 songs
79 hours of audio stems
majority of pop/rock songs

Is it being used by the latest Spleeter version or is there a way to download & use it for the training files if not?

**Comment by mmoussallam** [comment]
We cannot share the dataset but the pre-trained model shipped with the latest version of spleeter are using it yes.
