### ISSUE TITLE
Rrate must be specified when data is a numpy array or list of audio samples

### ISSUE THREAD

**Issue by ssumitk14** [deezer/spleeter#236]
![spleeter](https://user-images.githubusercontent.com/47416945/72617798-c64f8d00-395f-11ea-96f1-8e8eb1d6aa22.JPG)

**Comment by mmoussallam** [comment]
Hi @ssumitk14 

This is not a spleeter related question, you need to look at the jupyter notebook documentation on embedding audio.

**Comment by ssumitk14** [comment]
Hi @mmoussallam please take a look at this.
![spleeter1](https://user-images.githubusercontent.com/47416945/72619394-272c9480-3963-11ea-9c72-b595f87d633c.JPG)

**Comment by aarux-11** [comment]
![image](https://user-images.githubusercontent.com/71340243/177830401-46a95b66-a67a-4e88-b5e2-865fb5630bbe.png)
The attached image will give a better perspective.
Default sampling rate is 22kHz which can be overriden.

The complete function is:

IPython.display.Audio(data=None, filename=None, url=None, embed=None, rate=None, autoplay=False)
