### ISSUE TITLE
[Discussion] File already exist Error

### ISSUE THREAD

**Issue by ssumitk14** [deezer/spleeter#238]
![spleeter](https://user-images.githubusercontent.com/47416945/72678330-cfa93880-3aca-11ea-84e0-be73895608ad.JPG)
I'm getting error while running the separate command. What can be wrong ?

**Comment by RISE-Legit** [comment]
I also came across this issue. No 'london' file/folder existed before running the command. The only difference I can see between this and other files I separated is that this file was a full 6 minute mp3, whereas my previous successful separations were about 30 seconds long.

```
(base) C:\Users\Owner\spleeter-master>python -m spleeter separate -i spleeter/london.mp3 -p spleeter:4stems -o output

E:\Miniconda\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "E:\Miniconda\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Owner\spleeter-master\spleeter\audio\ffmpeg.py", line 108, in save
    os.makedirs(directory)
  File "E:\Miniconda\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'output\\london'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Miniconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Miniconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Owner\spleeter-master\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\Owner\spleeter-master\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\Owner\spleeter-master\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\Owner\spleeter-master\spleeter\commands\separate.py", line 45, in entrypoint
    separator.join()
  File "C:\Users\Owner\spleeter-master\spleeter\separator.py", line 68, in join
    task.get()
  File "E:\Miniconda\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
FileExistsError: [Errno 17] Cannot create a file when that file already exists: 'output\\london'

(base) C:\Users\Owner\spleeter-master>
```

**Comment by ssumitk14** [comment]
@RISE-Legit I uninstalled and installed everything again and now this error occurs for 1/4  times. Also, the size of output files is 10 times the original audio. Can we do anything about that?

**Comment by aidv** [comment]
Make the output path an absolute path. E.g `python -m spleeter separate -i spleeter/london.mp3 -p spleeter:4stems -o "c:\output"`

**Comment by Christilut** [comment]
I have the same problem. I think this is an FFMPEG error that tries to replace the input file with the output file at the same path.

Curious that it doesn't always happen though.

**Comment by starinspace** [comment]
I do also have the same error, same here, some files works great and other gives this error. I did also try doing a path "c:\audio\output" but that gives the same error (sometimes). I also notised that some titles with characters like "-" or has a "." in the title does not always work, and when using one and getting the error, it does effect until deleting the "pretrained models" folder and download it again.

A workaround that works, is to delete the "pretrained_models" folder and let them be downloaded again.

But there must be a bug somewhere?

**Comment by starinspace** [comment]
Mmoussallam, I did try the change in "[spleeter/audio/ffmpeg.py](https://github.com/deezer/spleeter/pull/249/commits/a23a41a3800ce43b1c9edbe9ccca1cf3578a10d6)" and that worked great, however, I get error "folder does not exist", so I have to create a folder with the name of the audio-file. But its a great workaround until complete fix.

 (However, spleeter/separator.py change does not work. 131-13)

**Comment by SlayermanGR** [comment]
Make sure you explicitly run the Anaconda Command Prompt as an Administrator in Windows, this solved the problem 100% here.
