### ISSUE TITLE
[Bug] ValueError: Couldn't find trained model at pretrained_models\2stems.

### ISSUE THREAD

**Issue by Christilut** [deezer/spleeter#239]
## Description

I'm getting this error sometimes and it's not clear to me why. My current workaround is to delete the temporary folder that contains the stems and to try again. That usually works.

## Step to reproduce

1. Installed using `conda`
2. Run as `user`
3. Got `ValueError: Couldn't find trained model at pretrained_models\2stems.` error

Can't reliably reproduce this yet but it does occur quite often. Maybe it has to do with cancelling the process mid-way. I tried that a bit, but nothing concrete yet.

I'll update this issue if I find out more. Just wanted to let you know that this is going on.

## Output

```bash
ValueError: Couldn't find trained model at pretrained_models\2stems.
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | Conda |
| RAM available     | 32GB                             |
| Hardware spec     | Ryzen           |

**Comment by Christilut** [comment]
Yes but that's not an acceptable solution, that is a workaround... Something during the execution of spleeter is causing this and that should be solved really

**Comment by mmoussallam** [comment]
Hi @Christilut 

Are you re-downloading the model each time you run the script ? what is the exact command line you are using ?

**Comment by Christilut** [comment]
I'm using spleeter in a script and I extract the 2stems.zip contents to the target directory every time before running spleeter to prevent this issue and a re-download.

```js
`${copiedPythonPath} -m spleeter separate -i "${pathFull}" -p spleeter:2stems-16kHz -o "C:\Users\User\AppData\Local\Temp\spleeter_output_dir\results"`
```

where `copiedPythonPath` is a copied `Python.exe` (so I can kill the process based on name), `pathFull` is the input file.

**Comment by farsdewibs0n** [comment]
> 
> 
> I'm using spleeter in a script and I extract the 2stems.zip contents to the target directory every time before running spleeter to prevent this issue and a re-download.
> 
> ```js
> `${copiedPythonPath} -m spleeter separate -i "${pathFull}" -p spleeter:2stems-16kHz -o "C:\Users\User\AppData\Local\Temp\spleeter_output_dir\results"`
> ```
> 
> where `copiedPythonPath` is a copied `Python.exe` (so I can kill the process based on name), `pathFull` is the input file.

If it's already downloaded, you dont need to donwload the stems again.

**Comment by Christilut** [comment]
Well but that is the current workaround to fix this issue... Something happens to the stem files and replacing them with the original files fixes it temporarily.

**Comment by Christilut** [comment]
Is this problem fixed?
