### ISSUE TITLE
[Discussion] "Runtime Disconnected" to get the Audio..

### ISSUE THREAD

**Issue by ihaveafissue** [deezer/spleeter#240]
I don't know what is the problem.. It never fail just because it was the demo audio you set before. When I try this out in **Google Colab** but it only told me "Runtime Disconnected" and failed to get my audio in the last step. `Audio'output/____/____.wav'`
![png](https://user-images.githubusercontent.com/60128124/72782371-87228400-3c5e-11ea-966a-d50e96e69e96.png)

**Comment by eerilqin** [comment]
你把文件名缩短一下试一试

**Comment by mmoussallam** [comment]
Hi @ihaveafissue 

This is an issue with your Google collab instance, not spleeter.
