### ISSUE TITLE
[Bug] Crashes Windows 10 completely

### ISSUE THREAD

**Issue by starinspace** [deezer/spleeter#245]
## Description

When running the script with "2stems" it works, but with "4stems" it does crash everything, so need to hard reset the pc. (Windows 10 64-bit), I don't know how to get a crash report for powershell cause I don't get one, it just crashes after a minute or two after starting the script.

## Step to reproduce

I'm using this script:
python -m spleeter separate -i test.mp3 -p spleeter:4stems -o output

## Output

```bash
Powershell (even tried with Commandprompt and it does do the same crash), it does not say anything.
```
None
## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | Python / pip / Conda / other             |
| RAM available     | 8.0 GB (6,94 to use)                            |
| Hardware spec     | AMD A10-7800 Radeon R7, Compute Core 4C+8GB, 3,50Ghz             |

## Additional context

Don't know if it might be memory problem or processor? Is there a "low memory"-mode that could be used?

**Comment by mmoussallam** [comment]
Hi @starinspace 

This is unfortunate and quite hard to understand for us, no other complete crash were reported so far. you may want to use the `docker` version instead of conda: check out in the wiki how to use it.

**Comment by D3rel** [comment]
The same thing happened to me, but i don't opened a bug report. 

At first spleeter worked perfectly, but after updating with the files from the last update, this problem started. Every time I try to use 4stems script, my computer starts to consume the whole 8GB ram, making my computer to stop working completely. making my computer to stop working completely. The only option is to disconnect from the plug to restart. :( 

So far I am happy with the result of 2stems with 22k, but it's sad i cant use the 4stems anymore.

**Comment by mmoussallam** [comment]
Hi @D3rel , @starinspace 

Just so you know we have started working on an update that should greatly reduce the amount of RAM consumed by spleeter when running the separate command. I'll keep you posted

**Comment by Richard3234sa** [comment]
Please how to fix this one   

(base) C:\Users\TJPC>cd spleeter

(base) C:\Users\TJPC\spleeter>conda env create -f spleeter/conda/spleeter-cpu.yaml

EnvironmentFileNotFound: 'C:\Users\TJPC\spleeter\spleeter\conda\spleeter-cpu.yaml' file not found


(base) C:\Users\TJPC\spleeter>

**Comment by mmoussallam** [comment]
Hi @starinspace 

We've made some changes recently. Can you please reinstall and tell us i you still have the issue ?

**Comment by mwcm** [comment]
I'm still getting this every couple times I try to separate, although it doesn't freeze for me, just get a full on black screen of death and the computer restarts

this only happens on 4 stem mode, I'm running Win10 64bit on 64GB ram, with no other applications open

**Comment by olejika** [comment]
I installed SpleeterGui 2.9 still crashes the computer
