### ISSUE TITLE
'FFMPEGProcessAudioAdapter' object is not callable

### ISSUE THREAD

**Issue by ZacheryGuan** [deezer/spleeter#25]
## Description
Report a type error using python API

## Step to reproduce
I'm now with the following code:
```
from spleeter.separator import Separator
separator = Separator('spleeter:2stems')
from spleeter.utils.audio.adapter import get_default_audio_adapter

audio_loader = get_default_audio_adapter()
sr = 22050
waveform, _= audio_loader('my_wave_path', sample_rate = sr)
```

1. Installed using `pip`, and ffmpeg library has also been installed
2. Got `TypeError: 'FFMPEGProcessAudioAdapter' object is not callable`

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS 10.14 |
| Python | 3.6, in Jupyter notebook       |

![image](https://user-images.githubusercontent.com/19270716/68202393-9c442b00-fffe-11e9-835c-be37fce271ac.png)

**Comment by mmoussallam** [comment]
Hi Zachary,

It seems to be a typo in the doc, it should be:
`waveform, _= audio_loader.load('my_wave_path', sample_rate = sr)`

**Comment by ZacheryGuan** [comment]
Thanks for your quick response! It works now.

**Comment by Faylixe** [comment]
The wiki has been updated accordingly, thanks.
