### ISSUE TITLE
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.

### ISSUE THREAD

**Issue by stickyninja3** [deezer/spleeter#255]
HI All,

I am currently running a training session on spleeter on the musdb18 dataset.  My thinking being get this working first before i attempt my own training set.

Installed using conda
I am running on a Mac Pro 5,1 (mid 2010) - 128Gb memory - running High Sierra 10.13.6
I also have a nvidia GeForce GTX 980
I have the CUDA drivers installed

I know that tensorflow doesn't support GPU on Mac, so have installed the normal version.

I am getting the following message throughout the processing.

OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.

Is this message coming from TensorFlow or Spleeter?  Also what does it actually mean?

It is still running at the moment, so hopefully will get an idea of how long it will take to train without the use of a GPU.  Of course, if someone knows how to get the GPU working in the above it would be great to know how to do this as well.

Any info would be great.

Thanks,
Alec

**Comment by aidv** [comment]
I don't think GPU acceleration is supported on Mac. It's been mentioned before.
And depending on how large the dataset is, it probably will take several days on the CPU.

A way to calculate a time estimation is to time how many steps it progresses for 10 seconds, divide that by 10, then you get how many steps per seconds. Once you have steps per second, you simply divide total steps with steps per seconds, and you get total seconds it should take to complete training.

**Comment by stickyninja3** [comment]
Thanks,

Its the full musdb18 file set, so 150 songs.  Just checked now, and it is still running, though it does seem to have stopped loading and processing chunks.  Then checkpoint file is updating (last updated an hour ago).  it is up to model.ckpt-2700.index . Does anyone know what number this gets upto.

I will keep people updated as it does appear to be doing something.....

**Comment by aidv** [comment]
Like I said. It's probably going to take days or even weeks.

**Comment by aidv** [comment]
I'm training a 100 file dataset on my RTX 2080 and it's taking about 3 hours to complete.
You are training on a 2010 Mac Pro using the CPU. So, yeah... A few weeks at least... If not months.

**Comment by stickyninja3** [comment]
Hi,

Thanks for the calculations above.  I am assuming that the "number" in the model.ckpt-XXXX.data-00000-of-00001 needs to get to the max steps defined in the JSON.  If so, it looks like it will take about 20 days.

I have stopped the process and restarted using a small sub set of files.  10 for training and 5 for validation.  The processing is just the same as for the large dataset.  This doesn't make sense to me.  I would have thought the processing time would be dependent on the number of training files.  It doesn't appear to.

I have googled and found a blog on getting GPU processing working on tensorflow with a mac.  I am going to attempt and see if this can be done, otherwise looks like i am going to have to go down the PC route.

Thanks for your responses so far.  They have been helpful.

**Comment by aidv** [comment]
The model file is not important. Just open the JSON config file and look at "max steps" or whatever it's called and use that for the formula

I do not know how the underlying technology works, but for me it takes roughly 3.5 hours training using 100 files with 10 files for validation on an RTX 2080.

Instead of going the PC route, consider the cloud route using Google Cloud, AWS, Azure, or any other service.

If I had an nVidia V100 card my estimate tells me it would take less than a minute to train using my 100 files.

I have yet to use a cloud service for this.

**Comment by stickyninja3** [comment]
Thanks for your input, i'll close this issue now.  Building tensorflow to use GPU looks complicated.  I will see how far i get.
