### ISSUE TITLE
How to use it at IOS?

### ISSUE THREAD

**Issue by qzj-ui** [deezer/spleeter#256]

**Comment by mmoussallam** [comment]
In theory you should be able to import the model and use it in CoreML but we did not tested it.

**Comment by Turing311** [comment]
I've found a way to use pretrained models in Android / iOS APPs.

**Comment by naticio** [comment]
> I've found a way to use pretrained models in Android / iOS APPs.

how? I am starting to investigate how to use spleeter for iOS, thanks

**Comment by thatcherclough** [comment]
Did anyone ever figure this out?

**Comment by Nikit333** [comment]
https://github.com/FaceOnLive/Spleeter-Android-iOS

**Comment by paulorrfilho** [comment]
> Did anyone ever figure this out?

I have not found anything yet. The library suggested above is paid, unfortunately.

**Comment by MuhammadAarfeen** [comment]
> https://github.com/FaceOnLive/Spleeter-Android-iOS

I have tried it on ios, but there is a issue with it.

`spleeterSDK.process(wavPath!, outPath: url.path)`
is returning 1 instead of 0 

can anyone help with the issue or Any other way to run spleeter on ios?

**Comment by boring2** [comment]
> > https://github.com/FaceOnLive/Spleeter-Android-iOS
> 
> I have tried it on ios, but there is a issue with it.
> 
> `spleeterSDK.process(wavPath!, outPath: url.path)` is returning 1 instead of 0
> 
> can anyone help with the issue or Any other way to run spleeter on ios?

Yes, I have the same problem. Have you solved it？

**Comment by boring2** [comment]
> > https://github.com/FaceOnLive/Spleeter-Android-iOS
> 
> I have tried it on ios, but there is a issue with it.
> 
> `spleeterSDK.process(wavPath!, outPath: url.path)` is returning 1 instead of 0
> 
> can anyone help with the issue or Any other way to run spleeter on ios?

Yes, I have the same problem. Have you solved it？ @MuhammadAarfeen

**Comment by zhu-j-faceonlive** [comment]
Contact us in repo for the guide.

**Comment by boring2** [comment]
> Contact us in repo for the guide.

加个微信？发我邮箱吧，code.zhen@gmail.com
@zhu-j-faceonlive

**Comment by Collaj90s** [comment]
I messaged faceonlive if I can get a copy of the sdk for my iPad. They asked for $6,000. I’ll just use the free version I already have on my computer.
