### ISSUE TITLE
Larger training base?

### ISSUE THREAD

**Issue by Mixerrog** [deezer/spleeter#257]
## Description

Is there a larger training base available that is based more on rock type songs that would give better stems separations for those types of songs that could be downloaded & used by Spleeter?

Also, is there a way to output flac files instead of wav files + 24 bit output files when 24 bit input files are used with Spleeter?

Thanks for any help on these, Roger

**Comment by mmoussallam** [comment]
Hi @Mixerrog 

I'm not aware of a larger training set available at this date, feel free to browse the [sigsep datasets](https://sigsep.github.io/datasets/) web page that lists all the available options.
