### ISSUE TITLE
Tensorflow/stream_executor/cuda/cuda_dnn.cc:329 Could not create cudnn handle

### ISSUE THREAD

**Issue by stickyninja3** [deezer/spleeter#258]
I have been getting the above error when running the train command.  Spleeter is running on a Windows 10 laptop core i7 gen 9.  With a nvidia geforce gtx 1660 ti.  A friend has lent me their gaming laptop to do these experiments.

I have installed CUDA toolset 10.0 (i have also tried with 10.1 and 10.2).
I have copied the cuDNN files as described by the nvidia documentation.
I installed Anaconda3

spleeter was installed using conda (conda install -c conda-forge spleeter-gpu)

The separation works fine, and runs in a few seconds.

This is something to do with the CUDA installation, but I am not sure where to look.  Anyone out there who has this working any pointers would be grateful.

**Comment by aidv** [comment]
1. Try restarting your computer
2. Try a shorter audio

**Comment by stickyninja3** [comment]
I have restarted the computer a few times.  I even added the AllowMemoryGrowth flag, but that didn't work.  As people have this working out of the tin, it can't be that.

I am having the issue with the training.  So not sure what you mean by shorter audio.

What steps did you take to get this working?

**Comment by aidv** [comment]
@stickyninja3 If the audio is 2 minutes, use a 1 minute audio. If that doesn't work, try a 30 second audio.

The steps I mentioned have solved most of my problems.
