### ISSUE TITLE
[Discussion] How to separate multiple music files with one call function of separate on the terminal?

### ISSUE THREAD

**Issue by chenglong96** [deezer/spleeter#260]
Hi, this the quick start method to separate the music files to vocals and accompaniment,
`git clone https://github.com/Deezer/spleeter`
`conda install -c conda-forge spleeter`
`spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output`

How to call this separate function once for multiple mp3 files(100+) in a folder so that i do not need to convert one by one manually?

**Comment by mmoussallam** [comment]
Hi @chenglong96 ,

depending on your OS and your terminal, you need to use a loop function over your files. see [here](https://www.windows-commandline.com/windows-for-loop-examples/) for documentation.

**Comment by enjoymarcus** [comment]
Hi - I've read through the documentation and there is an option to [batch process](https://github.com/deezer/spleeter/wiki/2.-Getting-started#batch-processing) multiple files in a single function. 

```
spleeter separate \
     -i <path/to/audio1.mp3> <path/to/audio2.wav> <path/to/audio3.ogg> \
     -o audio_output
```

However, I receive error messages when using this, either `-i` is missing, or `<` is not valid. I have tried the following instead;

`spleeter separate -i ./*.WAV -o 2stems -p spleeter:2stems-16khz -o output`

This will process the first file in the folder, and also recognises the other files but does not process them.

Any ideas and input would be appreciated.

Many thanks,

**Comment by ColeBallard** [comment]
> Hi @chenglong96 ,
> 
> depending on your OS and your terminal, you need to use a loop function over your files. see [here](https://www.windows-commandline.com/windows-for-loop-examples/) for documentation.

If you wanted to loop through a folder using macOS, you could use:

`for f in path/to/*.wav; do spleeter separate -o audio_output -p spleeter:4stems-16kHz $f; done`
