### ISSUE TITLE
Training Does Not Work / Hangs - GPU Version

### ISSUE THREAD

**Issue by stickyninja3** [deezer/spleeter#261]
Hi,

I have just started doing an EPQ for my A levels and have decided to do this on audio technology, and came across spleeter whilst researching ideas on the net.  The idea is to build a system to separate a string quartet.  I can use the musicians as school as part of the project.  I have installed spleeter (see steps below).

I can separate files, so I know spleeter is installed and running.  When I try to run a training session it "hangs".  No output is displayed after it segments the audio in the training folder.  The file

model.ckpt-0.data-00000-of-00001 

does not change and indicate it is reaching the steppoints.  When I run the non GPU version, this increments 300 every 85 minutes (so a model would take about 19 days to learn).  I have left the GPU version running for 12+ hours and no change in these files.

The plan was to get the training working on existing files, and then once confirmed it has worked, start the training on the quartet samples.  

This is how I have configured my system.

1.  Installed Visual Studio 2017 community version.
2. Installed CUDA toolkit 10.0.130
3. Installed cdDNN version 7.3.1. (any higher than this and spleeter would fail with an error)
4.  Installed Anaconda3
5. from an anaconda prompt run

conda install -c conda-forge spleeter-gpu

6.  In the navigator, ensured the cudatoolkit and cudnn versions match

7.  I have downloaded the musdb18hq dataset from Inria and extracted to a folder c:\trainingdata\musdb18hq
8. .csv files stored in c:\trainingdata\configs

9. open anaconda prompt
10. changed to the c:\trainingdata folder and typed the following command

spleeter train -p configs\musdb_config.json -d musdb18hq

When ever I made a change to the environment i would shut down and restart.

When this runs, it creates the cache folder and the musdb_model folder and it loads the audio in the chunks defined in the json file (i set to 10 initially as a test).  The config file is the one provided by spleeter just changed where the files were located in the config.

In the .csv files I am training on 10 files with 4 files in the validation .csv

After it stops loading the audio it simply stops scrolling and doesn't do anything more.  Under verbose mode no errors are reported.

Has anyone actually got the training working on a Windows 10 system?  If so, what steps have i missed out?

## Environment
| ----------------- | ------------------------------- |
| OS                | Windows 10
| Installation type | Conda             |
| RAM available     | 64Gb                            |
| Hardware spec     | GPU   Nvidia GTX1660TI 6GB  CPU Intel i7 Gen 9 2.6 GHz          |

**Comment by thesby** [comment]
Have you downloaded the training data? Can you share it to me? I send my requests for access, but no response.
