### ISSUE TITLE
Tensorflow-gpu - Not having luck with conda

### ISSUE THREAD

**Issue by stickyninja3** [deezer/spleeter#262]
Hi All,

I am not having any luck with Tensorflow and spleeter-gpu.  Training is not workking.  

I have completely removed spleeter and installed tensorflow-gpu version 1.14 using pip.
I have installed CUDA 10.0
I have installed cuDNN 7.4.2 

this is the combination to use as indicated by the tensor flow website.

I have gone through some tensorflow tutorials with the above set-up and proved that the GPU is detected by TF and is used.

Now some questions, probably more for the deezer guys if they can add any detail.

In the installation section of the wiki it says that spleeter-gpu is not available using pip.  I was under the impression that if tensorflow detected a GPU it would use it.  I have installed spleeter using pip and it indeed ignores the GPU.

What needs to be changed in spleeter to use the GPU features of tensorflow?  I have never built packages for conda or pip so is this something done within the package manager?

When trying to debug what was happening with conda, i simply added "print" statements to see where in the code it was having issues.  It was within a tensorflow function 

estimator.train_and_evaluate

which is where i suspected the issue was and why i needed to confirm that tensorflow could see the GPU.

So i know I can change the source code installed by pip / conda.  Where in the code do i need to focus on getting spleeter to use the GPU?

**Comment by mmoussallam** [comment]
Hi @stickyninja3 

The `pip install` method with tensorflow-gpu seems to sometimes work and sometimes not. We're not able to fully understand what goes wrong but there's nothing to change in the code as it is. The issue is with the installation process.
This is why we advise to use either the `conda` or the `docker` versions where we do control what happens.
