### ISSUE TITLE
wav output length is way smaller to mp3 input

### ISSUE THREAD

**Issue by glennford49** [deezer/spleeter#264]
is there any way for the input mp3 length gets the same output length on wav format?

**Comment by mmoussallam** [comment]
Hi @glennford49 

Not sure to understand what happens, can you give more details about your setup, the exact command you launch and what's the output length difference is ?

**Comment by glennford49** [comment]
I figured it out... it has a limit of 10 minutes only on separations task,  i've tried 19 minutes audio input , it outputs only 10 minutes on 4 stems and 2 stems, thanks for your response

**Comment by thrfdth** [comment]
I've also come across the same issue. Is there any way other than splitting audio by 10 minutes?

**Comment by mmoussallam** [comment]
yes there is, using the Python API
