### ISSUE TITLE
[Bug] wiki references incorrect docker image

### ISSUE THREAD

**Issue by sofuture** [deezer/spleeter#265]
## Description

The wiki documentation references the incorrect image on this page: https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-docker-image

It should be `researchdeezer/spleeter` instead of `deezer/spleeter`.

## Step to reproduce

visit https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-docker-image

## Output

n/a

## Environment

n/a

## Additional context

n/a

**Comment by sofuture** [comment]
Too bad you can't PR wikis :/

**Comment by Faylixe** [comment]
Fixed :)
