### ISSUE TITLE
[Discussion] Unable to run spleeter

### ISSUE THREAD

**Issue by deskstar90** [deezer/spleeter#267]
Hello to everyone, so(sigh), I've been trying to get spleeter to run for the last 3 days now, and I've run out of resources or ideas and need help, information overload!!. I've installed Python 3.6.3 today, but tried many other revisions prior to this 3.6.3 and similar issues occurred. I keep getting this error: 
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
Failed to load the native TensorFlow runtime.

I made sure the paths are correct in the system variables, updated Visual C++, manually dragged the DLL in the system32 and sysWOW64...Ugh!! I'm frustrated.. I don't know what else to try.. PLEASE ANY SUGGESTIONS before I pull out all my hair
THANKS
running win10 64bit
[dll_issue.txt](https://github.com/deezer/spleeter/files/4178898/dll_issue.txt)

**Comment by iver56** [comment]
Random user here. I recommend using Anaconda3.

* Make an environment with python 3.6.6: `conda create --name spleeter-env python=3.6.6`
* Install spleeter with dependencies: `conda install -c conda-forge spleeter`

Please don't pull out your hair. That would not improve the situation.

**Comment by deskstar90** [comment]
Thank you for replying iver56, hope you are well.. since my last post I've been reading alot of other posts and possible issues why that error occurs, the only reason "perhaps" is that my cpu does not support AVX, its an older CPU (Intel i5 750) unfortunately and i'm desperately looking for a replacement that supports AVX. Now, do you think that if I follow your recommendations right now without that newer cpu spleeter will work? I'm not exactly sure how to using anaconda but I'm willing to learn. Please let me know, have a nice day

**Comment by deskstar90** [comment]
Ok, I installed Anaconda3 and executed the following; 
Make an environment with python 3.6.6: conda create --name spleeter-env python=3.6.6
Install spleeter with dependencies: conda install -c conda-forge spleeter
my paths are set and conda is working
This is all new environment for me now,
what next? do I run the spleeter commands from cmd prompt or from anaconda navigator? 
I want to learn.. ;)

**Comment by iver56** [comment]
Use anaconda prompt. Remember to activate your newly installed python env (conda activate ...) before doing things like installing and using spleeter inside it.

________________________________

**Comment by deskstar90** [comment]
ok sorry, pls bear with me, is this what I'm supposed to have..or am I missing the python-env
because you asked me to make 2 environments spleeter-env and python-env?

(spleeter-env) C:\Users\RIO>conda env list
# conda environments:
#
base                     C:\Users\RIO\Anaconda3
spleeter-env          *  C:\Users\RIO\Anaconda3\envs\spleeter-env

**Comment by deskstar90** [comment]
Hi, I think I'm getting closer, but still not clear to me how to run the commands. I've watched countless hours of videos and tried to read as much as possible here and there, PLEASE CLARIFY it for me THANKS!!

(spleeter-env) C:\Users\RIO>python -m spleeter separate -i spleeter/America.mp3 -p spleeter:4stems -o output
ERROR:spleeter:An error occurs with ffprobe (see ffprobe output below)

ffprobe version 4.2 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --
-enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshin
eora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --
idstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf
--enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
spleeter/America.mp3: No such file or directory


(spleeter-env) C:\Users\RIO>python spleeter separate -i spleeter/America.mp3 -p spleeter:4stems -o output
python: can't open file 'spleeter': [Errno 2] No such file or directory

**Comment by deskstar90** [comment]
ok, finally, I got it sorted out. Its now working. It works better in Anaconda and I learned a few things along the way.

**Comment by soberdor** [comment]
> 
> 
> Thank you for replying iver56, hope you are well.. since my last post I've been reading alot of other posts and possible issues why that error occurs, the only reason "perhaps" is that my cpu does not support AVX, its an older CPU (Intel i5 750) unfortunately and i'm desperately looking for a replacement that supports AVX. Now, do you think that if I follow your recommendations right now without that newer cpu spleeter will work? I'm not exactly sure how to using anaconda but I'm willing to learn. Please let me know, have a nice day

Hi deskstar90, just to clarify, did you get it to work without replacing your CPU? I'm having the same problem at the moment...

**Comment by deskstar90** [comment]
Hi soberdor, 
Yes, I got it to work with my old intel i5 with no AVX extension. 16Gb of memory helps speed up the process. I also got this to work on an older duo core with 4Gb but its takes forever to split songs.

**Comment by soberdor** [comment]
Thanks! It works for me too now - after increasing the swap file :-)

**Comment by AngyKH** [comment]
Hi deskstar90
I also have the same problem. An old CPU (Intel). Can you help me??

**Comment by deskstar90** [comment]
Sorry AngyKH, the installation is difficult, I since got rid of those old computers as spleeting songs was very slow. It just not worth it, Just get a W10 and it will spleet songs 100x faster. It's very difficult to troubleshoot other people's PC's. good luck
