### ISSUE TITLE
[Bug] Crashes with protobuf 3.11.1 on macOS

### ISSUE THREAD

**Issue by tlk** [deezer/spleeter#271]
## Description

Newer versions of protobuf crashes tensorflow and spleeter. See https://github.com/tensorflow/tensorflow/issues/35573

## Steps to reproduce

```
$ brew install ffmpeg
$ pip3 install spleeter
$ spleeter separate -i myaudio.mp3 -p spleeter:2stems -o output
[libprotobuf ERROR google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
Abort trap: 6
$
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | macOS Catalina  |
| Installation type | pip              |
| RAM available     | plenty                             |

## Workaround

```
pip3 uninstall protobuf
pip3 install protobuf==3.8
```

**Comment by mmoussallam** [comment]
Hi @tlk 

Since we've moved to TF2 and python 3.8 compatibility this should now be fixed. Let us know if that's not the case.
