### ISSUE TITLE
[Discussion] Maximal song length 10min, is there a reason?

### ISSUE THREAD

**Issue by bigboss97** [deezer/spleeter#274]
I converted a song (medley) of ~15min long. The split tracks are exact 10min long. Is there a reason?

**Comment by mmoussallam** [comment]
yes,  by default the song are cropped at 600 seconds. We're working on a new version that will allow to process longer tracks.

**Comment by romi1502** [comment]
To avoid memory issues, the default maximum duration of separation is 10min, but it can be set to any duration using the `-d` option:
```bash
spleeter separate -i my_15min_audio.wav -d 600
```
Just be aware, that processing long files is very memory intensive and can cause OOM errors.
