### ISSUE TITLE
Spletter with large rock based training base

### ISSUE THREAD

**Issue by Mixerrog** [deezer/spleeter#277]
Anyone have a large rock based training base they could share to get better rock song separations?

Thanks, Roger

**Comment by mmoussallam** [comment]
Hi @Mixerrog 

The music information retrieval scientific community maintain a list of [publicly available datasets](https://github.com/ismir/mir-datasets). and the SigSep group has[ one dedicated to stems](https://sigsep.github.io/datasets/) you can use for training.

Hope this helps
