### ISSUE TITLE
[Bug] ValueError: Couldn't find trained model at pretrained_models/2stems.

### ISSUE THREAD

**Issue by ZacheryGuan** [deezer/spleeter#28]
## Description

When I ran the sample with python API, the error was raised. I could not find any pretrained model in this repo either. Do I need to train a model by myself? 

## Step to reproduce

1. Installed using `pip`
2. Run:
```    
    from spleeter.separator import Separator
    separator = Separator('spleeter:2stems')

    from spleeter.utils.audio.adapter import get_default_audio_adapter
    audio_loader = get_default_audio_adapter()
    sr = 22050
    waveform, _ = audio_loader.load(wav_file, sample_rate=sr)

    prediction = separator.separate(waveform)
```
The error is raised at the last line.
`ValueError: Couldn't find trained model at pretrained_models/2stems.`

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS 10.14|
| Installation type | pip             |

**Comment by Faylixe** [comment]
No you don't have to, we choose to make model available through _Github release_ :

https://github.com/deezer/spleeter/releases/tag/v1.4.0

The library will automatically download required model archive if not found on disk. If you have this error , it means that the download step failed somehow. Could you give us the full traceback of the raised exception ?

**Comment by ZacheryGuan** [comment]
Oh, I see. 

I was not aware the spleeter needed to download model resources, so it seemed to become not responding and I terminated the jupyter notebook kernel. After that, though the directory 'pretained_models/2stems' was created, the model has not finished downloading. Maybe the program considers that the model should exist when the above directory exists. 
Now I delete the 'pretrained' directory and it seems to restart to download again. Therefore, it would be better to print some hint to inform users of downloading files. :)

Thanks!

**Comment by Faylixe** [comment]
> Oh, I see.
> 
> I was not aware the spleeter needed to download model resources, so it seemed to become not responding and I terminated the jupyter notebook kernel. After that, though the directory 'pretained_models/2stems' was created, the model has not finished downloading. Maybe the program considers that the model should exist when the above directory exists.
> Now I delete the 'pretrained' directory and it seems to restart to download again. Therefore, it would be better to print some hint to inform users of downloading files. :)
> 
> Thanks!

We do actually log output about model downloading, we will try to improve logging on the next iteration :).
