### ISSUE TITLE
[Feature] Add a `used by` section in the README

### ISSUE THREAD

**Issue by martinratinaud** [deezer/spleeter#281]
Hi

I've used spleeter to build https://www.edityouraudio.com, a free service to split your song (and also to generate a karaoke out of it) and I've found a lot of services that had the same kind of idea.

I think it could be interesting to have a `used by` section in the readme where people using Spleeter could add their own website.

I can make a PR if you agree with this idea

Thanks again for your work!

**Comment by aidv** [comment]
They're not going to do it. It's been discussed before.

**Comment by mmoussallam** [comment]
Hi @martinratinaud 

Thanks for your message. Indeed we've discussed this and for now we don't think this repo is the right place to advertise external services. We're happy that you find spleeter useful though !
