### ISSUE TITLE
[Bug] spleeter seperating my own mp3 failure by using docker image  

### ISSUE THREAD

**Issue by tonywk** [deezer/spleeter#283]
## Description

spleeter failed to seperate my own mp3 which is stored in the directory as docker's input volume  
running the default command was successful: docker run -v $(pwd)/output:/output researchdeezer/spleeter separate -i audio_example.mp3 -o /output

## Step to reproduce

1. Installed using `spleeter docker image on win7`
2. Run as `docker run -v $(pwd)/input:/input -v $(pwd)/output:/output -v $(pwd)/model:/model -e MODEL_PATH=/model researchdeezer/spleeter separate -i /input/song1.mp3 -o /output`
3. Got `terminate called after throwing an instance of 'std::bad_alloc` error

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows7 64bit |
| Installation type | Docker image,virtual machine 2 processor,2G RAM              |
| RAM available     | total 8G RAM                             |
| Hardware spec     | intel i5-6200             |

**Comment by mmoussallam** [comment]
Hi @tonywk 

how big is your mp3 file exactly ? 2G RAM in your virtual machine might be too low to operate on a large one.

**Comment by tonywk** [comment]
My mp3 is about 5M, not big..

**Comment by mmoussallam** [comment]
Hi @tonywk 

We've made some tests, and 2Gb for a full 5M file will not be sufficient. Try to split your file in smaller pieces.
