### ISSUE TITLE
[Feature] Progress monitoring

### ISSUE THREAD

**Issue by micbuffa** [deezer/spleeter#284]
Hi! We're using Spleeter server side from NodeJS and we would like to report the progress while spleeter is working. Is there an option to display #####... characters as spleeter is progressing in the stem separation? 

Thanks in advance !

**Comment by aidv** [comment]
Has been asked before. Apparently not possible.

**Comment by mmoussallam** [comment]
Hi @micbuffa hope you're well !

Indeed, as @Faylixe mentioned in #71 it's not straightforward to do because most of the processing happens in tensorflow layers. We could only provide a very binary indicator, which would not be of much interest.

**Comment by micbuffa** [comment]
Thanks, I missed #71. Sorry for asking twice... Indeed, this seems complicated....
