### ISSUE TITLE
[Discussion] download model archive on ecach process ? 

### ISSUE THREAD

**Issue by daslicht** [deezer/spleeter#287]
is it normal that spleeter lkeeps downloading the model archive on each process ?
I anytime get :
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz

Cheers Marc

**Comment by Franceshe** [comment]
Well, I have the same problem after trying to 
`pip install spleeter`
and do
`spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output`
After checking the process:
I found 
`
96251 ttys010    0:04.12 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96254 ttys010    0:00.04 /Users/siyunhe/anaconda3/bin/python -c from multiprocessing.semaphore_tracker import main;main(7)
96255 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96256 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96257 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96258 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96259 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96260 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96261 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96262 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96263 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96264 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96265 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
96266 ttys010    0:00.00 /Users/siyunhe/anaconda3/bin/python /Users/siyunhe/anaconda3/bin/spleeter separate -i spleeter/audio_example.mp3 -p sple
`
Does anyone know how long it takes for the model to download?

**Comment by Franceshe** [comment]
> is it normal that spleeter lkeeps downloading the model archive on each process ?
> I anytime get :
> INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
> 
> Cheers Marc

Actually it is faster than I thought, around 6min with 300kb/s, better to have a process bar to 
show the download procedure.

**Comment by mmoussallam** [comment]
Hi @daslicht  @Franceshe 

It should definitely not need to download the model more than once. This probably means it gets saved in a temporary folder that is cleaned after your execution. What's your setup ? are you executing in a docker ?

**Comment by MrPatben8** [comment]
Is there a way to point spleeter to the folder of pretrained_models instead of having it download it and extract it every time?

**Comment by daslicht** [comment]
nope just macos mojave here. anyway to determine where it gets downloaded ?

**Comment by mmoussallam** [comment]
the model should be downloaded in a folder called `pretrained_models` by default.
You can change that (and actually avoid re-downloading) by explicitely setting the environment variable `MODEL_PATH` before calling spleeter.

**Comment by daslicht** [comment]
Ok, it seams to download that folder in the same folder execute the process. For any conversion I get an output  and that pretrained_models folder

**Comment by mmoussallam** [comment]
something like `export MODEL_PATH=<path/to/pretrained_models/>`

**Comment by daslicht** [comment]
and this will be permanent or just for the session ?

**Comment by mmoussallam** [comment]
Just for the session but you can also set it up permanently. Look on google how to depending on your OS and which terminal/shell you're using.

**Comment by daslicht** [comment]
Got it, Thank you very much !

**Comment by daslicht** [comment]
output cant be a path no ?
