### ISSUE TITLE
[Discussion] Pip method don't work

### ISSUE THREAD

**Issue by martobg10** [deezer/spleeter#289]
I followed these instructions - https://github.com/deezer/spleeter/wiki/1.-Installation#using-pip

but have this error:
https://i.postimg.cc/gjw8r7k5/Annotation-2020-03-11-232504.png

thanks in advance!

**Comment by stickyninja3** [comment]
Try using pip3 instead of pip.  You may need to install additional dependencies as these don't get installed using pip, but do with Conda.

**Comment by martobg10** [comment]
I'm with Python 3.8.2. Is this the problem?

**Comment by Zcooger** [comment]
Yes. It is too new for Spleeter, for example use the 3.7.4 version.

**Comment by martobg10** [comment]
Fixed, thank you!
