### ISSUE TITLE
[Bug] Separation multiprocessing task timeout may be too short

### ISSUE THREAD

**Issue by somewhatlurker** [deezer/spleeter#29]
## Description

While trying to find a definite cause of missing output files, I found an unrelated issue: when files take longer than the timeout to save, the files will be truncated early (this is very uncommon with the default value of 20s, but possible).

## Step to reproduce

I suppose you could reproduce this by generating many artificial disk reads/writes during saving.
Alternatively , you can modify the timeout value at https://github.com/deezer/spleeter/blob/6f1a2926488e9c9c1fb6d6dc024ef7b4fb0e7ea9/spleeter/commands/separate.py#L153 to a much lower value. Using slower disks or longer files may make it easier to find a suitable value. I personally saw this most often (not always though) with timeouts of ~2 seconds when using the 2stems model on a ~3 minutes long track.

## Output

N/A

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | pip |
| RAM available     | ~16GB                             |
| Hardware spec     | Ivy Bridge Desktop i5, writing to a single consumer mechanical disk (no RAID) |

## Additional context

It seems like it may be more appropriate to call [close](https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.pool.Pool.close) and [join](https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.pool.Pool.join) on the pool instead of using a fixed timeout, but just increasing the timeout would also work for most cases.

This may also fix #17

**Comment by Faylixe** [comment]
Thanks a lot for the detailed report, it sound like it would probably explain lot of issues, I will dive into it tomorrow and probably submit a new release ASAP :)

**Comment by Faylixe** [comment]
We finally realised that we have some issues with the way we are interacting with `FFmpeg` for audio loading and saving (mostly on _Windows_). We would explain most of the issues we have got so far. We implemented a new audio adapter based on `ffmpeg-python` which will be way more reliable and are currently testing it.

We also removed timeout from asynchronous tasks as suggested and simply wait for associated pool to end. It doesn't make sense to apply timeout with a command line based utility :)

**Comment by somewhatlurker** [comment]
Okay, that sounds great. Hopefully it does fix everything up.

Thanks for getting this all sorted out so quickly.

**Comment by Faylixe** [comment]
> Okay, that sounds great. Hopefully it does fix everything up.
> 
> Thanks for getting this all sorted out so quickly.

Please retry with the newly uploaded version (1.4.2) on PyPi.

**Comment by somewhatlurker** [comment]
It's hard to be sure because I only had intermittent issues myself (and extremely rarely the exact issue that was reported here from timeouts), but I just did a test that seemed to work fine so it would appear there's at least no regressions anywhere.

I also noticed that output logging (`INFO:spleeter:File _____ written`) seems to be working on Windows now, but that's off topic for that issue.

**Comment by Faylixe** [comment]
Great, closing the issue then, if this is happing again we will reopen it ;)

**Comment by somewhatlurker** [comment]
Perhaps I actually spoke a little soon. I just had a file not written even with the changes. But that's probably better discussed in a separate issue due to having a different cause (if at all, because like the FAQ says it's probably memory related -- I had a friend experience it on linux too today which I assume means it's probably something you would've detected in testing if it's a real bug in something else)
