### ISSUE TITLE
Command not found: Spleeter

### ISSUE THREAD

**Issue by chrisgauthier9** [deezer/spleeter#290]
<img width="568" alt="Screen Shot 2020-03-12 at 9 33 25 AM" src="https://user-images.githubusercontent.com/58147163/76526825-87602400-6444-11ea-9ec2-a16ea279bd02.png">

Any ideas? I followed all the instructions.

**Comment by mmoussallam** [comment]
Hi @chrisgauthier9 , please use the full issue template with info on your setup so that we can help.

**Comment by ovrdrvn** [comment]
This bug is back
