### ISSUE TITLE
[Bug] Unknown encoder m4a

### ISSUE THREAD

**Issue by MrPatben8** [deezer/spleeter#293]
## Description
When using the -c option for selecting the m4a encoder for the output files, the process fails. This appears to be related to FFMPEG. 

## Step to reproduce
1. cd into the directory with song.mp3
2. run `spleeter separate -i song.mp3 -c m4a -p spleeter:4stems -o output `

## Output

`ERROR:spleeter:FFMPEG error: b"ffmpeg version git-2020-03-11-36aaee2 Copyright (c) 2000-2020 the FFmpeg developers\r\n  built with gcc 9.2.1 (GCC) 20200122\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf\r\n  libavutil      56. 42.100 / 56. 42.100\r\n  libavcodec     58. 75.100 / 58. 75.100\r\n  libavformat    58. 41.100 / 58. 41.100\r\n  libavdevice    58.  9.103 / 58.  9.103\r\n  libavfilter     7. 77.100 /  7. 77.100\r\n  libswscale      5.  6.100 /  5.  6.100\r\n  libswresample   3.  6.100 /  3.  6.100\r\n  libpostproc    55.  6.100 / 55.  6.100\r\nGuessed Channel Layout for Input Stream #0.0 : stereo\r\nInput #0, f32le, from 'pipe:':\r\n  Duration: N/A, bitrate: 2822 kb/s\r\n    Stream #0:0: Audio: pcm_f32le, 44100 Hz, stereo, flt, 2822 kb/s\r\nUnknown encoder 'm4a'\r\n"`

## Environment

| OS                | **Windows**  |
| Installation type |  **pip** |
| RAM available     | 16Gb |
| Hardware spec     | Nvidia GTX1070 / AMD FX-6300 |

**Comment by mmoussallam** [comment]
Hi @MrPatben8 

`m4a` is a container format, I guess you mean `aac` in which case it should work with `-c aac`. Best

**Comment by MrPatben8** [comment]
@mmoussallam Ah yeah that could be it. In any case the help option is incorrect since it lists m4a as one of the encoder options.
Thanks for your help!
