### ISSUE TITLE
[Discussion] Spleeter setup with conder never finish

### ISSUE THREAD

**Issue by daslicht** [deezer/spleeter#294]
Hi,
today i tried installing spleeter under windows unsing conda.
After cloing spleeter and installing conda i get the following:
```
C:\dev> conda install -c conda-forge spleeter
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
```
and this never ends , any idea what could be wrong ?

**Comment by daslicht** [comment]
AV issue

**Comment by zfirefire** [comment]
Hi,

I do not understand coding at all but I am experiencing the same exact issue. 
I am on a MacBook Pro running Catalina 10.15. I don't know or see "Kapersky"

Any idea what my issue could be?

**Comment by flyingdisc** [comment]
I have exactly the same issue as @daslicht in Windows 10. 
I don't have any third party AV software, only the default Windows Defender.
So I didn't disable my Windows Defender. 
Instead I solved the problem by creating a new environment by referring to this conda issue [https://github.com/conda/conda/issues/9367](url), 
`conda create --name myenv`
`conda activate myenv`
Then the installation process run with no problem.

**Comment by kasparovnutter** [comment]
> I have exactly the same issue as @daslicht in Windows 10.
> I don't have any third party AV software, only the default Windows Defender.
> So I didn't disable my Windows Defender.
> Instead I solved the problem by creating a new environment by referring to this conda issue [https://github.com/conda/conda/issues/9367](url),
> `conda create --name myenv`
> `conda activate myenv`
> Then the installation process run with no problem.

this solved it on a W10 clean install, thanks!!
