### ISSUE TITLE
[Bug] name your bug

### ISSUE THREAD

**Issue by chrisgauthier9** [deezer/spleeter#297]
## Description

Unable to conda install Spleeter

## Step to reproduce

1. Installed using conda
2. Run as conda install -c conda-forge spleeter
3. Waited 30 minutes for code to run
4. Got error :

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - anaconda-navigator -> python[version='2.7.*|3.5.*|3.6.*|3.4.*']
  - anaconda-project -> python[version='3.4.*|>=3.8,<3.9.0a0']
  - anaconda==2020.02 -> python[version='3.6.10|3.7.6|3.8.1',build='h359304d_2|h359304d_1|h359304d_0']
  - astropy -> python=3.4
  - autopep8 -> python[version='>=3.8,<3.9.0a0']
  - backports.functools_lru_cache -> python[version='2.7.*|3.5.*|3.6.*|3.4.*|>=2.7,<2.8.0a0']
  - bkcharts -> python=3.4
  - bleach -> python[version='>=3.8,<3.9.0a0']
  - conda-env -> python[version='2.7.*|3.4.*|3.5.*']
  - diff-match-patch -> python[version='2.7.*|3.4.*|3.5.*|3.6.*']
  - gevent -> python=3.4
  - h5py -> python[version='<3']
  - html5lib -> python[version='3.4.*|>=3.8,<3.9.0a0']
  - intervaltree -> python[version='2.7.*|3.5.*|3.6.*']
  - jinja2 -> python[version='>=3.8,<3.9.0a0']
  - joblib -> python[version='>=3.8,<3.9.0a0']
  - jupyterlab -> python[version='>=3.8,<3.9.0a0']
  - jupyterlab_server -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0|3.4.*']
  - matplotlib -> python[version='3.6.*|<3']
  - mkl-service -> python[version='2.7.*|3.5.*|3.6.*|3.4.*']
  - mkl_fft -> python=3.4
  - mkl_random -> python=3.4
  - more-itertools -> python=3.4
  - navigator-updater -> python[version='2.7.*|3.5.*|3.6.*|>=3.8,<3.9.0a0|3.4.*']
  - networkx -> python[version='>=3.8,<3.9.0a0']
  - numba -> python=3.4
  - openpyxl -> python[version='>=3.8,<3.9.0a0']
  - packaging -> python[version='>=3.8,<3.9.0a0']
  - partd -> python[version='>=3.8,<3.9.0a0']
  - path -> python[version='>=2.7,<2.8.0a0']
  - path.py -> python[version='>=3.8,<3.9.0a0']
  - pathtools -> python[version='2.7.*|3.4.*|3.5.*|3.6.*']
  - prometheus_client -> python[version='>=3.8,<3.9.0a0']
  - pydocstyle -> python[version='>=3.8,<3.9.0a0']
  - pygments -> python[version='>=3.8,<3.9.0a0']
  - pytest-arraydiff -> python[version='2.7.*|3.5.*|3.6.*|3.4.*']
  - pytest-doctestplus -> python[version='2.7.*|3.5.*|3.6.*|>=3.8,<3.9.0a0|3.4.*']
  - pytest-openfiles -> python[version='2.7.*|3.5.*|3.6.*|>=3.8,<3.9.0a0|3.4.*']
  - pytest-remotedata -> python[version='2.7.*|3.5.*|3.6.*|3.4.*']
  - python-dateutil -> python[version='>=3.8,<3.9.0a0']
  - qtawesome -> python[version='>=3.8,<3.9.0a0']
  - seaborn -> python[version='>=3.8,<3.9.0a0']
  - sortedcollections -> python[version='>=3.8,<3.9.0a0']
  - sphinx -> python[version='>=3.8,<3.9.0a0']
  - sphinxcontrib-websupport -> python[version='>=3.8,<3.9.0a0']
  - testpath -> python[version='3.4.*|>=3.8,<3.9.0a0']
  - watchdog -> python[version='>=3.5,<3.6.0a0']
  - xlwings -> python=3.4
  - zict -> python[version='>=3.8,<3.9.0a0']

## Output

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS |
| Installation type | Conda |

## Additional context

Just updated to catalina

**Comment by stickyninja3** [comment]
What version of Python do you have installed
