### ISSUE TITLE
Train a model with only electric guitar?

### ISSUE THREAD

**Issue by brunobulgaron** [deezer/spleeter#3]
Hello there!
I would like to know if it's possible to train a model, but only using the electric guitar files on the MUSDB dataset?

Also, this Spleeter is awesome!

Thank you very much!

**Comment by yamtssfa** [comment]
Yes it would be great to be able to make guitar hero type tracks

**Comment by vandorb12** [comment]
I think this would be extremely difficult to pull off. Tambre and pitch of an electric guitar is so varied from genre to genre, as well as attack and sustain that it would not be parsed cleanly like piano or vocal. I could see this done for clean acoustic guitar, just not rock/heavily effected and distorted electric guitars.
But what do I know? I'm just a random person on the internet.

**Comment by romi1502** [comment]
The MUSDB dataset has no electric guitar track (only vocals, drums, bass and other).
Then, for training such a model, you first need to find a dataset with such isolated tracks.
As mentioned by @vandorb12, separating guitar tracks may be quite more challenging.

**Comment by brunobulgaron** [comment]
First of all, thank you all for replying. I really appreciate it!

If I were to train a model based on a dataset of isolated electric guitars, you guys have an idea of how many tracks I would have to use to get a good model to play around?
Thanks!

**Comment by romi1502** [comment]
@brunobulgaron,
I don't really have a answer for you. For training a deep learning model you usually need a lot (I don't really have a number for defining "a lot" :) ) of data, and you need to ensure that the data are diverse enough. 
Training a model with thousands samples of the same guitar played in the same amp by the same guitarist will probably results to a model that generalize much less than if it was trained on hundreds of samples various guitars played on various amp by various guitarists.
