### ISSUE TITLE
[Discussion] Train a model for narration

### ISSUE THREAD

**Issue by ysig** [deezer/spleeter#308]
Hi,

your package is fantastic, but I would like to use it in use-case that has to do with narration.
As so, in order for it to work better I would like to train a model between two big chunks of music and narration and eventually separate my target file.

As so I have three questions:
1. Can you provide instructions of how to train a model that are for custom-datasets?
2. How much time of audio samples is it needed, to have a good model?
3. Is there a tool that creates a synthetic dataset from two pure chunks of sound?

**Comment by junh1024** [comment]
https://github.com/deezer/spleeter/wiki/2.-Getting-started#train-model 
But opus already has algorithms to discern between speech & music ,  https://people.xiph.org/~xiphmont/demo/opus/demo3.shtml . Or you can use other metrics such as M/S comparison. But I think the default spleeter models do fine on separating music/narration as long as the music has no voice.
