### ISSUE TITLE
[Bug] no supported devices found for platform CUDA

### ISSUE THREAD

**Issue by mpaglia0** [deezer/spleeter#310]
## Description

When the command 'spleeter separate' is launched an error returns

## Step to reproduce

1. Installed using `sudo pip install spleeter`
2. Run as `spleeter separate -i FileName.ogg -p spleeter:4stems -o XXX`
3. Got error you can see here below

## Output

```bash
2020-04-01 11:14:44.334923: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
Annullato (core dump creato)
```

## Environment

| OS                | Linux |
| Distribution   |  OpenSUSE Leap 15.1  |
| Installation type | pip  |
| RAM available     | 16 GB  |
| Hardware spec     | GPU Nvidia GK107GL Quadro K420 / CPU Intel i5-4590 4x @ 3.30 GHz         |

## Additional context

Installed CUDA platform using nVIDIA rpm

**Comment by mmoussallam** [comment]
Hi @mpaglia0 

Using the GPU version of spleeter does not work well with `pip` install. Try the `conda` way or the dockers.
