### ISSUE TITLE
[Discussion]Spleeter only supports win64 bit system and cannot be used on Win32 bit system?

### ISSUE THREAD

**Issue by githublyff** [deezer/spleeter#317]
Spleeter only supports win64 bit system and cannot be used on Win32 bit system?

**Comment by mmoussallam** [comment]
Hi @githublyff 

Tensorflow is not supported in win32 machines https://github.com/tensorflow/tensorflow/issues/20362#issuecomment-401096205 so spleeter won't work either

**Comment by githublyff** [comment]
Thank you very much!

**Comment by githublyff** [comment]
@mmoussallam 
Thank you very much!
