### ISSUE TITLE
When to do cloning + virtualenv?

### ISSUE THREAD

**Issue by amadionix** [deezer/spleeter#318]
I installed the package using conda, and I am able to use it without any problem. 
I don't see any limitations to this.

But you also have a small paragraph "Development and testing" where you explain how to clone, create a virtual env and test. 
When would this be needed?

**Comment by romi1502** [comment]
Hi @amadionix,
you only need to clone the project if you want to do modification in it.
If you only want to use spleeter, install with conda is enough.
