### ISSUE TITLE
Issues when fine tune model

### ISSUE THREAD

**Issue by syxu828** [deezer/spleeter#32]
Hi, thanks for sharing your nice work!
I have a question when I tried to fine-tune your model on my dataset.
I feed your released pertained model to the estimator and trained the model with my dataset.
However, the model did not find the parameters for "../../Adam" in the checkpoint.
Do you have any idea about this problem ?

**Comment by alreadytaikeune** [comment]
Hi @syxu828 thanks for your interest and feedback.

For the sake of shipping lighter models (~ 3x lighter) we stripped out from the graph all the nodes that were useless for inference. That's the case of everything that concerns optimizers. This unfortunately precludes fine-tuning the models. We'll try to publish the full models as quickly as possible. This should not be an issue, keep an eye out!

**Comment by syxu828** [comment]
Thanks very much !

**Comment by johndpope** [comment]
@syxu828  please share insights into how to do fine tuning 


 I’m wondering if the instrument layers can go wider.
 Eg here’s the flute / trombone / high hat /   kick etc  layers. 
16 track / 32 / 64 / 128 / 1024 / etc

Use this orchestral model for this song
Use the rock n roll model for other

**Comment by romi1502** [comment]
We've just released complete models with optimizers parameters for fine tuning in this [release](https://github.com/deezer/spleeter/releases). There is no straightforward way to do fine tuning yet, but you can download manually the model and make the config json file point to it for doing fine tuning.

**Comment by syxu828** [comment]
Hi, I just want to see if we can have more performance improvements by introducing more 2stems/4stems dataset.
