### ISSUE TITLE
getting invalid syntax. please help

### ISSUE THREAD

**Issue by viveklal987** [deezer/spleeter#320]
Description

I was using SPYDER to use SPLITTER. But being new to programming field, I dont have much Idea on how to use splitter in SPYDER (single page code may be). That is why I tried colab and it worked perfect. But when I tried copy pasting the code from COLAB, I encountered an error.

Step to reproduce

Earlier I tried cloning git, conda install, But as i am new I do not know what it does as I was already having ANACOND NAVIGATOR

then 

simply copy pasted the codes from 
https://colab.research.google.com/github/deezer/spleeter/blob/master/spleeter.ipynb#scrollTo=afbcUSken16L
to my jupyter

Output

spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output
                    ^
SyntaxError: invalid syntax

 

 Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows  |
| Installation type | pip           |
| RAM available     |4gb and 2.91 gb available                     |
| Hardware spec     |CPU      |

## Additional context

installed spleeter by code "pip install spleeter"
and after running this "pip install ffmpeg"
Requirement already satisfied: ffmpeg in c:\anaconda3\lib\site-packages (1.4)
Note: you may need to restart the kernel to use updated packages.

**Comment by mmoussallam** [comment]
Hi @viveklal987 

the command `spleeter separate -i spleeter/audio_example.mp3 -p spleeter:2stems -o output` is not Python code (so it cannot be run in Spyder), it is intended to be run on your terminal (for instance in Anaconda Prompt)
