### ISSUE TITLE
[Discussion] Python 3.8 support?

### ISSUE THREAD

**Issue by Tantawi** [deezer/spleeter#325]
Ubuntu 20.04 LTS is around the corner and it will come pre-installed with Python 3.8. Is there any plans to support Python 3.8 in Spleeter?

Thanks.

**Comment by Faylixe** [comment]
Hi, we do not support Python 3.8 as the version of Tensorflow we are using do not currently support Python 3.8. You can use a virtual env, a Conda env, or a Docker image with Python 3.6 or 3.7 instead.
