### ISSUE TITLE
[Bug] spleeter not importing

### ISSUE THREAD

**Issue by S10MC2015** [deezer/spleeter#329]
## Description
spleeter not importing

## Step to reproduce
I have not a clue.

1. Installed using git clone then initialize venv
2. Run as ?. ran using "cmd /k "E:\Anaconda\Scripts\activate.bat && cd /d E:\"audio source seperation"\spleeter && python -m venv spleeterenv source spleeterenv/bin/acticate && cd /d E:\"audio source seperation"\spleeter && python.exe spleeter separate -i "C:\Users\User\Downloads\NA.mp3" -p spleeter:2stems -o E:\audio source seperation\spleeter\seperated\2stemstest -c mp3
3. Got `relative import with no known parent package` error

## Output
![image](https://user-images.githubusercontent.com/30575036/79345633-45396f00-7f29-11ea-8d3b-4d21c337470c.png)
I expect it to just work.

## Environment

|                              |                                                                        |
| ------------------- | ------------------------------------------------ |
| OS                        | Windows                                                        |
| Installation type   | other                                                              |
| RAM available      | 8gb                                                                |
| Hardware spec     | CPU amd a10 8700p (ik it is underpowered |
| ------------------- | ------------------------------------------------ |
|                              |                                                                        |

## Additional context
I am trying to get this to run from python. is there a better way to do it instead of calling a command prompt?
Also, the reason I am not using the conda-forge version is that it gets stuck on solving dependencies.

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/79347962-3d2efe80-7f2c-11ea-8c4c-8bc3b3e83391.png)
now the error has gotten better...

**Comment by mmoussallam** [comment]
HI @S10MC2015 

Can you just do the `pip install spleeter` instead of cloning ?
