### ISSUE TITLE
[Feature] Provide SavedModels of pretrained models

### ISSUE THREAD

**Issue by JeffreyCA** [deezer/spleeter#33]
Can you provide SavedModels of pretrained models (with the `saved_model.pb`file)?

**Comment by bboettcher3** [comment]
Related to this, do you have any plans to convert the model to a TensorflowJS model? Having a Javascript counterpart would be pretty useful for embedding Spleeter in other applications.

**Comment by JeffreyCA** [comment]
Update: SavedModels are already currrently being outputted to `/tmp/serving` after running a spleeter separation.

You can change this output directory via the `DEFAULT_EXPORT_DIRECTORY` constant in `estimator.py`.

**Comment by Faylixe** [comment]
> Related to this, do you have any plans to convert the model to a TensorflowJS model? Having a Javascript counterpart would be pretty useful for embedding Spleeter in other applications.

This will not happening from our side, the only migration we would consider at some point is porting library with TensorFlow 2. Plus I had checked a little bit before releasing and it would be very complicated as TensorFlow JS does not provide the range of functionality _Spleeter_ is currently using in _Python_ (`estimator` API to be more specific)

But if you are motivated feel free to explore, we would love having other language adoption from contributors.

> Update: SavedModels are already currrently being outputted to `/tmp/serving` after running a spleeter separation.
> 
> You can change this output directory via the `DEFAULT_EXPORT_DIRECTORY` constant in `estimator.py`.

I will close the issue since you seem to have figured out how but we will also upload those model on the release soon.

**Comment by shoegazerstella** [comment]
@JeffreyCA did you succeed in properly convert the SavedModes into tf.js?
I used the method explained [here](https://www.tensorflow.org/js/tutorials/conversion/import_saved_model) but had these warnings during conversion:

```
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_8/cond/FusedBatchNorm'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_20/cond/FusedBatchNorm_1'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_20/cond/FusedBatchNorm'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_9/cond/FusedBatchNorm_1'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_9/cond/FusedBatchNorm'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_21/cond/FusedBatchNorm_1'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_21/cond/FusedBatchNorm'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_10/cond/FusedBatchNorm_1'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_10/cond/FusedBatchNorm'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_22/cond/FusedBatchNorm_1'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_22/cond/FusedBatchNorm'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_11/cond/FusedBatchNorm_1'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_11/cond/FusedBatchNorm'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_23/cond/FusedBatchNorm_1'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'batch_normalization_23/cond/FusedBatchNorm'
```

**Comment by JeffreyCA** [comment]
No I did not try to do that
