### ISSUE TITLE
[Bug] Illegal Instruction (core dumped) // pkg_resources.DistributionNotFound: The 'tensorflow==1.15.2'

### ISSUE THREAD

**Issue by martobg10** [deezer/spleeter#330]
## Description

TensorFlow problem

## Step to reproduce

Installed using `pip install spleeter` (tried also `pip install spleeter==1.4.9`)
After that I type: `spleeter separate -i example.mp3 -p spleeter:2stems-16kHz -m -o output`

## Output

```bash
pkg_resources.DistributionNotFound: The 'tensorflow==1.15.2' distribution was not found and is required by spleeter
```

After that I type "pip install tensorflow==1.15.2", but the next error after `spleeter separate -i example.mp3 -p spleeter:2stems-16kHz -m -o output` is `Illegal Instruction (core dumped)`

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Arch Linux |
| Installation type | Pip |
| RAM available     | 6 GB |
| Hardware spec     | Intel Celeron 1000M |

## Additional context

With the latest Spleeter (1.5.1) I also received `Illegal Instruction (core dumped)`

**Comment by mmoussallam** [comment]
Hi @martobg10 

We made some changes in the installer lately, could you try again and let us know if this did not solve your issue. Thanks
