### ISSUE TITLE
[Bug] AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'

### ISSUE THREAD

**Issue by foxlet7** [deezer/spleeter#336]
1. Installed using `Conda`
2. Run as `Administrator`
3. Got `AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'` error
When i tried to >python -m spleeter separate -i Test.mp3 -o output
## Output

AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'
## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows  |
| Installation type | Conda /         |
| RAM available     | 8                           |
| Hardware spec     |  CPU  |

**Comment by mmoussallam** [comment]
hi @foxlet7 

We've just recently moved to Tensorflow2. I don't know exactly what your issue was about but I hope it's now fixed in the latest spleeter version
