### ISSUE TITLE
 Could not find a version that satisfies the requirement spleeter

### ISSUE THREAD

**Issue by Esmee-Zhang** [deezer/spleeter#337]
hi, I use macos and system version is 10.15.4. 
I use pip or pip3 both shows the error, 
ERROR: Could not find a version that satisfies the requirement spleeter (from versions: none)
ERROR: No matching distribution found for spleeter.
so... any solution? or it has to be done within conda?
thank you!

**Comment by mmoussallam** [comment]
Hi @Esmee-Zhang 

Please fill up a complete bug report with more details. Are you using python 3.8 ?

**Comment by PrinzNika** [comment]
i have the same issue, running Manjaro on kernel 5.6 with python 3.8 installed. othe packages upgrade without a problem using pip.

**Comment by Donavin97** [comment]
I am also getting the same error, using python3.8.2, could that be the issue, on 7.5 it worked.

**Comment by Faylixe** [comment]
We are not supporting Python 3.8, please downgrade or use a virtualenv.
