### ISSUE TITLE
[Bug] documentation doesn't state python 3 as prerequisite

### ISSUE THREAD

**Issue by LegalizeAdulthood** [deezer/spleeter#338]
## Description

Requires python 3 but doesn't state this anywhere

## Step to reproduce

> conda install -c conda-forge spleeter-gpu
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - spleeter-gpu -> python[version='>=3.6,<3.8']

Your python: python=2.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Package importlib_resources conflicts for:
spleeter-gpu -> importlib_resources
Package sqlite conflicts for:
python=2.7 -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.30.1,<4.0a0']
Package vc conflicts for:
python=2.7 -> vc=9
Package norbert conflicts for:
spleeter-gpu -> norbert
Package python_abi conflicts for:
python=2.7 -> python_abi=[build=*_cp27m]
Package vs2008_runtime conflicts for:
python=2.7 -> vs2008_runtime
Package pip conflicts for:
python=2.7 -> pip
Package ca-certificates conflicts for:
python=2.7 -> ca-certificates
Package setuptools conflicts for:
spleeter-gpu -> setuptools
Package ffmpeg-python conflicts for:
spleeter-gpu -> ffmpeg-python
Package tensorflow-gpu conflicts for:
spleeter-gpu -> tensorflow-gpu==1.14.0
Package requests conflicts for:
spleeter-gpu -> requests
Package pandas conflicts for:
spleeter-gpu -> pandas==0.25.1

1. Installed using `...`
2. Run as `...`
3. Got `...` error

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows / Linux / MacOS / other |
| Installation type | Conda / pip / other             |
| RAM available     | XGo                             |
| Hardware spec     | GPU / CPU / etc ...             |

**Comment by mmoussallam** [comment]
Hi @LegalizeAdulthood 

It's actually right there in the badges in the header of the README, because of our dependencies on tensorflow, we only support python 3.6 and 3.7 for now.
