### ISSUE TITLE
Why only half the spectrum?

### ISSUE THREAD

**Issue by tbwhsb88** [deezer/spleeter#34]
![image](https://user-images.githubusercontent.com/43901051/68283961-83e41700-00b7-11ea-9efa-1d63eb23df6c.png)

**Comment by zengjunjie1026** [comment]
I just want questioned。。

**Comment by alreadytaikeune** [comment]
Hello @tbwhsb88, please refer to [this issue](https://github.com/deezer/spleeter/issues/15) for an answer. It is a configuration parameter that is described [here](https://github.com/deezer/spleeter/wiki/3.-Models#configuration-file). We trained the models to work on signals with frequencies up to 11kHz (and same for the generated signals), but that is something you can change. This is why you observe that the spectral content above 11kHz is cut off.
