### ISSUE TITLE
yaml not found?

### ISSUE THREAD

**Issue by Bobski2000** [deezer/spleeter#340]
![Capture](https://user-images.githubusercontent.com/62856434/80232583-0dc77280-864d-11ea-9709-2f0545c55ae2.JPG)

the yaml file is not found. Ive installed using Anaconda and Github.
Ive even inistalled using python and both dont seem to have the yaml file.
Am i doing something wrong?
Using:
Windows 10 Pro
MSI X470
Ryzen 5 3600x
16gb Ram
Gigabyte GeForce 1050 ti OC Edition 4gb

## Step to reproduce

1. Installed using `...`
2. Run as `...`
3. Got `...` error

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows / Linux / MacOS / other |
| Installation type | Conda / pip / other             |
| RAM available     | XGo                             |
| Hardware spec     | GPU / CPU / etc ...             |

**Comment by Faylixe** [comment]
Please read the documentation for Conda installation. https://github.com/deezer/spleeter/wiki/1.-Installation#using-conda
