### ISSUE TITLE
Feature Request/Suggestion: Audience Track

### ISSUE THREAD

**Issue by kylemj89** [deezer/spleeter#350]
Possible to learn feedback from Audience such a cheers. whistles and clapping and isolate to its own track

**Comment by mmoussallam** [comment]
Hi @kylemj89 

if you training samples it's probably doable, at least for the clapping. Whistles and cheers will be hard to distinguish from vocals by the model though.

**Comment by ductrungktdn** [comment]
> Hi @kylemj89
> 
> if you training samples it's probably doable, at least for the clapping. Whistles and cheers will be hard to distinguish from vocals by the model though.

Hey, can you show me how to train for Spleeter? Can I do it on my own to get better result???
