### ISSUE TITLE
Non-AVX CPUs supported?

### ISSUE THREAD

**Issue by deton24** [deezer/spleeter#351]
I have an error:
_Failed to load the native TensorFlow runtime._

Using Spleeter, or executing any test tensorflow commands listed on their site (I'm using CPU version).

I found that the error can be caused by CPU without AVX. 
It is required since tensorflow 1.6, while Spleeter requires 1.15.2.
Source: https://github.com/tensorflow/tensorflow/issues/17807#issuecomment-377110939

Am I right, or are there any non-AVX users who successfully used Spleeter?

If not, can you add the information about AVX on your main page?
Or maybe some old Spleeter version was compatible with tensorflow 1.5?

Does GPU tensorflow version still requires AVX?

**Comment by mmoussallam** [comment]
Hi @deton24 

I think we never released a spleeter version functioning with a tensorflow version lower than 1.12. Given it's a hard dependency on our system I guess if you can't install a compatible version then you won't be able to use spleeter.

**Comment by deton24** [comment]
Then I'd be glad if you wrote on main page an information about
requirements for Spleeter:
- CPU with AVX instructions
- GTX 650 (for GPU tensorflow version)
Regards

śr., 29 kwi 2020, 16:02 użytkownik Moussallam <notifications@github.com>
napisał:
