### ISSUE TITLE
[Feature] implement lead vocal removal only

### ISSUE THREAD

**Issue by Donavin97** [deezer/spleeter#353]
## Description
I would like to know if it's possible to have a feature where you could  remove or extract only the lead vocals from songs, esencially creating a karaoke version of a song with the background vocals intact?

**Comment by romi1502** [comment]
Hi @Donavin97.
This is not possible at the moment as Spleeter models were trained to discriminate vocals (being lead or background) from other instruments.
If you have a dataset with background vocals separated from the lead vocals (for instance background vocals included in the accompaniment), you can try training a Spleeter model with it.
However, separating lead from background seems quite a challenge, and I won't be surprised that a model trained on such a dataset in the spleeter training fashion would struggle at doing such a task. Such task involves not only discriminating instruments but also discriminating instrument role in the song.
