### ISSUE TITLE
[Bug] cannot get a output

### ISSUE THREAD

**Issue by benciity** [deezer/spleeter#36]
## Description

<WARNING:tensorflow:From d:\anaconda\lib\site-packages\spleeter\model\functions\unet.py:29: The name tf.keras.initializers.he_uniform is deprecated. Please use tf.compat.v1.keras.initializers.he_uniform instead.
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.int32
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string
INFO:tensorflow:Loading audio b'spleeter/test.mp3' from 0.0 to 600.0>

## Step to reproduce
spleeter separate -i spleeter/test.mp3 -p spleeter:4stems -o output

## Output
tensorflow:Loading audio b'spleeter/test.mp3' from 0.0 to 600.0

## Environment
| OS                | Windows  |
| Installation type | Conda     |
| Hardware spec     | GPU      |

**Comment by Faylixe** [comment]
As seen in #29 we are currently testing a patch for those bug. A new version will be released by tomorrow.
