### ISSUE TITLE
[Bug] solving environment failed

### ISSUE THREAD

**Issue by JohnSmith2007** [deezer/spleeter#360]
## Description
I'm trying to install spleeter using conda, and it keeps giving me this error

## Step to reproduce

run "conda install -c conda-forge spleeter"

1. Installed using Conda
2. Run as conda install -c conda-forge spleeter
3. Got solving environment failed

## Output

```bash
(base) C:\Users\smcco>conda install -c conda-forge spleeter
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | Conda |
| RAM available     | 16GB |
| Hardware spec     | GPU: nVIDIA GeForce 1050 Ti, Intel UHD Graphics 630 / CPU: Intel i5-8300 |

## Additional context

No additional context

**Comment by mmoussallam** [comment]
Hi @JohnSmith2007 

Which version of Python are you using ? please note that 3.8 is not supported: https://github.com/deezer/spleeter/wiki/5.-FAQ#python-38

**Comment by sitnin** [comment]
Having same issue on Linux / 32Gb / 1660 Super / Python 2.7.17.

**Comment by Donavin97** [comment]
Hi there, I believe spleeter only works on Python3 versions, up to 3.7. Maybe upgrading your python to 3.7.5 could help, I’m currently running it and I have no issues.Best regards: Donavin.  From: Gregory SitninSent: Thursday, 07 May 2020 09:14To: deezer/spleeterCc: SubscribedSubject: Re: [deezer/spleeter] [Bug] solving environment failed (#360) Having same issue on Linux / 32Gb / 1660 Super / Python 2.7.17.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JohnSmith2007** [comment]
> Hi @JohnSmith2007
> 
> Which version of Python are you using ? please note that 3.8 is not supported: https://github.com/deezer/spleeter/wiki/5.-FAQ#python-38

I'm using Python 3.7.0

**Comment by mmoussallam** [comment]
@JohnSmith2007 

it seems to be an issue with your conda install, some people had the same issue and tried various solutions here : https://github.com/conda/conda/issues/9367

**Comment by RobVM1** [comment]
Did you resolve this issue installing spleeter?

**Comment by RobVM1** [comment]
There seems to be a major issue with Conda, so I ended up using pip to install spleeter, and that worked fie. I had to manually install ffmpeg and and the path to my environment variables, no big deal.

**Comment by JohnSmith2007** [comment]
> Did you resolve this issue installing spleeter?

Yeah, i just gave up on the program itself and instead went with the GUI that was made by boy1dr, 'cause i don't know jack shit about coding. So yay, now i don't need to enter enormous amounts of text into a CMD to get something to work. all i have to do now is click a few buttons.
