### ISSUE TITLE
[Bug] spleeter: error: unrecognized arguments: o- output

### ISSUE THREAD

**Issue by JohnSmith2007** [deezer/spleeter#361]
## Description

I just got Spleeter to install correctly without it giving me shit, but when i try to separate something it keeps giving me errors.

## Step to reproduce

run python -m spleeter separate -i (C:)\Users\smcco\Music\Power-Rangers_Time_Force_theme.mp3 -p spleeter:5stems o- output

1. Installed using Conda
2. Run as regular user
3. Got spleeter: error: unrecognized arguments: o- output

## Output

```bash
(base) C:\Users\smcco>python -m spleeter separate -i (C:)\Users\smcco\Music\Power-Rangers_Time_Force_theme.mp3 -p spleeter:5stems o- output
usage: spleeter [-h] {separate,train,evaluate} ...
spleeter: error: unrecognized arguments: o- output
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | Conda |
| RAM available     | 16GB |
| Hardware spec     | GPU: nVIDIA GeForce 1050 Ti, Intel UHD Graphics 630, CPU: Intel i5-8300 |

## Additional context

This program is fickle as shit

**Comment by mmoussallam** [comment]
Hi @JohnSmith2007 

you just have an error in your command syntax, it's `-o output` not `o-` Hope this helps

**Comment by shubham2407** [comment]
Hi @JohnSmith2007 

Your code is approximately correct but, you did a minor syntax error
i.e. it should be `-o output` instead of `o-output`

**Comment by JohnSmith2007** [comment]
> Hi @JohnSmith2007 
> 
> Your code is approximately correct but, you did a minor syntax error
> i.e. it should be `-o output` instead of `o-output`

Thanks for the explanation. However, I've long since stopped using the program via the command terminal. I now use the GUI version of this made by boy1dr.
