### ISSUE TITLE
[Bug] Spleeter has no output if filename ends with space

### ISSUE THREAD

**Issue by Christilut** [deezer/spleeter#363]
## Description

It seems that if the filename you are trying to split ends with a space, it won't save any results

## Step to reproduce

```
// Notice the space before .mp3
python -m spleeter separate -i "path/to/foo .mp3" -p spleeter:2stems-16kHz -o "path/to/result-dir"
```

## Output

Exits without error but has no files in the output dir.
The folder created by spleeter is there, eg `foo` but without trailing space. 

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows  |
| Installation type | Conda|

**Comment by mmoussallam** [comment]
Hi @Christilut 

Ending a filename with a space seems like a particularly evil thing to do :) 
That being said the path in your example is not valid in windows, did you try with a correct one ?

**Comment by Christilut** [comment]
Yeah, I'm using spleeter in my app with a GUI and normally everything works but files ending with a space don't work.
But my workaround for Windows is now that I'm copying the source file into a fixed filename and then work with that.
