### ISSUE TITLE
[Discussion] Command line works but not api? Spleeter-GPU

### ISSUE THREAD

**Issue by aidv** [deezer/spleeter#366]
This boggles my mind, has anyone had similar experience?

**Comment by mmoussallam** [comment]
@aidv  what do you mean by API does not work ?

**Comment by aidv** [comment]
I tried using the API in my python code, it eventually worked.

It worked well with the GPU too.

But now all of a sudden the GPU utilization stopped and Spleeter is using the CPU.

I changed absolutely nothing.

I just can't catch a break with this 🤦🏻‍♂️
