### ISSUE TITLE
[Discussion] Can't get Spleeter to install

### ISSUE THREAD

**Issue by Nipppi** [deezer/spleeter#369]
Hello everyone. I'm running on Windows 10, and no matter what I try, Spleeter will NOT install with anaconda. I followed a quick YouTube tutorial and followed the instructions. I installed Python, downloaded the Spleeter zip from here, and extracted it into a folder named "spleeter" directly in my C:\ directory. I've used the conda spleeter install command, and keep getting a file directory error. I've tried deleting the spleeter folder, and cloning it using the command on the spleeter page here, again keep getting the same errors. I tried everything on the main page here and no matter what I do, my anaconda prompt just reads errors. Can anyone help me out?

**Comment by mmoussallam** [comment]
Hi @Nipppi 

Please use the full issue (bug) template to help us help you. There is no way we can know what is going on without some basic info such as which error you get.

I'm closing this but feel free to open a bug issue and fill in all  fields.
