### ISSUE TITLE
[Bug] wget command is broken 

### ISSUE THREAD

**Issue by 973KarlJoy** [deezer/spleeter#374]
Unknow issue 

## Description
The "wget" command does not work. This is the error message : 'wget' command is not recognize as an internal, or external executable or command file ( it might be approximative however here is the french version of the message I have : 'wget' n'est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes.) 

## Step to reproduce
I just followed this tutorial, 
https://www.youtube.com/watch?v=iwUjwSCOOzs
I copied paste the first line of code on git hub, then pressed y 
then copy paste the secund line of code and here it gave me the bug 

1. Installed using `Anaconda Prompt`
2. Run as `...` I dont run as follow the tutorial i put below 
3. Got `...` error  it doesnt show the name of the error message 

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```

## Environment
Python Anaconda 

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows  10 |
| Installation type | Conda              |
| RAM available     | 16Go                             |
| Hardware spec     | AMD Ryzen 7 1700X / 4095 MoNVIDIA GeForce GTX 1070 Ti  / 447GB PH6-CE480-L2 (SATA (SSD))	
465GB Hitachi HGST HTS545050A7E680 (SATA) /Gigabyte Technology Co. Ltd. AX370-Gaming K5-CF (AM4)  ...             |

**Comment by mmoussallam** [comment]
Hi @973KarlJoy 

You need to install the `wget` utility if you want to run this part of the code, but it'll just download the sample audio file. You can download it directly or skip this line if you want to use spleeter on your own files
