### ISSUE TITLE
[Discussion] Output in FLAC or other formats

### ISSUE THREAD

**Issue by leops95** [deezer/spleeter#388]
Hi,
I was wondering if it is possible to to export the output files in other formats than WMA. I would be interested in having the files as FLAC, is it already possible to do so ?

I thank you in advance for your time and comprehension towards my request.

**Comment by leops95** [comment]
Whoops the files are in .wav and not .wma

**Comment by romi1502** [comment]
Hi @leops95,
yes it is possible to export as `flac` using the `-c`option, as mentioned in the help (`spleeter separate -h`): 
```
-c {wav,mp3,ogg,m4a,wma,flac}, --codec {wav,mp3,ogg,m4a,wma,flac}
                        Audio codec to be used for the separated output
```

**Comment by leops95** [comment]
Thanks it worked !
