### ISSUE TITLE
Can't Run Spleeter on Mac (Catalina)

### ISSUE THREAD

**Issue by ovrdrvn** [deezer/spleeter#402]
## Description

My installation has anaconda in my user directory and a spleeter directory at the same level. If I cd into the spleeter diretory and run the command with the python call, it finds spleeter but a new error comes: ModuleNotFoundError: No module named 'tensorflow'

## Step to reproduce

1. Installed using  git clone https://github.com/Deezer/spleeter
conda install -c conda-forge spleeter
2. Run as  myself
3. Got `...` ModuleNotFoundError: No module named 'tensorflow'

## Output

```bash
python -m spleeter separate -i bad.flac -p spleeter:4stems -o output
Traceback (most recent call last):
  File "/Users/xxxx/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/xxxx/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/xxxx/spleeter/spleeter/__main__.py", line 58, in <module>
    entrypoint()
  File "/Users/xxxx/spleeter/spleeter/__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "/Users/xxxx/spleeter/spleeter/__main__.py", line 36, in main
    enable_logging()
  File "/Users/xxxx/spleeter/spleeter/utils/logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "/Users/xxxx/spleeter/spleeter/utils/logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging


## Environment

<!-- Fill the following table -->

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                MacOS
| Installation type | Conda 
| RAM available     | 32 GB                          |
| Hardware spec     |2020 imac.             |

## Additional context

<!-- Add any other context about the problem here, references, cites, etc.. -->

**Comment by ovrdrvn** [comment]
Read requirements docs. Tensorflow 2 was insalled and it needed to be the older version so pip installed that. Then needed librosa and ffmpeg. Now I get this AttributeError: module 'ffmpeg' has no attribute '_run'

**Comment by ovrdrvn** [comment]
python -m spleeter separate -i bad.flac -p spleeter:4stems -o output
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named spleeter

**Comment by ovrdrvn** [comment]
Any update?

**Comment by Lyzah** [comment]
Solution in #432 by @themcclure helped for me...I also was trying to run on Mac(Catalina).

**Comment by romi1502** [comment]
There is indeed a problem with the anaconda install due to an internal dependency of tensorflow 1.15.  
See more details and workaround on this thread: [https://github.com/deezer/spleeter/issues/432#issuecomment-651234764](https://github.com/deezer/spleeter/issues/432#issuecomment-651234764)

**Comment by romi1502** [comment]
I updated the conda package.
The installation of spleeter with conda should be back to normal: 
```bash
conda install -c conda-forge spleeter
```
