### ISSUE TITLE
[Discussion] Will higher cpu cores and ram speed up spleeter?

### ISSUE THREAD

**Issue by Scylla2020** [deezer/spleeter#404]
I currently have a quad core with 8gb ram and it gets stuck with spleeter. Will using for example an 8 core cpu with 16gb ram make it faster or it wont make a difference?

**Comment by romi1502** [comment]
Having more RAM won't make spleeter faster but can help processing longer files.
Having a 8 core instead of a 4 core should make spleeter a bit faster (especially for the tensorflow part) but the best way to have a significative speed improvement is to process files on a (CUDA compatible) GPU instead of CPU.

**Comment by Scylla2020** [comment]
So approximately how much speedup could i possibly get be getting if I went with a RTX 2080 Ti gpu?

**Comment by aidv** [comment]
@Scylla2020 Yes. Very significant.

**Comment by Scylla2020** [comment]
Ok great thanks! I decided to just get an entry level, RX550 will see how that goes in a couple weeks

**Comment by Scylla2020** [comment]
How many cores are you using. Just seen spleeter docs say they used a Gtx 1080 with a 3min song taking 1.5sec on a 32 core cpu.

**Comment by aidv** [comment]
I have a few different machines, my main one has an i9-9900k (8 core)+ RTX2080.


These are my results

**Model**: 5 stem

**Subject**: ~3 min song

**GPU**
Model load time: 5.98 s
Song spleet time:  2.27 s

**CPU**
Model load time: 6.90 s
Song spleet time: 25.41 s

So the GPU gives about 10x faster processing.

For anyone out there that wants to do benchmarking, here's my script:

```
import sys
import os
import sys

import time

import warnings
warnings.filterwarnings('ignore')




start = time.time()
from spleeter.separator import Separator

count = 0
avg = 0

def doOnce():
    global count
    global avg

    count += 0
    print('Run ' + str(count))
    start = time.time()
    separator.separate_to_file('./1.mp3', destination='output', synchronous=True)
    end = time.time()
    elapsed = end - start
    print('Song completion time: ' + str(elapsed))
    avg += elapsed

if __name__ == '__main__':
    print('Benchmark')

    separator = Separator('spleeter:5stems')
    end = time.time()
    elapsed = end - start
    print('Model loading time: ' + str(elapsed))

    doOnce()
    doOnce()
    doOnce()
    doOnce()
    doOnce()
    
    avg = avg/5
    print('Avarage (sec): ' + str(avg))
```

Usage:

- Place a file called `1.mp3` in same folder as the script
- Open Anaconda shell
- Activate your environment
- Run `python -m benchmark`
- Wait until script executes

**Comment by Scylla2020** [comment]
Cool thanks for the detail!
