### ISSUE TITLE
Support for Python 3.8?

### ISSUE THREAD

**Issue by axfelix** [deezer/spleeter#405]
I notice the pip package is flagged as supporting <3.8, is this due to an incompatibility or has it just not been updated yet?

**Comment by romi1502** [comment]
As already mentioned in issue #325, the version of tensorflow (v1) used by spleeter has no support for python 3.8. We have to move to tensorflow v2 for supporting python 3.8. We'll do it eventually, but there is no plan to do it in the very short term.
