### ISSUE TITLE
[Question] Creating a own .csv

### ISSUE THREAD

**Issue by jusnim** [deezer/spleeter#409]
I want to use my own Dataset of .wav's to train spleeter and as far as i have noticed i need a .csv where the Dataset is described.
**My Question:** How do i create a .csv like given? [https://github.com/deezer/spleeter/blob/master/configs/musdb_train.csv](url)

**Comment by romi1502** [comment]
As mentioned in [this wiki section](https://github.com/deezer/spleeter/wiki/3.-Models#training-parameters), the csv must contains path to the audio files of the instrument you want to separate and to the mixture of all instruments (that can be the sum of all the others) and the duration of the file (that has to be the same for all these files). For instance, if you want to separate instrumental part from vocal, you'll need to have a csv with a `instrumental_path` column, a "vocal_path" column, a "mix_path" column and a "duration" column.
