### ISSUE TITLE
multiprocess.Pool is not recycled in separator

### ISSUE THREAD

**Issue by java641** [deezer/spleeter#414]
1. When I use Python Api like below
```
def separator_music(file_name):
    separator = Separator('spleeter:2stems')
    separator.separate_to_file(file_name, '/path/to/output/directory')

for file in files:
    separator_music(file)
```
2. Run as above code .
3. My computer is using up more and more memory. In the end,  the process is killed.
4. I found that multiprocess.Pool is not recycled in separator.
![image](https://user-images.githubusercontent.com/9145015/84021165-ac6a2180-a9b6-11ea-9ba5-f9f727a8e457.png)

**Comment by mmoussallam** [comment]
Hi @java641 

It's a duplicate from an issue that led to this #319. Just extract your `Separator` object construction out of the for loop and you should be fine. Otherwise, you're building many tensorflow graph which is completely unnecessary

**Comment by java641** [comment]
@marshalium Thanks!
