### ISSUE TITLE
[Bug] Broken links on the models wiki page

### ISSUE THREAD

**Issue by varenc** [deezer/spleeter#422]
## Description

The links to the base_config.json files for the pretrained models on [this wiki page](https://github.com/deezer/spleeter/wiki/3.-Models) are broken. They link to [wiki pages](https://github.com/deezer/spleeter/wiki/configs/2stems/base_config.json) that no longer exist. Took me a sec to find the real ones, but I believe those links could just be updated to point to the files [in this directory.](https://github.com/deezer/spleeter/tree/master/spleeter/resources)

Below that there's also a link to the releases on "github.deezerdev.com", which I assume should be update as well.  (though that one was less confusing)

## Step to reproduce

1. Visit the [models wiki page](https://github.com/deezer/spleeter/wiki/3.-Models)
2. Try to click the link to see a working example of a model json config.
3. Observe the confusing redirect to the wiki home page and weird permission warning from Github

**Comment by romi1502** [comment]
Thank you @varenc for pointing this out.
I've just fixed the links.
