### ISSUE TITLE
[Discussion] Why files outputted by splitter is three times bigger than initial file? 

### ISSUE THREAD

**Issue by Werter12** [deezer/spleeter#434]
Thanks for the awesome project guys. I am wondering why outputted files are much bigger than the initial file?
For example, my initial file was 9mb and the vocal I got after processing 36mb.

**Comment by romi1502** [comment]
Hi @Werter12,
There are several reasons for the output files having a bigger size than the input one's:
- the audio codec/bitrate is not the same: Spleeter outputs wav/PCM 16 bits with 44.1kHz sampling rate by default (so a bit rate of 1440kbps). So if your input is mp3 or aac @320kpbs, then the output files will be 4.5x bigger than the input. you can set the output audio codec with the `-c` option and the output audio bitrate with the `-b` option.
- the input file is mono: then Spleeter will actually start by converting it to stereo, process the file as stereo and output stereo files (so 2x bigger than input).

**Comment by Werter12** [comment]
@romi1502 Thanks!
