### ISSUE TITLE
[Discussion] How many batches are supported to one command?

### ISSUE THREAD

**Issue by cxy200927099** [deezer/spleeter#44]
what is the max batch size with a single call to separate?

I just want to get vocals file , how to set the output vocals name and output directory?

thank you

**Comment by mmoussallam** [comment]
Answer probably depends on your shell settings.

If you want to customize the outputs and process batches of file I recommend  you use the [python API](https://github.com/deezer/spleeter/wiki/4.-API-Reference).

**Comment by cxy200927099** [comment]
> Answer probably depends on your shell settings.
> 
> If you want to customize the outputs and process batches of file I recommend you use the [python API](https://github.com/deezer/spleeter/wiki/4.-API-Reference).

I read the python api, the batch process as below:
```python
def batch_extract_by_spleeter(input_path, out_path):
    file_list = sorted(os.listdir(input_path))

    # Using embedded configuration.
    separator = Separator('spleeter:2stems')

    # Batch separation export.
    for _file in file_list:
        _abs_file = os.path.join(input_path, _file)
        separator.separate_to_file(_abs_file, out_path, synchronous=False)

    # Wait for batch to finish.
    separator.join()
```
I could not find the method to just set the the output voical file path, the parameter **destination**  of the  separate_to_file function is a directory
