### ISSUE TITLE
Is the requirements.txt missing on master?

### ISSUE THREAD

**Issue by DocRace** [deezer/spleeter#447]
There is no  "requirements.txt" under master branch.

**Comment by Faylixe** [comment]
Yes, we recently moved our CI from CircleCI to Github action and we removed the `requirements.txt` file during the process, leaving the dependency listing into the `setup.py`. We will maybe restore requirements later and integrate it directly into the packaging. Feel free to submit a pull request if you need it quickly :)

**Comment by dmd** [comment]
`readme.md` still refers to `requirements.txt`
