### ISSUE TITLE
[Bug] build llvmlite error

### ISSUE THREAD

**Issue by stefanschauer** [deezer/spleeter#451]
## Description

I am trying to install spleeter according to the instruction. when runing the pip command I get an error message telling me that llvmlite building does not work.

## Step to reproduce

0. python3 -m venv spleeterenv && source spleeterenv/bin/activate
1. python3 -m pip install -r requirements.txt && pip install pytest pytest-xdist
2. Got build llvmlite error

## Output

Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ryc433tr/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ryc433tr/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-9kran4na
       cwd: /tmp/pip-install-ryc433tr/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-ryc433tr/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-ryc433tr/llvmlite/ffi/build.py", line 106, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.5/subprocess.py", line 693, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
      raise child_exception_type(errno_num, err_msg)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-ryc433tr/llvmlite/ffi/build.py", line 192, in <module>
      main()
    File "/tmp/pip-install-ryc433tr/llvmlite/ffi/build.py", line 182, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-ryc433tr/llvmlite/ffi/build.py", line 109, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: decorator, audioread, llvmlite, numba, resampy, librosa
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ryc433tr/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ryc433tr/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vt2kp1uy/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mister/.local/include/python3.5m/llvmlite
         cwd: /tmp/pip-install-ryc433tr/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-ryc433tr/llvmlite/llvmlite/_version.py {'full': 'aa11b129c0b55973067422397821ae6d44fa5e70', 'version': '0.32.1'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-ryc433tr/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-ryc433tr/llvmlite/ffi/build.py", line 106, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 693, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-ryc433tr/llvmlite/ffi/build.py", line 192, in <module>
        main()
      File "/tmp/pip-install-ryc433tr/llvmlite/ffi/build.py", line 182, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-ryc433tr/llvmlite/ffi/build.py", line 109, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ryc433tr/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ryc433tr/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vt2kp1uy/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Linux / Ubuntu |
| Installation type | pip  python3         |

**Comment by csukuangfj** [comment]
@stefanschauer 
you have to install llvm first. Since your OS is Ubuntu, the following command should be helpful

```bash
sudo apt-get install llvm-8
```

You may need to create a symlink for `llvm-config`

```
sudo ln -s /usr/bin/llvm-config-8 /usr/bin/llvm-config
```

Note that at least llvm 8.0.0 is needed. The default llvm version from `sudo apt-get intall llvm` may not work.

**Comment by mmoussallam** [comment]
Thanks @csukuangfj 

@stefanschauer  did it solve your problem ?
