### ISSUE TITLE
"ffmpeg binary not found" error

### ISSUE THREAD

**Issue by dm0n-hue** [deezer/spleeter#456]
I've downloaded ffmpeg onto my mac and followed the installation steps but for some reason I get this error in my terminal window.
Would appreciate it if I could have some help with this. Thank you.

**Comment by xshone** [comment]
Try to add the path of ffmpeg in the system environment. Hope it will be helpful for you.

**Comment by mmoussallam** [comment]
Hi @dm0n-hue 

indeed, youf ffmpeg install is not completed if the executable cannot be found. [This thead](https://superuser.com/questions/624561/install-ffmpeg-on-os-x) show some way to have a working installation on mac. good luck
