### ISSUE TITLE
Results on MUSDB Training

### ISSUE THREAD

**Issue by RaW-Git** [deezer/spleeter#459]
Hello there,

I'm currently writing my Master Thesis on Audio Source Separation and I'm using your U-Net implementation as a Baseline for my approach towards it. I reimplemented parts of your framework and the U-Net in Tensorflow 2.0 and currently running Trainings on the MUSDB18 Dataset. The Architektur and the Training Hyperparameters are very similar to what you provided in the MUSDB Config. With this implementation I'm reaching an SDR of around 4.9dB for the Vocals and for the other Instruments only around 3 - 4dB.
Could you provide me your Evaluation results when only using MUSDB Data for the training? I have only limited amount of computational power and it would help me a lot to figure out if the difference in the results are caused by the Dataset Size or if my Hyperparameters are still not tuned well.

Best regards,
Ramón

**Comment by mmoussallam** [comment]
Hi @RaW-Git 

You'll find them in the wiki: https://github.com/deezer/spleeter/wiki/Separation-Performances#training-on-musdb
