### ISSUE TITLE
Support Python 3.8 with Pip

### ISSUE THREAD

**Issue by declension** [deezer/spleeter#460]
## Description

Allow installation of the pip package with Python 3.8 (e.g. all latest Ubuntu installations)
 
## Additional information
![Screenshot_2020-07-13 spleeter](https://user-images.githubusercontent.com/3322808/87351188-f8c5f580-c550-11ea-8ae0-330c3a841da5.png)

Currently doesn't: https://pypi.org/project/spleeter/ shows `Requires: Python >=3.6, <3.8`

**Comment by declension** [comment]
See related #295

**Comment by mmoussallam** [comment]
Hi @declension 

Our issue with Python 3.8 is because of the `tensorflow` dependency. We're currently working on a port to TF2 to fix that.

**Comment by declension** [comment]
Thanks @mmoussallam - I followed it through the process and realised exactly that.  Good luck!
