### ISSUE TITLE
Unresolved conflicts installing to OSX 10.13.6 ... Is 10.15 required?

### ISSUE THREAD

**Issue by jimfisheye** [deezer/spleeter#463]
## Description

Installing to OSX 10.13.6 results in a number of unresolved conflicts and the installation fails.

## Step to reproduce

1. Verified Python3 installed. (v3.8.3)
2. Installed Anaconda3
3. Installed spleeter using Conda with the command "conda install -c conda-forge spleeter"
4. A number of unresolved conflicts were listed and spleeter was not installed (or the install was too incomplete to do anything)
5. Tried both GUI and command line versions of Anaconda. Same results. The Conda install appears OK and produces no errors itself.

## Output

enter: spleeter separate -h
-bash: spleeter: command not found

enter: python -m spleeter separate -h
/Users/jn/anaconda3/bin/python: No module named spleeter

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS 10.13.6|
| Installation type | Conda           |
| RAM available     | 16GB                             |
| Hardware spec     | Intel HD Graphics 3000 512 MB / 2.5 GHz Intel Core i7 /           |

## Additional context

I don't really have a preference for OSX version if it might require difficult installation.
What version of OSX will allow for the simple install in a couple steps as noted?

**Comment by romi1502** [comment]
Spleeter should work on 10.13.6. I currently have no trouble installing and running it on 10.14.6.
It seems that you started from a python 3.8 version and spleeter is not compatible with python 3.8 yet (because of some dependencies not being compatible). Have you tried with python 3.7? you can use a conda environnement to do this:
```bash
conda create -n py37 python=3.7
conda activate py37
conda install -c conda-forge spleeter
```
In case it still does not work, could you provide the log for the unresolved conflicts during the conda install?

**Comment by jimfisheye** [comment]
There it is!
Thanks romi1502!

I was following the instructions [here](https://github.com/deezer/spleeter/wiki/1.-Installation#using-conda).
Which led to Conda instructions [here](https://docs.anaconda.com/anaconda/install/mac-os/).
It came across like "Install for the version of Python you currently happen to have."

I was probably going to try OSX 10.15 before coming back around and trying Python v2... so, thank you!

**Comment by jimfisheye** [comment]
I spoke too soon...

I was able to run the command: spleeter separate -h
Trying an actual test with the stock mp3 file, however, got this:
ERROR:spleeter:An error occurs with ffprobe

ffprobe version 4.3 Copyright (c) 2007-2020 the FFmpeg developers
  built with clang version 9.0.1
  configuration: --prefix=/Users/jn/anaconda3/envs/py37 --cc=x86_64-apple-darwin13.4.0-clang --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mp3 @ 0x7fbd62809800] Format mp3 detected only with low score of 1, misdetection possible!
[mp3 @ 0x7fbd62809800] Failed to read frame size: Could not seek to 1163.
audio_example.mp3: Invalid argument

**Comment by romi1502** [comment]
This seems to be an issue with the audio files that seems not to be properly recognized by ffmpeg. Can you try with other files?

**Comment by jimfisheye** [comment]
My bad. I should have checked the example file I suppose?
Spleeter is giving output. 
I suppose I'll have to play around beyond the defaults. I have the warbled wind chime extravaganza that I've come to expect from these kinds of things. But it's working!

Thanks again for your help!
