### ISSUE TITLE
[Discussion] conda install takes forever to solve dependencies

### ISSUE THREAD

**Issue by basicvisual** [deezer/spleeter#470]
Hi is there a special version of conda to be used. I seem to install  packages via conda , in ubuntu 18.04 but 
`conda install -c conda-forge spleeter` takes hours to solve dependencies and fails. I was wondering if anyone was facing the same issue ? (ubuntu 18.04 OS)

**Comment by darrenwinslow** [comment]
I have the same issue on macOS (10.15.6) and it still fails.
