### ISSUE TITLE
[Bug] High-pitched artifact at very beginning of separated track (v1.5.4)

### ISSUE THREAD

**Issue by JeffreyCA** [deezer/spleeter#476]
## Step to reproduce

1. Install latest Spleeter version (1.5.4):  `pip install spleeter`
2. Run following Python script to separate 'other' component of `bluesky.mp3`:

```py
from spleeter import *
from spleeter.utils import *
from spleeter.audio.adapter import get_default_audio_adapter
from spleeter.separator import Separator

separator = Separator('spleeter:4stems', stft_backend='librosa', multiprocess=False)
audio_adapter = get_default_audio_adapter()
waveform, _ = audio_adapter.load('bluesky.mp3', sample_rate=44100)
prediction = separator.separate(waveform)
out = prediction['other']

audio_adapter.save('/path/to/output.mp3', out, 44100, 'mp3', '256k')

```

There's a high-pitched artifact at the very beginning of the output track.  
**The problem only occurs when you set the `stft_backend` to `librosa`.**

I attached a ZIP including the input and output files: [tracks.zip](https://github.com/deezer/spleeter/files/5093723/tracks.zip)

I initially thought https://github.com/deezer/spleeter/pull/426 was supposed to fix this, but I'm already on v1.5.4 and it's still happening.

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | macOS |
| Installation type | pip             |
| RAM available     | 16 GB                           |
| Hardware spec     | 2.2 GHz Quad-Core Intel Core i7 |

**Comment by JeffreyCA** [comment]
@romi1502 @mmoussallam Any idea why this may be happening? Is it related to https://github.com/deezer/spleeter/pull/426?

**Comment by JeffreyCA** [comment]
@romi1502 Do you know when the next release will be out?

**Comment by mmoussallam** [comment]
Hi @JeffreyCA 

Version 2 has been released and it should have solved this. Let us know if you still encounter the issue.
