### ISSUE TITLE
Mp3 Format separate_to_file method API documentation

### ISSUE THREAD

**Issue by Gnai** [deezer/spleeter#479]
hello,
i am trying to separate my tracks and export the stems to .mp3 instead of .wav with the separate_to_file method.
Anyone figured it out?

**Comment by romi1502** [comment]
You have a `codec` option in the `separate_to_file` method that makes it possible (and a `bitrate` option to set the bitrate):
```bash
from spleeter.separator import Separator
separator = Separator('spleeter:2stems')
separator.separate_to_file("/path/to/input/audio/file.wav", "/output/path", codec="mp3", bitrate="128k")
```
