### ISSUE TITLE
[Discussion] How to get around ERROR: Package 'spleeter' requires a different Python: 3.8.2 not in '>=3.6, <3.8'?

### ISSUE THREAD

**Issue by CHJ85** [deezer/spleeter#489]
I tried installing this again since it's been awhile.
But I am still getting this error.
"ERROR: Package 'spleeter' requires a different Python: 3.8.2 not in '>=3.6, <3.8'"
How do I get around this? I'm on Ubuntu 20.04 btw.

**Comment by romi1502** [comment]
Spleeter is not compatible with python 3.8 yet (as tensorflow 1.15 which is a needed dependency is also not compatible).
We should release a compatible version soon. In the meantime, you have to use python 3.6 or 3.7. 
The easiest way to do this without messing things in your main python installation is to use a virtual env in conda:
```python
conda create -n py37 python=3.7
conda activate 3.7
pip install spleeter
```

**Comment by CHJ85** [comment]
I tried to install conda and do it that way, but it wouldn't work.
I'll just wait for the next version then.
Thanks for your response.

**Comment by expectopatronum** [comment]
It should be:
```python
conda create -n py37 python=3.7
conda activate py37
pip install spleeter
```

**Comment by CHJ85** [comment]
Right. I cannot find conda in the package manager, so I'm not sure what version ofconda I need to install.
I tried the version from pip but that one wasn't compatible.
So like I said, I'll be waiting for the next version of Spleeter.
