### ISSUE TITLE
Hello,I try to install cutadapt however no one is compatible with my python version (python 3.8). 

### ISSUE THREAD

**Issue by Janett7** [deezer/spleeter#491]
I try to install cutadapt however no one is compatible with my python version (python 3.8). Message from the console:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed   

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - cutadapt -> python=2.7

Your python: python=3.8

i AM USING CODES FROM https://cutadapt.readthedocs.io/en/stable/guide.html

Also I tried several verions from conda. https://anaconda.org/search?q=platform%3Aosx-64+cutadapt&sort=ndownloads&sort_order=1&reverse=true

Someone has an idea?

**Comment by Janett7** [comment]
> I try to install cutadapt however no one is compatible with my python version (python 3.8). Message from the console:
> 
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: /
> Found conflicts! Looking for incompatible packages.
> This can take several minutes. Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
> 
> Specifications:
> 
> * cutadapt -> python=2.7
> 
> Your python: python=3.8
> 
> i AM USING CODES FROM https://cutadapt.readthedocs.io/en/stable/guide.html
> 
> Also I tried several verions from conda. https://anaconda.org/search?q=platform%3Aosx-64+cutadapt&sort=ndownloads&sort_order=1&reverse=true
> 
> Someone has an idea?
I resolved already!

**Comment by expectopatronum** [comment]
As far as I know spleeter is only compatible with Python 3.6 and 3.7 (as you can see from the badge in the README). Maybe using Python 3.7 will solve your problem?

**Comment by makecloud** [comment]
> As far as I know spleeter is only compatible with Python 3.6 and 3.7 (as you can see from the badge in the README and mentioned [here](https://github.com/deezer/spleeter/issues/489#issuecomment-688082381)). Maybe using Python 3.7 will solve your problem?

is there any problems to downgrade my python under conda have been installed?

**Comment by romi1502** [comment]
This issue seems to be solved. Besides, the last version of spleeter can run on python 3.8. So I close the issue.
