### ISSUE TITLE
[Bug] No embedded configuration 2stem found after pip installed

### ISSUE THREAD

**Issue by UnknownObject000** [deezer/spleeter#492]
#450  Description

I have installed spleeter using pip. When I running the spleeter command on powershell, the error poped up.

## Step to reproduce

1. Installed using `pip install spleeter`
2. Run as `spleeter separate -i .\audio_example.mp3 -p spleeter:2stem -o .\`
3. Got `spleeter:No embedded configuration 2stem found` error

## Output

```bash
PS F:\Spleeter\spleeter> spleeter separate -i .\audio_example.mp3 -p spleeter:2stem -o .\   
ERROR:spleeter:No embedded configuration 2stem found
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 20H2 |
| Installation type | pip             |
| RAM available     | 8.7GB  |
| Hardware spec     | GPU GTX1050 / CPU Intel Core i7-8750H           |

## Additional context

Reinstall does not help.

**Comment by UnknownObject000** [comment]
More info: 

Python Version: 3.7.4
pip version: 20.1

**Comment by romi1502** [comment]
The configuration is `spleeter:2stems`, not `spleeter:2stem`.
