### ISSUE TITLE
support for new python versions

### ISSUE THREAD

**Issue by hossy13** [deezer/spleeter#494]
hi
why its not compatible with new python versions like 3.8 or 3.9

**Comment by makecloud** [comment]
i caught the same problem with you.  my macbook default installed python3.8 since i buy it，but this spleeter require lower of 3.8？oh my god，let me downgrade for this ? so stupid

**Comment by hossy13** [comment]
@makecloud 
yea i created another virtualenv
and interact with spleeter by command line

**Comment by romi1502** [comment]
Python 3.8 support was added in the last release of spleeter. Let us know if you encounter issues with it.
