### ISSUE TITLE
[Discussion] Can I reduce the file's size?

### ISSUE THREAD

**Issue by babbluesy** [deezer/spleeter#497]
The size of the file increases by more than 10 times after the conversion. Can I solve this?

**Comment by romi1502** [comment]
I'm not sure of your problem, but my guess is that your input 128k mp3 or so to spleeter and it outputs wav (default behaviour).
As mentioned in the help of spleeter (`spleeter separate -h`), you can export files to other formats and set the bitrate with the following options:
```
  -c {wav,mp3,ogg,m4a,wma,flac}, --codec {wav,mp3,ogg,m4a,wma,flac}
                        Audio codec to be used for the separated output
  -b BITRATE, --birate BITRATE
                        Audio bitrate to be used for the separated output
```
So the following command should produce much smaller files:
```bash
spleeter separate -i audio_example.mp3 -c mp3 -b 128k
```

**Comment by pranavansp** [comment]
How to use this on Python API Level?

**Comment by redbar0n** [comment]
I recently contributed to this wrapper script that might help manage spleeter both RAM and HDD space concerns in general: https://github.com/amo13/spleeter-wrapper
