### ISSUE TITLE
'spleeter' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by EdjeElectronics** [deezer/spleeter#5]
I followed the [Quick Start](https://github.com/deezer/spleeter#quick-start) directions, but I get this error when I try using spleeter.  Did I miss something? Do I need to manually add spleeter to my system path? I'm on Windows 10.

![spleeter_error2](https://user-images.githubusercontent.com/26154245/68078988-fba7fe00-fda6-11e9-9366-c375c921aa89.png)

**Comment by mmoussallam** [comment]
Hi Evan,

Thanks, we'll look into it. The `spleeter` shortcut has been tested on Linux/MacOS but not on Windows yet.
In the mean time you should be able to use the longer version `python -m spleeter separate` 

Let us know if you still have issues.

**Comment by Faylixe** [comment]
Did you tried to run `spleeter.exe` instead ? Windows haven't been tested a lot, but command line script is generated by `setuptools` and thus should create a valid *Windows* executable.

**Comment by adizhol** [comment]
pip install pyssl,
then install the rest of the pip requirements from yaml file

**Comment by nimbleness** [comment]
I'm having the same issue

**Comment by Faylixe** [comment]
The problem here is that your Conda environment installation was not ok from the beginning.

> Running setup.py install for simplejson: finished with status 'error'

Since your Conda install meet some error then `Spleeter` was installed leading you to the error you found :).

**Comment by krauspe** [comment]
I was able to complete conda install command without erros, but nevertheless I got

`(spleeter-gpu) E:\DATA\PROG\spleeter>python -m spleeter separate -i audio_example.mp3 -p spleeter:2stems -o output
Traceback (most recent call last):
  File "D:\Programme\Anaconda3\envs\spleeter-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Programme\Anaconda3\envs\spleeter-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\DATA\PROG\spleeter\spleeter\__main__.py", line 51, in <module>
    entrypoint()
  File "E:\DATA\PROG\spleeter\spleeter\__main__.py", line 47, in entrypoint
    main(sys.argv)
  File "E:\DATA\PROG\spleeter\spleeter\__main__.py", line 41, in main
    entrypoint(arguments, params)
  File "E:\DATA\PROG\spleeter\spleeter\commands\separate.py", line 160, in entrypoint
    audio_adapter = get_audio_adapter(arguments.audio_adapter)
  File "E:\DATA\PROG\spleeter\spleeter\utils\audio\adapter.py", line 136, in get_audio_adapter
    return get_default_audio_adapter()
  File "E:\DATA\PROG\spleeter\spleeter\utils\audio\adapter.py", line 124, in get_default_audio_adapter
    from .ffmpeg import FFMPEGProcessAudioAdapter
  File "E:\DATA\PROG\spleeter\spleeter\utils\audio\ffmpeg.py", line 14, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'`
-------------

I made sure ffmpeg is actually installed !

**Comment by Jeslandor** [comment]
> Did you tried to run `spleeter.exe` instead ? Windows haven't been tested a lot, but command line script is generated by `setuptools` and thus should create a valid _Windows_ executable.

I am having this same exact issue on "Windows" (on "Linux" works great) and I am afraid I looked over (using "Total Commander" search and "Everything" tools) for a "spleeter.exe" or even a "spleeter" file to run and it was nowhere to be found. So apparently for some reason it is not being created at all.

With that said, using "python -m spleeter" command instead works perfectly here. So a big thanks for the tip to "mmoussallam"

**Comment by ez-dev** [comment]
Open Anaconda command prompt "as administrator" (It's important)

then
conda install -c conda-forge spleeter

then 
python -m spleeter .......................

this way worked for me like a charm and thanks the team for the fantastic job!

**Comment by quinnzaballa** [comment]
Download Python on [Python](Python.org) and check Add Python to PATH For some reason you will need to manually add it...
