### ISSUE TITLE
Struggling on windows

### ISSUE THREAD

**Issue by waveydavey0** [deezer/spleeter#50]
Not a python user generally, so please excuse ignorance. Also, not posted as a bug, as most likely my error. I'm on a windows 10 box. 
Installed miniconda ok, and did the 

git clone https://github.com/deezer/spleeter
conda env create -f spleeter/conda/spleeter-cpu.yaml
conda activate spleeter-cpu

steps all ok. Last step changes prompt to (spleeter-cpu) d:\mypath
but then when I do

spleeter separate -h

I get 
'spleeter' is not recognized as an internal or external command,
operable program or batch file.

Any advice please ?

**Comment by redapple** [comment]
Can you try running
`python -m spleeter separate -h` ?

If that doesn't work, you probablyy need to go through [the installation docs](https://github.com/deezer/spleeter/wiki/1.-Installation) again.

**Comment by mmoussallam** [comment]
It seems similar to #51  and probably means you need to install Anaconda.

**Comment by deewhy** [comment]
I have Anaconda installed and I've tried running `python -m spleeter separate -h`, but I'm getting 'No module named spleeter.__main__; 'spleeter' is a package and cannot be directly executed'

**Comment by krauspe** [comment]
I have the same problem , and I have anaconda3 installation
