### ISSUE TITLE
[Bug] README Grammar Issues

### ISSUE THREAD

**Issue by ttepatti** [deezer/spleeter#500]
## Description

The README.md file contains grammatical errors

## Step to reproduce

Open the README.md file

## Output

```
Spleeter is the Deezer source separation library with pretrained models written in Python and uses Tensorflow. It makes it easy to train source separation model (assuming you have a dataset of isolated sources), and provides already trained state of the art model for performing various flavour of separation :
```

## Additional context

A sample of how I would fix the above paragraph:

```
Spleeter is a source separation library written in Python and utilizing Tensorflow, created by Deezer. It makes it easy to train source separation models (assuming you have a dataset of isolated sources), and provides already-trained state-of-the-art models for performing various flavours of separation.
```

If it's okay, I'd be happy to fix these issues and file a PR. I didn't want to blankly file one without consulting the development community around Spleeter, because I know many open source projects are dealing with a lot of Hacktoberfest "I fixed the docs" PR spam right now. That being said, I think these are some legitimate grammar issues that could use updating here :-)

Thanks!

**Comment by refekt** [comment]
I'll help
