### ISSUE TITLE
IF I can separate only one stem from stems?

### ISSUE THREAD

**Issue by hacker-lin** [deezer/spleeter#506]
I used 2stems/4stems/5stems，I can get  [bass, drums, other, piano, vocals]

is there a way to only drop one , and keep the rest as the whole music? 
eg:  I like a song,  but I dont like the drums in the song,   I only want to drop the drums from the song ...

or

how can I concat these "[bass, drums, other, piano, vocals]"  by myself

thx !

**Comment by Mixerrog** [comment]
To remove a stem, just invert the stem & add it back to the original file (must be the same type of file). This will subtract the stem from the original file.

Rog


     On Sunday, October 11, 2020, 11:11:32 PM CDT, Cython_lin <notifications@github.com> wrote:  
 
 


I used 2stems/4stems/5stems，I can get [bass, drums, other, piano, vocals]

is there a way to only drop one , and keep the rest as the whole music?
eg: I like a song, but I dont like the drums in the song, I only want to drop the drums from the song ...

or

how can I concat these "[bass, drums, other, piano, vocals]" by myself

thx !

**Comment by RufusMall** [comment]
Yeah like the above poster said, invert the stem.

Or you could also use something like FFMPEG to combine the stems you do want:

I THINK something this link below is what you want (I haven't tried it myself)
https://stackoverflow.com/questions/14498539/how-to-overlay-downmix-two-audio-files-using-ffmpeg

**Comment by hacker-lin** [comment]
@Mixerrog I cant understand the way, thanks for u answer !

and 

I use @RufusMall's way, It works 
> I THINK something this link below is what you want (I haven't tried it myself)
> https://stackoverflow.com/questions/14498539/how-to-overlay-downmix-two-audio-files-using-ffmpeg

(
  I just listen to some music for myself.
  Electronic drums in some light music sounds noisy.
  so I just drop it from light music.
)
