### ISSUE TITLE
[Discussion] Separation based on chunk by chunk input waveform data does not seem to work!

### ISSUE THREAD

**Issue by racko1** [deezer/spleeter#507]
Hi,
I am trying to do 2stems separation by using "separator.separate(waveform)" API. 
When i call this API with complete waveform of input wav file, 2stems separation is perfect (output vocals.wav & accompaniment.wav proper).
But if i call this API with 4096 samples of same input wav file in a loop till end of file and accumulate the predicted vocals & accompaniment outputs, the vocals output found to contain lot of music (meaning separation is not proper).

#Code snippet
from spleeter.audio.adapter import get_default_audio_adapter

audio_loader = get_default_audio_adapter()
sample_rate = 44100
waveform, _ = audio_loader.load('/path/to/audio/file', sample_rate=sample_rate)

buffer = 4096
samples_total = len(waveform)
samples_wrote = 0

while samples_wrote < samples_total:
	#check if the buffer is not exceeding total samples
	if buffer > (samples_total - samples_wrote):
		buffer = samples_total - samples_wrote
	block = waveform[samples_wrote : (samples_wrote + buffer),]
	prediction = separator.separate(block)

I am trying to implement a sample application to do 2stems separation in run time chunk by chunk.
But separation is not proper. Don't know whether spleeter supports this type of provision.
If yes, don't where is the mistake or how to use spleeter API to achieve it.

It would be highly helpful if someone could help me or assist me with some information.

Thank you so much!

**Comment by romi1502** [comment]
Hi @racko1.
The behaviour you get with short buffers is not surprising. The model needs context for separating properly and may behave incorrectly at the border. With a buffer of 4096 (which is very short), you only have a single frame of STFT to process and then have almost no temporal context to perform separation.
Also be aware, that the default model (spleeter:<N>stems) will actually perform separation on 12s long segment even if you provide a shorter buffer (zero-padding the buffer to 12s), which will result in a very inefficient separation (both in terms of separation performance and in terms of speed). To change the size of the segment, you have to tweak the `T` parameter in the config. The smaller possible value is `64`  which corresponds to roughly 1.5s, so it is useless to try to perform separation on smaller buffer.

I guess you'd like to perform realtime on-the-fly separation which spleeter was not designed for.  Some compromise for doing it are discussed in issue #276 .

**Comment by racko1** [comment]
Got it!
Thank you so much.

**Comment by jeromeDms** [comment]
I'm also searching to separate using chunks, did you find something @racko1  ?
Thanks
