### ISSUE TITLE
[Bug] Command not found

### ISSUE THREAD

**Issue by max6292** [deezer/spleeter#51]
I'm sure this is a user error as I am new to coding but when I try to use I get "command not found". Does this mean it wasn't installed properly? 

I installed miniconda for this. 

<img width="503" alt="Screen Shot 2019-11-07 at 11 42 46 AM" src="https://user-images.githubusercontent.com/57498358/68409182-a5dfa700-0154-11ea-8cdb-9a558e6972bc.png">

Thanks for the help!

**Comment by erolsabadosh** [comment]
I'm having the same issue, someone please help!

**Comment by redapple** [comment]
Can you try running
`python -m spleeter separate -h` ?

If that doesn't work, you probablyy need to go through [the installation docs](https://github.com/deezer/spleeter/wiki/1.-Installation) again.

**Comment by erolsabadosh** [comment]
My problem turned out to be that I didn't have Anaconda installed I only installed Miniconda, once I installed Anaconda it worked. Thank you!

**Comment by max6292** [comment]
I'm still having the same issue. I have conda 4.7.12
Just tried reinstalling and got the following. Sorry I'm new at all of this! Thanks for your patience! 
<img width="568" alt="Screen Shot 2019-11-08 at 11 52 15 AM" src="https://user-images.githubusercontent.com/57498358/68495499-549bea00-021e-11ea-9a09-87a18bc0ceb2.png">

**Comment by max6292** [comment]
Re installing worked though now I am running into the ffprobe error. I reinstalled using homebrew. Still no luck. Should I just wait till next release?
