### ISSUE TITLE
the question of the audio separate time

### ISSUE THREAD

**Issue by mtz1992** [deezer/spleeter#510]
Excuse me, is the separated audio file just the first ten minutes of audio?
What to do if the original audio is longer than ten minutes？

**Comment by romi1502** [comment]
Hi @mtz1992,
As already mentioned in several issues (such as #274 ), 10 min (600s) is just the default value of the `--duration` parameter of the `spleeter separate` command. 
It can be set to any value, but be aware that you may encounter memory issues if trying to separate too big files.

**Comment by mtz1992** [comment]
ok.I get it. Thank you very much
