### ISSUE TITLE
[Discussion] How to use/export model after finished training?

### ISSUE THREAD

**Issue by EuphoriaCelestial** [deezer/spleeter#511]
Hi, I just finished training on the musdb18hq dataset, and having those files as result
![image](https://user-images.githubusercontent.com/43977734/98196707-73c77780-1f57-11eb-8812-8002574bd6b9.png)

But I dont know which one is the actual model file to use, and how to use it to inference (I am new to this, only used Pytorch before). Please provide some guide lines about this in README file too, thank you!

**Comment by romi1502** [comment]
Hi @EuphoriaCelestial ,
For inference you just need to use the JSON config file that you used for training through the `-p` (`--params_filename`) option (which is the same for both `spleeter train` and `spleeter separate`). 
Note that the JSON should contain a field `model_dir` that indicate where the model will be stored/retrieved from (and this is in this directory that the checkpoints file mentioned in your post are stored).

**Comment by EuphoriaCelestial** [comment]
> Hi @EuphoriaCelestial ,
> For inference you just need to use the JSON config file that you used for training through the `-p` (`--params_filename`) option (which is the same for both `spleeter train` and `spleeter separate`).
> Note that the JSON should contain a field `model_dir` that indicate where the model will be stored/retrieved from (and this is in this directory that the checkpoints file mentioned in your post are stored).

@romi1502 can you kindly explain more detail? I used docker to train and I tried this command to validate
`nvidia-docker run -v $(pwd)/eval_output:/eval_output -v /spleeter/musdb18hq/:/musdb researchdeezer/spleeter:gpu evaluate -p spleeter:4stems --mus_dir /musdb -o /eval_output`

but I am not sure if it is using my newly trained model or it pulled pre-trained model to evaluate; and it stuck like this for almost 12 hours, is this normal?
![image](https://user-images.githubusercontent.com/43977734/98320904-763cd680-2016-11eb-9b71-6fdb5b6d80c6.png)
