### ISSUE TITLE
Where i can fins json-config?

### ISSUE THREAD

**Issue by lesecs** [deezer/spleeter#516]
Where i can fins json-config?
I Try in  spleeter but Neverfind. Can you tell me where i can fond in Windows.
Ty

_Originally posted by @lesecs in https://github.com/deezer/spleeter/issues/153#issuecomment-727732929_

**Comment by romi1502** [comment]
JSON configs can be found here:
[https://github.com/deezer/spleeter/tree/master/configs](https://github.com/deezer/spleeter/tree/master/configs)
