### ISSUE TITLE
[Discussion] Spleeter-based apps Using TFLite on iOS have large size 

### ISSUE THREAD

**Issue by arlins** [deezer/spleeter#518]
Hello, using the latest model file "2stems.tflite" and the newly released TensorFlow Lite C++ APIs (https://github.com/jinay1991/spleeter/releases), I have successfully completed vocal separation on the iOS platform, and it works very well. The work of the Spleeter team is amazing. (I did not test 4stems, 5tems, etc.)

But I found another troublesome problem. The model file "2stems.tflite" requires that the TensorFlowLite we use must support SELECT operation, and the latest TensorflowLite version of the iOS platform does not support SELECT ops.

In order for TensorflowLite on the iOS platform to support SELECT ops, we need to use the library "TensorFlowLiteSelectTfOps" (https://github.com/aiswaryarajm/tensorflow/blob/9cef7b78b0e9f20cd828111477e35b619d59617d/tensorflow/lite/experimental/ios/TensorFlowLiteSelectTfOps.md). But this binary library is about 1.5GB in total, which is very large. For this reason, spleeter-based apps cannot be released to the App Store on the iOS platform because the final binary file/app is too large.

I tried some ways to make spleeter work without using the "TensorFlowLiteSelectTfOps" library on the iOS platform. I tried deleting the "tf.lite.OpsSet.SELECT_TF_OPS" in the conversion script "tflite_converter.py", and then generate a new tflite model file. But the final model file still needs "TensorFlowLiteSelectTfOps" to work properly.

Is it possible to solve this problem from the source model file? I have no idea.

**Comment by arlins** [comment]
@jinay1991 Hello, thank you for providing tflite model files and TFLite C++ APIs. Are the above issues known issues? Or is there a solution?

**Comment by jinay1991** [comment]
> @jinay1991 Hello, thank you for providing tflite model files and TFLite C++ APIs. Are the above issues known issues? Or is there a solution?

Yes they are known issues and exists for my TFLite C++ APIs as well. I had build libtensorflowlite.so manually with delegates linking to this statically. 

Original Model may need to adapt in this case.

**Comment by arlins** [comment]
@jinay1991  Thank you for your reply.
Checking out the data on TensorFlow official website (https://www.tensorflow.org/lite/guide/ops_select), the size of the TFLite binary file containing "Built-in ops + TF ops" on Android is 23.0 MB, and the APK size is 8.0 MB. But on iOS, the size of the binary file/app that only contains the arm64 architecture exceeds 150MB, which drives me crazy.
What's more regrettable is that TFLite does not currently support cropping for iOS versions. I will try to find ways to reduce the binary size of TFLite-related libraries.

**Comment by Turing311** [comment]
I've found a way to use pretrained models in Android / iOS APPs.

**Comment by vlatkozelka** [comment]
hi @arlins 
May I ask which tflite model you used? can you provide a link to it?
Whenever I try to load the tflite models on Android, they have wrong data shapes: [1, 1] instead of [1, 512, 1024].

**Comment by daniwavy5032** [comment]
> hello @vlatkozelka @arlins can someone please point me towards what to give the model as input? I also converted the 4stems models to tflite and the input shape is [1, 2]. I have seen lot of places that shape is [1, 512, 1024, 2] 1 and 2 being the batch size and channels. but what does I input in 512 and 1024 I can't seem to understand that

Did you fixed this?
