### ISSUE TITLE
2 stems vs 2 stems-finetune

### ISSUE THREAD

**Issue by MABMW** [deezer/spleeter#525]
Hi.
Could you explain the 
difference between 2stems and 
2stems-Finetune.

**Comment by romi1502** [comment]
Hi @MABMW,
the `2stems-finetune` model is the same as the `2stems` one, but contains extra parameter of the optimizer that makes possible to continue training of the model on your own dataset out of the box. 
`2stems-finetune` is then larger but contains only additional information for training.
So if you're only using spleeter for performing separation and not for training, you can stick to `2stems`.
