### ISSUE TITLE
[Discussion] Is it possible to use GPU with Spleeter Python API without conda?

### ISSUE THREAD

**Issue by Tiago622** [deezer/spleeter#526]
Hello all,

I'm using Spleeter Python API to separate audio signals in many stems. Is it possible to use GPU for separations without conda or docker image?

Thanks

**Comment by romi1502** [comment]
Hello @Tiago622,
yes it is possible (at least on linux, almost sure it won't work on MacOS, and not sure about Windows). 
You need to be sure to have:
- ffmpeg installed.
- a Nvidia GPU with drivers installed.
- CUDA 10.1 (a more recent version should do it too).
- python (3.6, 3.7 or 3.8) and pip.

Then `pip install spleeter` and you should then be able to run spleeter on GPU.
