### ISSUE TITLE
[Discussion] Are you still using norbert library?

### ISSUE THREAD

**Issue by ManuelFritsche** [deezer/spleeter#527]
In the paper it says that spleeter uses multi-channel Wiener filtering with the Norbert library, but I couldn't find the library anywhere in the code. Also spleeter seems to be running fine without norbert installed. Did you remove it?

I was wondering about the effect of multi-channel Wiener filtering on the results and would like to have some audio examples for comparison.

**Comment by mmoussallam** [comment]
Hi @ManuelFritsche 

Yes we still use `norbert` for instance [here](https://github.com/deezer/spleeter/blob/60ef2778f228bb4a3b3a818c7ea7979a3934faca/spleeter/model/__init__.py#L353).  If you want to try the effect of Wiener Filtering, you need to add the --mwf option to your command (see more details on the options in the [wiki](https://github.com/deezer/spleeter/wiki/2.-Getting-started#separate-sources)

Best
