### ISSUE TITLE
[Discussion] Quality Affected

### ISSUE THREAD

**Issue by D3rel** [deezer/spleeter#53]
I really liked the result of this tool, but there is something that bothers me and I hope the developers may be fixing it in the future.

I noticed that in the final file, the frequencies are cut in the spectrogram, which means a loss of quality in the audio, making it more muffled. I hope if possible this will be fixed and it managed to maintain the lossless quality of the file .. this would make the tool excellent!!

Original file:
![001](https://user-images.githubusercontent.com/54336736/68446281-115c5f80-01bb-11ea-8c06-12717d8bf446.png)

Final file: 
![002](https://user-images.githubusercontent.com/54336736/68446318-233e0280-01bb-11ea-8849-c6db1dd175ce.png)

**Comment by mmoussallam** [comment]
Hi

This issue having been raised multiple times, I've added [an entry to the FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-) section about it.

**Comment by D3rel** [comment]
> Hi
> 
> This issue having been raised multiple times, I've added [an entry to the FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-) section about it.

Thanks! I changed the info and the full spectrum was keep, so worked! But well... I hope they will soon the models be trained and groomed to work at frequencies above 11kHz, and this tool will be perfect!!
