### ISSUE TITLE
[Bug] Dev setup from scratch isn't working when python 3.9 is installed

### ISSUE THREAD

**Issue by agur** [deezer/spleeter#530]
## Description

1.  On a mac, have python 3.9 installed.
2.  But TF 2.3.0 is not found for 3.9 and errors out.
3.  In my case I had deps on 3.9 already in use on the system.  Thus force downgrade from 3.9 to 3.8 is not recommended.
4.  Expected both clean and non intrusive solution is to create a new virtual env for 3.8 and work there in a clean isolated manner.

## Step to reproduce

1.  Install env / deps with `pip install` :

```bash
(spleeterenv) $ python -m pip install .
Processing /Users/agur/dev/github/agur/spleeter
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.9/site-packages (from spleeter==2.0.2) (50.3.2)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from spleeter)
ERROR: No matching distribution found for tensorflow==2.3.0
(spleeterenv) $ python -m pip --version
pip 20.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
```

## Output

(In steps above)

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                |  MacOS 10.15.7 |
| Installation type | python 3.9, pip / virtualenv             |
| RAM available     | 32gb                             |
| Hardware spec     | CPU: 2.6 GHz 6-Core Intel Core i7, GPU: AMD Radeon Pro 5300M             |

## Additional context

Got a solution and will submit a fix.

**Comment by mmoussallam** [comment]
Hi @agur 

Thanks for your comment and suggestion. As we are already mentioning that Spleeter is only compatible with python 3.6 to 3.8 I don't think it's worth mentioning again in the README. Virtualenv is indeed one way to have it work, using our docker images is another one.

**Comment by agur** [comment]
@mmoussallam - thanks for your notes.

While this happened on Mac and I have mentioned it on the *ticket*, then there is nothing mac specific in that use-case and the same can happen not only with 3.9 but with any future non-supported version.   What I wrote for the *process* is not Mac specific:

> #### Troubleshoot dev env:
> 
> In case of already having multiple python versions installed, including 3.9.
> Then if you want to explicitly use a 3.8 since TF 2.3.0 isn't on 3.9 (yet).
> And we want a clean new virtualenv on 3.8.
> Then just instead of: `python -m venv spleeterenv` use:
> 
> ```bash
> /usr/local/opt/python@3.8/bin/python3 -m venv spleeterenv
> python -m pip install --upgrade pip
> ```
>

**Comment by nathan-stewart** [comment]
In 2023... hey spleeter - say tell xfig I said hello!
