### ISSUE TITLE
[Discussion] Instruction for installing Tensorflow 2 compatible version

### ISSUE THREAD

**Issue by katie-cathy-hunt** [deezer/spleeter#534]
I followed the installation guide on the Wiki:
```
conda install -c conda-forge spleeter-gpu
```
and it installed TF 1 which is not compatible with my Nvidia driver i.e. 455.45.01.

I saw a PR (https://github.com/deezer/spleeter/pull/498) for switching from TF 1 to 2, however I could not find any instruction on how to install the TF 2 compaible version.

Any pointers are appreciated!

**Comment by mmoussallam** [comment]
Closing this as current version is compatible.
