### ISSUE TITLE
[HELP Please!]Successfully installed but can't be used

### ISSUE THREAD

**Issue by enini** [deezer/spleeter#54]
I used pip to install `pip install spleeter `pip install spleeter -i https://pypi.doubanio.com/simple`
And I have to use the doubanio mirror because I am in China
But I have successfully installed spleeter:

However! I cannot use it. It always tells me 'system cant find this file '. I am pretty sure that the file path is correct.
After many trials, I still don't know why. Can anybody give me some suggesstions please?
Thanks
![image](https://user-images.githubusercontent.com/26686844/68447492-17822880-021b-11ea-8c68-070a33fc7b4c.png)
"系统找不到指定的文件"means that 'ERROR_FILE_NOT_FOUND  System can't find the file specificed.'

**Comment by PaulDeVito** [comment]
I'm also having this issue, but on Windows

**Comment by enini** [comment]
> I'm also having this issue, but on Windows

when i am using conda(virtual environment spleeter-cpu), everything is ok. but when using spleeter in the base environment, WinErr2 appears. 
And i am also on window

**Comment by johndpope** [comment]
Try using mini conda 
https://docs.conda.io/en/latest/miniconda.html

RIP pip.

**Comment by enini** [comment]
Thanks~
hahaha

**Comment by PaulDeVito** [comment]
awesome! conda get's the job done when creating the environment from the provided yaml. Thanks :)
