### ISSUE TITLE
Latest gpu install uses cpu only

### ISSUE THREAD

**Issue by nicolch1a** [deezer/spleeter#544]
## Step to reproduce

1. Installed using `...`
2. Run as `...`
3. Got `...` error

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```

## Environment

|       Windows 10            |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows / Linux / MacOS / other |
| Installation type | Conda / pip / other             |Pip installed spleeter-gpu with current 3.8 python anaconda
| RAM available     | XGo                             |8 gig
| Hardware spec     | GPU / CPU / etc ...             |nvidia gtx1050, not 100% sure of that. 1260 cores.

## Additional context

Not sure if this is a cuda driver issue. I do know nvidia keeps drivers up to date. Not sure how to engage the gpu???

**Comment by romi1502** [comment]
Hi @nicolch1a,
I double checked and I'm able to run spleeter (2.0.2, latest version) on GPU (with CUDA Driver 430.14 and CUDA 10.2).
So you'e issue is probably linked to a bad CUDA configuration.
