### ISSUE TITLE
[Discussion] Using spleeter for dialog separation

### ISSUE THREAD

**Issue by edwar64896** [deezer/spleeter#547]
What would be the best way to go about using spleeter for dialog separation? Specifically, isolation of dialog in noisy or unfriendly contexts (i.e. lots of background noise).

Have located training info in manual - hopefully this will shed some light.

**Comment by romi1502** [comment]
Hi @edwar64896
Have you tried to use straightforwardly the pretrained models on noisy dialogs?
I think they could actually do a fair job at isolating speech.
Depending on your application, you may need to train your own on model, and then to do that you'll need a dataset of clean dialogs with isolate noise.
