### ISSUE TITLE
[Discussion] Output is cut off at about 11kHz

### ISSUE THREAD

**Issue by okaycpu** [deezer/spleeter#55]
Pretty self explanatory. Is there a way to get an output that's the same quality that's put in? Like I'd like to input a lossless file and get a lossless file out that isn't a bad transcode. I use -c flac and I still get files that are cut off at ~11kHz.
![Screen Shot 2019-11-07 at 9 53 38 PM](https://user-images.githubusercontent.com/57510018/68448430-16181800-01a9-11ea-89df-c36edcad061c.png)

**Comment by mmoussallam** [comment]
Hi

Since this issue has been raised multiple times now I've added [an entry to the FAQ ](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-) section about it!
