### ISSUE TITLE
Warning! ***HDF5 library version mismatched error***

### ISSUE THREAD

**Issue by bfp4** [deezer/spleeter#550]
I installed the softwear but when i try to run it gives me this waring "Warning! ***HDF5 library version mismatched error***". I checked and found that i needed to update the h5py to 1.10.6, but when i did that the h5py install gave me this error.
`PackagesNotFoundError: The following packages are not available from current channels:

  - h5py=1.10.6`

**Comment by romi1502** [comment]
Hi @bfp4,
`h5py` is not a direct dependency of `spleeter`, but a dependency of `tensorflow` (which is needed by `spleeter`).
The current version of `spleeter` deployed on pypi uses `tensorflow` 2.3.0 that dependes on `h5py` 2.
The warning then could come from another package (not related to spleeter) that would require another version of `h5py`, but from a clean environnement with the latest version of `spleeter` installed, you should not have this warning.
