### ISSUE TITLE
[Discussion] Public Release Version 2.0.2

### ISSUE THREAD

**Issue by jujudusud** [deezer/spleeter#552]
Hello here, and thanks for all that stuff ! really usefull !

I'm going to update the Archlinux AUR package of spleeter and I need a public release at 2.0.2 version.

Is it possible to provide such a release ?

Thanks a lot in advance.

**Comment by Faylixe** [comment]
Hi, thanks for maintaining Spleeter on Arch. It would be better to wait just a little as we are about to release 2.1.0 in coming days. I would let you know at this time on this issue :)

**Comment by jujudusud** [comment]
Ok for me to wait for the 2.1.0 release. Thank you.

**Comment by Faylixe** [comment]
Alright,  we release the new version and apply some patches, current version 2.1.2 should be good for you to go, the package is available on PyPi: https://pypi.org/project/spleeter. Please note that we do not have CPU / GPU package anymore but only one that works on both CPU and GPU.

**Comment by jujudusud** [comment]
Thanks a lot @Faylixe ! I'm building the package... :-) Will let you know if it's working properly on Archlinux.

**Comment by Mixerrog** [comment]
I have have a great working version of the original Spleeter 1.43 release with modifications for 16 khz & even 22.4 khz stem separations that run fine on my Windows 10 computer. I have even wrote bin files to do multiple song separations that work fine also. Is there any reason to upgrade to a newer version? Has the Stem separations been improved on?

I was told there would be a new Spleeter version released that would provide a slight improvement -- is this 2.02 version it & that a Pro version with a much larger training base has been sold to a US company that should be making an announcement about it but heard nothing about either -- any more details?

Thanks, Rog


     On Monday, January 11, 2021, 05:52:32 AM CST, Félix Voituret <notifications@github.com> wrote:  
 
 


Alright, we release the new version and apply some patches, current version 2.1.2 should be good for you to go, the package is available on PyPi: https://pypi.org/project/spleeter. Please note that we do not have CPU / GPU package anymore but only one that works on both CPU and GPU.
