### ISSUE TITLE
 fichier spleeter-cpu.yaml absent

### ISSUE THREAD

**Issue by dextermaniac** [deezer/spleeter#555]
dans le fichier ZIP de  SLEEPER (version windows ) dans le dossier "conda" le fichier "" spleeter-cpu.yaml "" est absent
impossible donc de créer un nouvel environnement dans anaconda

**Comment by Faylixe** [comment]
Actually we do not provide Conda environment but Conda package directly, available on Anaconda cloud. We will update doc and package soon.
