### ISSUE TITLE
[Bug] pip install spleeter -> broken (on Archlinux)

### ISSUE THREAD

**Issue by jujudusud** [deezer/spleeter#557]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description
Pip install of spleeter 2.1.0 broken on archlinux.
Searching for tensorflow 2.3.0 -> not available.

## Step to reproduce

1. Installed using `pip install spleeter`
2. Run as `user` and/or 'root'
3. Got `ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from spleeter) (from versions: none)
ERROR: No matching distribution found for tensorflow==2.3.0 (from spleeter)` error

## Output
~ $ pip install spleeter
Defaulting to user installation because normal site-packages is not writeable
Collecting spleeter
  Downloading spleeter-2.1.0-py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 3.4 MB/s 
Collecting typer<0.4.0,>=0.3.2
  Downloading typer-0.3.2-py3-none-any.whl (21 kB)
Collecting ffmpeg-python==0.2.0
  Downloading ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting librosa==0.8.0
  Downloading librosa-0.8.0.tar.gz (183 kB)
     |████████████████████████████████| 183 kB 5.8 MB/s 
Collecting pandas==1.1.2
  Downloading pandas-1.1.2.tar.gz (5.2 MB)
     |████████████████████████████████| 5.2 MB 6.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting httpx[http2]<0.17.0,>=0.16.1
  Downloading httpx-0.16.1-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 1.5 MB/s 
Collecting norbert==0.2.1
  Downloading norbert-0.2.1-py2.py3-none-any.whl (11 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from spleeter) (from versions: none)
ERROR: No matching distribution found for tensorflow==2.3.0 (from spleeter)
## Environment
| ----------------- | ------------------------------- |
| OS                | Linux Archlinux |
| Installation type | pip             |
| RAM available     | 8 Go                             |
| Hardware spec     | Intel celeron integrated GPU            |

## Additional context
-

**Comment by Faylixe** [comment]
Could you try installing Tensorflow separately as an arch package using `pacman` ? I am not familiar with Archlinux, but a quick search sound like you can not rely properly on pip for some specific dependencies (using binary distribution I guess ?) such as TF.

**Comment by jujudusud** [comment]
tensorflow is at version 2.4.0 on archlinux, and trying to lunch :
`spleeter separate -p spleeter:2stems -o output audio_example.mp3`
Fail with : 
`pkg_resources.DistributionNotFound: The 'tensorflow==2.3.0' distribution was not found and is required by spleeter`
even if tensorflow is installed.

**Comment by jujudusud** [comment]
Modifying required version in setup.py let my go a little further.
Blocked now with :
`pkg_resources.DistributionNotFound: The 'pooch>=1.0' distribution was not found and is required by librosa`

**Comment by jujudusud** [comment]
The pooch problem is being with the resolution of a bug on the archlinux package.
Now, h2 is required in version 3.* and is present on archlinux at 4.0.0 ...

**Comment by jujudusud** [comment]
Closing the issue. impossible here to use Spleeter with a non AVX CPU and no CUDA GPU. :-(

**Comment by jujudusud** [comment]
It's working well with a virtualenv python 3.7.
Only have to buy a new AVX compatible CPU :-)

**Comment by jujudusud** [comment]
Ok, Now I can use an I7 CPU wih AVX and it's working virtualenv python 3.8 with poetry : 
1 -pip install poetry
2 -poetry install (into spleeter source directory)
Just fine ! :-)
Thanks a lot for that stuff.
Now, trying to update Archlinux Package at latest spleeter version.
