### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by Laikanoosh** [deezer/spleeter#558]
I'm not a programmer or anything so this will probably come across as an obvious question. 

I have gotten everything installed and I'm a femtometer away from getting spleeter to work.

But what does this mean?? 

  _FILES...  List of input audio file path  [required]_

I seem to be using the other commands properly I just have no idea what to type in for that. every time I try anything it says:

_Error: Invalid value for 'FILES...': File 'audio_example.mp3' does not exist._ 

Anything helps I'm so close to getting this I think It hurts

**Comment by IvanGH2** [comment]
I'm assuming you're looking to separate audio_example into stems. Let's say that audio_example.mp3 is present in C:\test directory. Then, in cmd navigate to C:\test

c:\>cd c:\test 

and then call spleeter separate 

c:\test>spleeter separate audio_example.mp3 -o stems

If everything goes OK, you should now see the stems in the C:\test\stems\audio_example folder.
