### ISSUE TITLE
[Discussion] Python Version

### ISSUE THREAD

**Issue by muZa11** [deezer/spleeter#563]
when installing it says.

> Specifications:
> 
>    - spleeter -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
> 
> Your python: python=3.8
> 

what does this mean?
> >=3.6,<3.7.0a0|>=3.7,<3.8.0a0

 i mean, to which version i have to switch?

**Comment by romi1502** [comment]
Hi @muZa11 
How are you trying to install spleeter ?
Spleeter is supposed to be compatible with python 3.8 by now, so I'd like to be able to reproduce your error.

**Comment by muZa11** [comment]
steps:
1. sudo -i
2. apt install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6
3. downloaded anaconda for linux x84 64bit
4. bash ~/anacodaXXX.sh
5. conda install -c conda-forge spleeter

i have also tried pip method but couldn't installed libsndfiles so rollback to anaconda method. 
I am in Kali Linux.

**Comment by muZa11** [comment]
see this screenshot. just tried again.
https://drive.google.com/file/d/1vqynF89ERXW1AKa4CnPcQu35M8oEmoTI/view?usp=sharing

**Comment by mmoussallam** [comment]
Hi @muZa11 

We've just revamped the conda package and it has a new location. Can you try `conda install -c deezer-research spleeter` ?

**Comment by Mixerrog** [comment]
Is there any stem separation improvements over the original 1.43 that I have been using fine on my Windows 10 computer as reading all these emails, it seems like a lot of trouble to upgrade it so have been leaving mine with the original version?

Rog


     On Thursday, January 21, 2021, 07:17:33 AM CST, Moussallam <notifications@github.com> wrote:  
 
 


Hi @muZa11

We've just revamped the conda package and it has a new location. Can you try conda install -c deezer-research spleeter ?

**Comment by muZa11** [comment]
the version problem is gone but 
https://drive.google.com/file/d/18dtIeBIPe9ujw3niFuKEuk1KJtQD7e4C/view?usp=sharing

**Comment by romi1502** [comment]
There is indeed an issue with conda install. We'll have a look into it.

**Comment by mmoussallam** [comment]
Hi @muZa11 

run the command `conda config --add channels conda-forge` before the spleeter install one and it should be good. I'll update the documentation accordingly.

Let me know if that does not solve your issue
