### ISSUE TITLE
Cannot install Spleeter in W10 64

### ISSUE THREAD

**Issue by JimboLab** [deezer/spleeter#565]
- [ ] I didn't find a similar issue already open.
- [ ] I read the documentation (README AND Wiki)
- [ ] I have installed FFMpeg
- [ ] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Step to reproduce

1. Installed using `...`
2. Run as `...`
3. Got `...` error

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```
Attempt #1:
conda install -c conda-forge spleeter
failed
Specifications: 
 - spleeter -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0A0']
Your python: python=3.8

Attempt #2:
conda install -c deezer-research spleeter
failed
CondaHTTPError: HTTP 500 INTERNAL SERVER ERROR for url...

## Environment

Win 10 64 fully patched, latest AnaConda individual edition

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows / Linux / MacOS / other |
| Installation type | Conda / pip / other             |
| RAM available     | XGo                             |
| Hardware spec     | GPU / CPU / etc ...             |

**Comment by MABMW** [comment]
Hello, try to install spleeter via pip; "pip install spleeter"
Mention, that versions installed with pip do not support GPU, but that the process will be made with the CPU.

**Comment by romi1502** [comment]
Hi @JimboLab 
we indeed have issues with the conda install. We moved from conda-forge to our own channel (deezer-research) lately. 
There seems to be issues with the new channel install, we have to investigate them.
There are only old version on the conda-forge channel but they are only compatible with python 3.7 (not 3.8).
While for a fix on our channel, here are workarounds:
* If you're not interested in having the most up to date spleeter version, install it from conda-forge in a python 3.8 environnement:
```bash
conda create -n py37 python=3.7
conda activate py37
conda install -c conda-forge spleeter
```
*  If you want the latest version of spleeter or want to stay on a python 3.8 env, first make sure you have `ffmpeg` installed and then install spleeter with pip. As you already have conda installed, you can do:
```bash
conda install ffmpeg
pip install spleeter
````

Note that there is now a single package for both the gpu and cpu version (as tensorflow is now both gpu and cpu compatible).
