### ISSUE TITLE
[Feature] --version ?

### ISSUE THREAD

**Issue by martinratinaud** [deezer/spleeter#566]
## Description

I need to know which version of spleeter is installed

for this, I would use `spleeter --version` but I can't find this information anywhere.

Does this feature exist?

Thanks

**Comment by billy-horn** [comment]
I would be wiling to help with this feature if it does not exist!

**Comment by mmoussallam** [comment]
Hi @martinratinaud 

you can run a plain `pip freeze | grep spleeter`

**Comment by martinratinaud** [comment]
Thank you very much @mmoussallam
