### ISSUE TITLE
Reason to update Spleeter?

### ISSUE THREAD

**Issue by Mixerrog** [deezer/spleeter#570]
I have been using version 1.43 on my Windows 10 machine fine since it first came out & want to know if there have been any improvements to the stem separations on the later versions since it looks like many are having issues installing the newer versions?

Thanks, Rog

**Comment by brisu** [comment]
Going through the change log I don't think there were major changes to the stem separations but I could be wrong. Most of the new versions contain improvements and updates to packages, services, etc. For the official and more detailed list that could help you decide if you want to upgrade. Refer to the [change log](https://github.com/deezer/spleeter/blob/master/CHANGELOG.md). 

I hope this was helpful in the slightest.

**Comment by romi1502** [comment]
Hi @Mixerrog 
There were no major changes in spleeter (mostly bugfixes, update of version for some dependancies, refactoring and small new features), and the models performing separation are the same. So if you're not affected by any bug that was fixed in the meantime, you can stay on 1.4.3

**Comment by Mixerrog** [comment]
Thanks for your feedback on this.

Rog


     On Friday, March 5, 2021, 07:00:20 AM CST, Romain Hennequin <notifications@github.com> wrote:  
 
 


Hi @Mixerrog
There were no major changes in spleeter (mostly bugfixes, update of version for some dependancies, refactoring and small new features), and the models performing separation are the same. So if you're not affected by any bug that was fixed in the meantime, you can stay on 1.4.3
