### ISSUE TITLE
[Bug] separator.separate(waveform) now fails because audio_descriptor is None

### ISSUE THREAD

**Issue by JeffreyCA** [deezer/spleeter#571]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

In the recent updates, `separator.py` was refactored and the `separate` function was changed from

```py
def separate(self, waveform: np.ndarray, audio_descriptor=''):
```

to:

```py
def separate(self, waveform: np.ndarray, audio_descriptor: Optional[str] = None):
```

If you call `separator.separate(waveform)` without passing `audio_descriptor`, it will be set to `None`. This causes `_separate_librosa` and `_separate_tensorflow` to fail as they expect `audio_descriptor` to not be `None`.

On librosa, I get an error: `Unsupported object type NoneType`.

I think the default should be changed back to empty string, not `None`.

**Comment by raraz15** [comment]
Using , audio_descriptor=''" solved my problem as JeffryCA mentioned

**Comment by romi1502** [comment]
Hi @JeffreyCA,
Thank you for reporting the issue.
It was fixed in this [PR]( https://github.com/deezer/spleeter/pull/587) which was just merged to master.
