### ISSUE TITLE
[Discussion] How do I use Multichannel Wiener Filtering for separation command?

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [deezer/spleeter#572]
When I enter `spleeter --help` it shows me this: 

> Guide:
> Usage: spleeter separate [OPTIONS] FILES...
> 
>   Separate audio file(s)
> 
> Arguments:
>   FILES...  List of input audio file path  [required]
> 
> Options:
>   -i, --inputs TEXT               (DEPRECATED) placeholder for deprecated
>                                   input option
> 
>   -a, --adapter TEXT              Name of the audio adapter to use for audio
>                                   I/O  [default: spleeter.audio.ffmpeg.FFMPEGP
>                                   rocessAudioAdapter]
> 
>   -b, --bitrate TEXT              Audio bitrate to be used for the separated
>                                   output  [default: 128k]
> 
>   -c, --codec [wav|mp3|ogg|m4a|wma|flac]
>                                   Audio codec to be used for the separated
>                                   output  [default: wav]
> 
>   -d, --duration FLOAT            Set a maximum duration for processing audio
>                                   (only separate offset + duration first
>                                   seconds of the input file)  [default: 600.0]
> 
>   -s, --offset FLOAT              Set the starting offset to separate audio
>                                   from  [default: 0.0]
> 
>   -o, --output_path PATH          Path of the output directory to write audio
>                                   files in  [default: C:\Users\Windo\AppData\L
>                                   ocal\Temp\separated_audio]
> 
>   -B, --stft-backend [auto|tensorflow|librosa]
>                                   Who should be in charge of computing the
>                                   stfts. Librosa is faster than tensorflow on
>                                   CPU and uses  less memory. "auto" will use
>                                   tensorflow when GPU acceleration is
>                                   available and librosa when not  [default:
>                                   auto]
> 
>   -f, --filename_format TEXT      Template string that will be formatted to
>                                   generatedoutput filename. Such template
>                                   should be Python formattablestring, and
>                                   could use {filename}, {instrument}, and
>                                   {codec}variables  [default:
>                                   {filename}/{instrument}.{codec}]
> 
>   -p, --params_filename TEXT      JSON filename that contains params
>                                   [default: spleeter:2stems]
> 
>   --mwf                           Whether to use multichannel Wiener filtering
>                                   for separation  [default: False]
> 
>   --verbose                       Enable verbose logs  [default: False]
>   --help                          Show this message and exit.

But I didn't understand how do I use the command `--mwf` or how do I enable the **_multichannel Wiener filtering_**?

**Comment by romi1502** [comment]
Hi @MohammedMehdiTBER,
By default Multichannel Wiener Filtering (MWF) is off. You can set it on using the `--mwf` option:
```bash
 spleeter separate audio_example.mp3 -B tensorflow -o output # MWF is off
 spleeter separate audio_example.mp3 --mwf -B tensorflow -o output_mwf # MWF is on
```
Note that there is currently a bug in spleeter that make the `--mwf` option not taken into account when using the `librosa` STFT backend (which is the default one when running spleeter on CPU), so you currently need to use the `tensorflow` backend (using the `-B tensorflow` option) to make it work. See issue #580 for further details on this issue.

**Comment by MohammedMehdiTBER** [comment]
Do I need to specify -o output_mwf and not -o output ?

**Comment by romi1502** [comment]
No you don't need to specify the "-o" option. The `-o` option is used to set the output path where the separated audio files will be written  by spleeter.
