### ISSUE TITLE
Spleeter on PythonAnywhere

### ISSUE THREAD

**Issue by LuigiAttorresi** [deezer/spleeter#579]
Hello, I’ve tried to install Spleeter on a server of PythonAnywhere using a pro account with 10 GB available. However after the installation when trying to use it to extract the stems of an input audio it gives this error:

tensorflow/core/platform/env.cc:351] Check failed: -1 != path_length (-1 vs. -1)

Is there a way to fix this?

**Comment by romi1502** [comment]
Hi @LuigiAttorresi 
The error that pops out is raised by tensorflow. So it may be either an issue with the version of tensorflow you installed or an issue with the input audio file you're using. Have you tried performing a separation using the [provided example file](https://github.com/deezer/spleeter/blob/master/audio_example.mp3) first? do you get the errors for it ?
Could you send the complete stacktrace of your error to help us understand it ?

**Comment by LuigiAttorresi** [comment]
Yes I’ve tried using the provided example, but I get always the same error. I’m creating a virtual environment with python 3.8 where ffmpeg and spleeter are installed, then using spleeter both by python script and command line it gives that error.

```
$ spleeter separate -p spleeter:2stems -o output audio_example.mp3 --verbose
                                                                                                               
F tensorflow/core/platform/env.cc:351] Check failed: -1 != path_length (-1 vs. -1) 
Aborted
```

**Comment by romi1502** [comment]
I couldn't reproduce your bu on several different configs so we'll need more details to help.
Have you tried to run spleeter [using docker](https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-docker-image) ?

**Comment by LuigiAttorresi** [comment]
I've found out the problem is that TensorFlow doesn't correctly run on PythonAnywhere, in fact I get the same error even by running other TF functions.
Thank you anyway!
