### ISSUE TITLE
[Feature] Output audio has cut off 12 kHz and higer frequencies

### ISSUE THREAD

**Issue by janeczek2** [deezer/spleeter#58]
## Description
Created output file has higer frequencies cut off at around 12 kHz. Can spleeter be configured to higher the cutoff at 20 kHz?

## Step to reproduce

1. Installed using conda
2. Running as it it should, no errors.
3. Got output file has frequency spectrum cut off at around 12 kHz.

## Output

```bash
INFO:spleeter:File output\pisarzflac\accompaniment.wav written
INFO:spleeter:File output\pisarzflac\vocals.wav written
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 7 x64 |
| Installation type | Conda |
| RAM available     | XGo    16GB|
| Hardware spec     | / CPU i7 4790 |

**Comment by mmoussallam** [comment]
Addressed in the [wiki](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-)
