### ISSUE TITLE
[Bug] Wrong Python documentation on Wiki page

### ISSUE THREAD

**Issue by martinthedinov** [deezer/spleeter#582]
I would propose this as a change to the Wiki page but it doesn't seem to be openly editable as a wiki would be. Anyway, your documentation seems to be outdated/wrong, specifically this part:

```
# Use audio loader explicitly for loading audio waveform :
from spleeter.audio.adapter import get_default_audio_adapter
audio_loader = get_default_audio_adapter()
```

should be:

```
# Use audio loader explicitly for loading audio waveform :
from spleeter.audio.adapter import AudioAdapter
audio_loader = AudioAdapter.default()
```

**Comment by martinthedinov** [comment]
There is an existing issue about this that I hadn't seen. Duplicate so closing.

**Comment by martinthedinov** [comment]
Actually, https://github.com/deezer/spleeter/issues/124 is not a duplicate. Looks like the current documentation on the Wiki is wrong again/still. It works as per above.

**Comment by romi1502** [comment]
Hi @martinthedinov 
Thank you for pointing the issue. I've just fixed the wiki.
