### ISSUE TITLE
Model Repeat Download

### ISSUE THREAD

**Issue by pHequals7** [deezer/spleeter#59]
After I ran the demo script using the audio example file, when i tried it with my own music file, it again downloads the previously downloaded model which I feel makes it very slow and inefficient
![error image](https://i.imgur.com/6phvO4S.jpg)

| OS - Windows
| Installation type - git clone and conda create env
| RAM available - 8GB
| Hardware spec  GPU - 1050 CPU - i5 8th Gen

**Comment by sjernigan** [comment]
If you are using the docker image, read the paragraph starting with 'For using your own audio file you will need to create contain' on the Usage page

**Comment by wistephens** [comment]
I'm have this need as well. Whenever I attempt to use the 5Stem split I get 5 wav files with basically the same content. The 2 and 4 stem models work very well.  I lost network connection when the 5stem model was downloading and I cannot figure out how to force a re-download of the model.  

| OS - MAC
| Installation type - git clone and conda create env;  cpu env
| RAM available - 8GB
| Hardware spec GPU - 1050 CPU - i5 8th Gen

**Comment by wistephens** [comment]
I fixed my issue: 
- download the 5stem.tar.gz file
- replace contents of spleeter/pretrained_models/5stem with contents of tar.gz

**Comment by pHequals7** [comment]
I tried the third time using custom audio - 2stems and this time it worked without downloading.
