### ISSUE TITLE
[Discussion] Could not find a version that satisfies the requirement tensorflow==2.3.0 (from spleeter)

### ISSUE THREAD

**Issue by Gseasoning** [deezer/spleeter#592]
I've been trying to install spleeter obviously the native version and when I try to install with cmd "pip3 install spleeter"
 I get this error message. 

ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from spleeter)
ERROR: No matching distribution found for tensorflow==2.3.0

Not sure what to do to fix this

**Comment by romi1502** [comment]
Hi @Gseasoning,
I cannot reproduce your issue. What OS are you using ? What version of python ?

**Comment by martinfinke** [comment]
I ran into the same issue when using Python 3.9. Tensorflow 2.3.0 [only supports Python 3.8](https://pypi.org/project/tensorflow/2.3.0/#files), so I downgraded to Python 3.8 and was able to install everything.

**Comment by romi1502** [comment]
Indeed spleeter is only compatible with python 3.6 to 3.8, mainly for dependancies such as tensorflow not compatible with later versions.
