### ISSUE TITLE
[Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by hadji-yousra** [deezer/spleeter#593]
I have a problem when I execute this command : 

python -m spleeter separate -o output/ audio_example.mp3

the error I get is the following: 
![image](https://user-images.githubusercontent.com/74329449/110136643-37eed280-7dd0-11eb-9e45-10c24de3763e.png)

I would like to point out that: 
1 - I'm on windows that's why I added the "python -m ". 
2 - I installed spleeter with pip after installing ffmpeg-python without any error message or warning.

**Comment by romi1502** [comment]
Hi @hadji-yousra,
The error you get seems to be a URL resolution error, seemingly when trying to download the model from github (but not sure as the stacktrace you provided does not even include code within spleeter).
My first guess is that it is not specifically a spleeter error, but an issue with your network settings / internet connection that prevented spleeter to access github at the time you ran the command.
Have you tried to download https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz from the same shell (using for instance wget)?
