### ISSUE TITLE
[Discussion] Skip to download pretrained_models in Docker

### ISSUE THREAD

**Issue by Tringles** [deezer/spleeter#594]
I made a AWS lambda using docker and I found that every time lambda is called, it downloads a folder, "pretrained_models". That process takes about 6~10 seconds and I want to reduce the time. What I did is
When I build a docker image, I put a folder "pretrained_models" together so that it does not have to download. However, it failed.
Secondly, I upload the folder "pretrained_models" to S3 bucket so that every time lambda is called, lambda loads the folder. I found that there is a hidden file in "pretrained_models" and I load it too. However, this also does not work.
I checked the directory where the folder should be located and there was no problem.

are there any things that I did not think about or solutions?
I want to get an answer of this problem.

**Comment by romi1502** [comment]
Hi @Tringles,
We provide docker images that already embed the model:
For instance the [3.8-2stems](https://hub.docker.com/layers/deezer/spleeter/3.8-2stems/images/sha256-0687d3334e9c0be11c31f053818f2c6d6eb73ac505f107f31fd91c10b752e7eb?context=explore) image includes the 2 stems model, and thus does not need to download back the model at each run.
It seems that there are issues with the 4/5 stems images (do not exist for 3.8 and include an old version of spleeter for 3.6/3.7) but we'll have a look at it and try to fix asap.

**Comment by PeijiYang** [comment]
@romi1502 how to set the path of the pretrained model.

**Comment by romi1502** [comment]
@PeijiYang , you can use the `MODEL_PATH` environment variable to set the path of the model.

**Comment by PeijiYang** [comment]
> @PeijiYang , you can use the `MODEL_PATH` environment variable to set the path of the model.

Can't it be set in the code? only environment variable?

**Comment by romi1502** [comment]
> Can't it be set in the code? only environment variable?
No it cannot at the moment. I'm not sure why you would need to set it within the code though.

**Comment by romi1502** [comment]
@Tringles, 
we fixed the 4 and 5stems docker images that should work now, so I close the issue.
