### ISSUE TITLE
[Discussion] How do you change the file path format for separated track outputs?

### ISSUE THREAD

**Issue by carter-king** [deezer/spleeter#596]
I am hoping to change the path where files are saved when I call the python API's separate_to_file(). I want to save files such that their path is /destination/trackname_instrument.wav instead of the default /destination/trackname/instrument.wav. I have been trying to pass the optional filename_format parameter, but I am not sure how to use it correctly. The "Exported filename format" section of the wiki still says "To be documented".

**Comment by romi1502** [comment]
Hi @carter-king,
indeed, you need to use the filename_format parameter:
```python
from spleeter.separator import Separator
separator = Separator("spleeter:2stems")
separator.separate_to_file("/path/to/audio.mp3",  "/path/to/output",  filename_format="{filename}_{instrument}.{codec}")
```

You can user the keyword `filename` (input file name), `instrument` (name of the instrument), `foldername` (name of the folder the input file is in) and `codec` between curly brackets within the formatting string.
