### ISSUE TITLE
[Discussion] Some update needed on FAQ.

### ISSUE THREAD

**Issue by jujudusud** [deezer/spleeter#597]
Hi all,

Reading [Faq - Python 3.8](https://github.com/deezer/spleeter/wiki/5.-FAQ#python-38) , I think there an update to be made for this Python 3.8 chapter.
Spleeter is working really well in python 3.8 at 2.2.1 version.
I know it's the difficult to align documentation with versions, hard and long work.
I made this issue just to point out what I saw reading the doc because I don't know how to Pull Request for wiki pages... :-(

Thanks a lot for all that awesome stuff ! :-)

**Comment by romi1502** [comment]
Hi @jujudusud,
thank you for spotting this issue. I've just fixed the page.

**Comment by jujudusud** [comment]
Merci ! :-)
