### ISSUE TITLE
[Bug] Outdated wiki information about "spleeter separate -h"?

### ISSUE THREAD

**Issue by n-zhi** [deezer/spleeter#599]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

When I'm trying to get help and type `spleeter separate -h` as stated on the page [2. Getting Started](https://github.com/deezer/spleeter/wiki/2.-Getting-started#usage) I get an error.

## Step to reproduce

1. Installed using `pip3 install spleeter`
2. Run as `python3 spleeter separate -h`
3. Got `Error: no such option: -h` error

## Output

```
$ python3 spleeter separate -h
Usage: spleeter separate [OPTIONS] FILES...
Try 'spleeter separate --help' for help.

Error: no such option: -h
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Linux |
| Installation type | pip |
| RAM available     | N/A |
| Hardware spec     | N/A |

## Additional context
`spleeter separate --help` works correctly.

**Comment by romi1502** [comment]
Hi @n-zhi,
Indeed, the last version of spleeter uses the `typer` package as CLI argument manager, so the short `-h` form for `--help` no longer works. We'll have a look if we can bring it back easily with typer.
In the meantime I've updated the wiki with the long `--help` form.
Thank you for spotting this.
