### ISSUE TITLE
Improvement: Include the model artifact into the Docker image (instead of downloading at run time)

### ISSUE THREAD

**Issue by iMerica** [deezer/spleeter#6]
Image building happens once, running the container happens N times. Theres no reason to re-download the model every time it runs.

**Comment by pppq** [comment]
I also tried adding a volume for it at `/model`, mentioned in the [Getting started](https://github.com/deezer/spleeter/wiki/2.-Getting-started#run-container) page of the wiki, but it does not seem to pick up a pre-downloaded instance.

**Comment by alreadytaikeune** [comment]
Hello,

There is indeed a problem in the wiki. `/model` doesn't correspond to the path where the models are actually extracted it seems. They are in `/workspace/spleeter/pretrained_models`, so you can mount a volume there, e.g.

` nvidia-docker run -v $(pwd)/output:/output -v $(pwd)/pretrained_models:/workspace/spleeter/pretrained_models ...`

**Comment by pppq** [comment]
Thanks! I see that the `MODEL_PATH` environment variable can also control the location within the container.

**Comment by alreadytaikeune** [comment]
Indeed, you can also keep the command given in the wiki, and set the environment variable `-e MODEL_PATH=/model` when running the container.

**Comment by Faylixe** [comment]
We will probably also at some point distribute ready to use *Docker* image on *DockerHub* which will embed model directly.

**Comment by mickdekkers** [comment]
In the interim, you can add this to your Dockerfile somewhere after the `WORKDIR /workspace/spleeter` command:
```dockerfile
RUN mkdir -p ./pretrained_models/2stems && \
    wget -nv https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz && \
    tar -xvzf 2stems.tar.gz -C ./pretrained_models/2stems && \
    rm -f 2stems.tar.gz
```

This will download and extract the 2stems model to the right place (adjust for different models). Note that you'll need to [rebuild](https://github.com/deezer/spleeter/wiki/2.-Getting-started#build-image) after updating your Dockerfile.

**Comment by romi1502** [comment]
I fixed the command in the wiki with the extra `-e MODEL_PATH=/model` option. 
As suggested by @mickdekkers, you can also build your own image with the model you need (avoiding including all models when you only need one).
