### ISSUE TITLE
Cannot find reference 'get_default_audio_adapter' in 'adapter.py' 

### ISSUE THREAD

**Issue by cong-x-p** [deezer/spleeter#600]
from spleeter.audio.adapter import get_default_audio_adapter but my IDE reported that the reference cannot be found

**Comment by romi1502** [comment]
Hi @cong-x-p,
the `get_default_audio_adapter` function was indeed removed from a previous version. 
To get a default audio adapter, you now should call the `default` class method of AudioAdapter:

```python
from spleeter.audio.adapter import AudioAdapter
default_adapter = AudioAdapter.default()
```
