### ISSUE TITLE
[Bug] zsh: killed     spleeter separate -p "/home/mohammedmehditber/Documents/base_config.json" -o 

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [deezer/spleeter#602]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

I Installed all dependencies and updated conda and ran pip check spleeter 

## Step to reproduce

1. Installed using `Debian ZSH`
2. Run as `sudo spleeter separate -p "/home/mohammedmehditber/Documents/base_config.json" -o "output_mwf" -f {filename}-{instrument}.{codec} -d 7200 -c mp3 -b 320k --mwf -B tensorflow "/home/mohammedmehditber/Music/mytrack.mp3" --verbose
`
3. Got `zsh: killed` error

## Output

```bash
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/4stems.tar.gz
INFO:spleeter:Validating archive checksum
INFO:spleeter:Extracting downloaded 4stems archive
INFO:spleeter:4stems model file(s) extracted
INFO:tensorflow:Using config: {'_model_dir': 'pretrained_models/4stems', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.7
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Apply unet for vocals_spectrogram
INFO:tensorflow:Apply unet for drums_spectrogram
INFO:tensorflow:Apply unet for bass_spectrogram
INFO:tensorflow:Apply unet for other_spectrogram
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from pretrained_models/4stems/model
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
zsh: killed     spleeter separate -p "/home/mohammedmehditber/Documents/base_config.json" -o 

```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Debian Linux |
| Installation type | Zsh  Mini Conda and pip            |
| RAM available     | 6Go                             |

**Comment by romi1502** [comment]
Hi @MohammedMehdiTBER,
`killed` errors are usually Out Of Memory errors meaning that the `spleeter` command try to use too much memory.
This is very likely that the signal you're trying to use is too long (which seems to be confirmed by the option `-d 3200` that you use. Separate your file by smaller chunk should solve the issue.

**Comment by MohammedMehdiTBER** [comment]
I use the same settings for Windows and it works on the same device.
Yet some other tracks don't give an output.
Is it because I'm using 22Khz?
