### ISSUE TITLE
[Feature] Yosemite Compatibility?

### ISSUE THREAD

**Issue by louisCyphre666** [deezer/spleeter#604]
## Description

I run OSX 10.10.5 on my mid 2012 MacBook Pro, 2.3 GHz core i7 with eight virtual cores, 16GB RAM, and two internal 1TB SSD’s. My d.a.w. of choice is ProTools, and version 10.3.10 is what I have a license for and what all of my plug-ins are licensed for. I refuse to upgrade when my hardware and software is working perfectly but I’m having issues finding things that are compatible with anything below 10.11. I really need something like this and was hoping there was a gooey version available that was pre-compiled that will work with Yosemite. If not, I would be extremely grateful if somebody with more coding experience could message me somehow and help me do it. I have some experience with Command line in Darwin and Linux, but usually just following instructions and memorizing certain tasks. I have not built some thing from source code completely by myself except for a couple times many years ago at the beginning of the OSX86 project using OSX 10.4.3. 

This is my first time posting on here as usually I just read, so please be easier on me if I made a mistake and posted some thing in the wrong place. I’m still learning my way around.

**Comment by mmoussallam** [comment]
Hi @louisCyphre666 

Spleeter does not require any specific version of macOs, you just need to have a compatible Python installed, which is anything between 3.6 and 3.8. you'll find installers for instance [there](https://www.python.org/downloads/mac-osx/)

let us know if you run into some issues
