### ISSUE TITLE
docker: Error response from daemon: Unknown runtime specified nvidia.[Discussion] your question

### ISSUE THREAD

**Issue by hjing100** [deezer/spleeter#606]
I want to use GPU
so I  run ：docker run --runtime=nvidia -v $(pwd)/output:/output deezer/spleeter-gpu separate -o /output -i audio_example.mp3

have an error:docker: Error response from daemon: Unknown runtime specified nvidia.[Discussion] your question

**Comment by hjing100** [comment]
docker: Error response from daemon: manifest for deezer/spleeter-gpu:latest not found: manifest unknown: manifest unknown.

**Comment by mogita** [comment]
Similarly, specifying `deezer/spleeter` for "docker run" command showed the same error.

**Comment by romi1502** [comment]
Hi @hjing100,
I couldn't reproduce your issue on a GPU-equipped computer (with driver version 430.14 and CUDA Version 10.2).
The message seems to say that you don't have a proper nvidia/CUDA install on your computer. You need to have a NVIDIA compatible GPU on the computer and to have a proper CUDA install to run spleeter on GPU.
If you do have an CUDA install, it may be an issue with the version of the driver or of CUDA. Make sure to have CUDA 10.1 or more and a compatible driver version.
If you still can't get an error, try to match the versions with the ones I tried.
