### ISSUE TITLE
Support files longer than 600 seconds / segmenting?

### ISSUE THREAD

**Issue by junh1024** [deezer/spleeter#61]
## Description

I assume it can only support files <=  600 seconds so I'd like longer support. What if I want to separate a concert?

A way to do this, if you're not already doing so, would perhaps be to divide the audio into 1 minute segments and process them with overlap, and that might reduce RAM use, too.

**Comment by ZFTurbo** [comment]
You can set required duration in function:

`separator.separate_to_file(input_file, out_dir, duration=6000, codec='mp3', bitrate='320k')`

By default it's 600 but can be any.

**Comment by big-jg** [comment]
I have changed every instance of 600 to 1200, it still reads and outputs at 600.

**Comment by big-jg** [comment]
Can anyone help with this please?

**Comment by fortym2** [comment]
You can use ffmpeg to split your input file in smaller segments . For example:
`ffmpeg -i track.flac -f segment -segment_time 600 -c copy %d.flac`

That will split `track.flac` in `0.flac`, `1.flac`, ..., `n.flac`.

Now run Spleeter on these little tracks, and you will get something like:

```
./output/0/drums.wav
./output/0/...
./output/1/drums.wav
./output/1/...
./output/.../...
```

Now you need to put the instruments back together.  ffmpeg can do this job too (see [concatenation](https://trac.ffmpeg.org/wiki/Concatenate)).

For example, assuming that you have a `drums.txt` containing the paths of the `drums.wav` files (in order), you can run:

`ffmpeg -f concat -safe 0 -i drums.txt -c copy drums.wav`

**Comment by romi1502** [comment]
The `-d` option of `spleeter separate` makes it possible to process file longer than 600s:
`spleeter separate -i input_audio.mp3 -d 735 -o /output`
Just be aware that separating long files will require a lot of RAM.

@big-jg, I just double check the `-d` option and the `duration` parameter of the `Separator.separate_to_file` (as mentioned by @ZFTurbo ) and I have no trouble processing file longer than 600s with both method.

**Comment by big-jg** [comment]
Thanks romi1502 I cannot find that line anywhere? i've looked in every document in spleeter code.
