### ISSUE TITLE
[Discussion] Mono processing

### ISSUE THREAD

**Issue by aughey** [deezer/spleeter#610]
I'm processing real-time microphone audio through Spleeter in an attempt to separate the actual voice from extraneous music picked up by the vocal mics.  It's working quite well.

I'd like to optimize my processing.  Currently, I'm duplicating the samples and passing a stereo signal to be split because that is how all of the examples work.  There are recent commits that address mono streams.  Is there anything special I need to do in order to setup a filter to process mono instead of stereo channels?

**Comment by romi1502** [comment]
Hi @aughey,
spleeter indeed processes audio in stereo. You can input mono files, but it will just duplicate the channel to stereo before processing.
If you'd like to do mono processing for optimization purpose, that should be feasuble by tweak the [Keras Model](https://github.com/deezer/spleeter/blob/master/spleeter/model/functions/unet.py), the [tensorflow estimator](https://github.com/deezer/spleeter/blob/master/spleeter/model/__init__.py) and some parts of the [separator](https://github.com/deezer/spleeter/blob/master/spleeter/separator.py), where the number of channel was hardcoded to `2`.
