### ISSUE TITLE
[Bug] The INFO won't show up until I press ctrl + c

### ISSUE THREAD

**Issue by ChenJingZhuo** [deezer/spleeter#611]
![image](https://user-images.githubusercontent.com/36926346/114834703-6adeaa00-9e03-11eb-9933-2ed0aaaace5b.png)

![image](https://user-images.githubusercontent.com/36926346/114834946-a7120a80-9e03-11eb-8af9-9aabd72ec524.png)

How can I get information to be displayed as it is executed？

**Comment by romi1502** [comment]
Hi @ChenJingZhuo,
I'm not sure I understand your issue.
If you want more details on the proceedings of the separation you may use the `--verbose` option of `spleeter separate`.
If this is just your terminal not flushing the standard output correctly, I think it may not be a spleeter related issue.

**Comment by ChenJingZhuo** [comment]
![image](https://user-images.githubusercontent.com/36926346/114903030-f75f8b80-9e48-11eb-91f6-6ca958d53048.png)

Great, it successfully displays the execution information, thank you!
