### ISSUE TITLE
(forward) Compatibility with tensorflow 2.5.0

### ISSUE THREAD

**Issue by ananda2nb** [deezer/spleeter#613]
Is tensorflow 2.3.0 a must for spleeter? I have python 3.9 with tensorflow 2.5.0 and when installing spleeter through pip, it says,
```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from spleeter)
ERROR: No matching distribution found for tensorflow==2.3.0
```

**Comment by mmoussallam** [comment]
Hi @ananda2nb 

So far we only tested and packaged spleeter for python versions between 3.6 and 3.8.  It's possible that it works on 3.9 too but we haven't tested yet

**Comment by JeffreyCA** [comment]
Hi @mmoussallam, are there any plans to support newer versions of tensorflow?
