### ISSUE TITLE
Error: AttributeError: module 'ffmpeg' has no attribute '_run'

### ISSUE THREAD

**Issue by afolabiaji** [deezer/spleeter#615]
- [x ] I didn't find a similar issue already open.
- [x ] I read the documentation (README AND Wiki)
- [x ] I have installed FFMpeg
- [ x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

When running spleeter to extract stems from a song. I keep getting this error message:

`File "/Users/afolabi/Library/Python/3.8/lib/python/site-packages/spleeter/audio/ffmpeg.py", line 102, in load
    except ffmpeg._run.Error as e:
AttributeError: module 'ffmpeg' has no attribute '_run'`

I've installed ffmpeg and read the docs. I've googled extensively for this but can't find anything.

**Comment by Robin-Dong** [comment]
Try to reinstall `ffmpeg-python` , I encontered this issue because i installed spleeter before installing `ffmpeg`. After reinstall  the `ffmpeg-python`, it fixed the problem. Hope this helps.

**Comment by afolabiaji** [comment]
I’ve fixed the issue. I saw your thread and tried your solution but it didn’t work for me.

The problem, I think, was that my Mac is running two different versions of python.

So I had to follow this article: 
https://opensource.com/article/19/5/python-3-default-mac

Then delete and then reinstall everything, then everything worked fine.

**Comment by FabrizioSant** [comment]
Hey I was having the same issue and reinstalling ffmpeg-pyhon at the end made it work as the comment above.

the working set up process is to install spleeter first with 'pip install spleeter', then download the ffmpeg  .exe binaries (set up the environment virable too) and then install the ffmpeg-python with 'pip install ffmpeg-python'.
