### ISSUE TITLE
[Bug] NameError: name 'static_mix' is not defined

### ISSUE THREAD

**Issue by samya-ak** [deezer/spleeter#617]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description
audio/ffmpeg.py seems to have undefined identifier called static_mix
installed ffmpeg-python 0.2.0 and spleeter 2.2.2 via pip

## Step to reproduce
Ran following code
```python
import numpy as np
from spleeter.separator import Separator
from spleeter.audio.adapter import AudioAdapter
import spleeter.utils.logging as Log

Log.configure_logger(True)

inputPath = 'songs/test.mp3'
outputPath = 'output/'

audio_loader = AudioAdapter.default()
sample_rate = 44100
waveform, _ = audio_loader.load(inputPath, sample_rate=sample_rate)

separator = Separator('spleeter:2stems')
prediction = separator.separate(waveform)
data = np.zeros_like(prediction['vocals'])

parts = {
            'vocals': True,
            'accompaniment': False
        }

for key in prediction:
    if parts[key]:
        data += prediction[key]

audio_loader.save(outputPath, data, 44100, 'mp3', '256k')
```
## Output

```powershell
Traceback (most recent call last):
  File "split.py", line 31, in <module>
    audio_loader.save(outputPath, data, 44100, 'mp3', '256k')
  File "C:\Users\...\env\lib\site-packages\spleeter\audio\ffmpeg.py", line 180, in save
    process.stdin.write(static_mix.astype("<f4").tobytes())
NameError: name 'static_mix' is not defined
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type |  pip         |
| RAM available     |6 GB                            |
| Hardware spec     | n/a            |

**Comment by romi1502** [comment]
Hi @samya-ak,
line 180 of [spleeter\audio\ffmpeg.py](https://github.com/deezer/spleeter/blob/master/spleeter/audio/ffmpeg.py) should not be:
```python
    process.stdin.write(static_mix.astype("<f4").tobytes())
```
as reported in your error, but: 
```python
    process.stdin.write(data.astype("<f4").tobytes())
```
So it seems you're not using a clean version of spleeter.
You should then make sure to use a clean version.
