### ISSUE TITLE
Music segments (start and end time) for stems

### ISSUE THREAD

**Issue by TheCidRMC** [deezer/spleeter#618]
## Description

Hi. Thanks for this amazing tool, really appreciate it. Is there a way to output start and end time segments from stems? I mean, the model already identifies which parts of the audio are associated to different types of stems, could it be possible to output those ranges of time (starts and ends) maybe in seconds or mili seconds?

Thanks you a lot guys.

**Comment by romi1502** [comment]
Hi @TheCidRMC 
I'm not sure I get your question. To make things clear, given an audio file as input, spleeter outputs several stem files (2, 4 or 5 depending on the model), all of which are exactly as long as the input file. 
You can possibly only process a segment of the input audio file using the `offset`(`-s`) and `duration` (`-d`) option of the `separate` command. This will results in stems of duration given by the second argument.

If you're interested in the part where a particular stem (let say drums) is active, you need to detect silence in it.
