### ISSUE TITLE
gpu install uses cpu only 

### ISSUE THREAD

**Issue by PistonIntJack** [deezer/spleeter#620]
hello,
when I install spleeter-gpu , I can use spleeter separate  -o ./ -p spleeter:2stems -i ./a.wav
but when I use python_code  spleeter.separator._separate_librosa(self, y, audio_id="")
CPU is OK， but GPU has an error
error message ValueError: Cannot feed value of shape (165, 2049, 2) for Tensor 'waveform:0', which has shape '(None, 2)'

Ubantu and cuda 10.1
thank you

**Comment by romi1502** [comment]
Hi @PistonIntJack,
note that the `spleeter-gpu` is no longer supported and that the base `spleeter` package should support GPU.
