### ISSUE TITLE
[Feature] Identify language of vocals

### ISSUE THREAD

**Issue by grr** [deezer/spleeter#624]
## Description

Since spleeter can extract the vocals, I'd like to have be able to identify the language(s) used. There doesn't appear to be any existing software or service that does this yet and there aren't any music databases I have found that track this info either. The only way to currently get this info is to manually curate tag data or playlists.

**Comment by romi1502** [comment]
Hi @grr,
Lyrics language identification from lyrics is actually quite a different challenge, and this is not something that will be added to spleeter.
However, we've also worked on this topic and will present a paper about it at the next ICASSP conference (but we don't plan to release the models) : 
https://2021.ieeeicassp.org/Papers/ViewPaper.asp?PaperNum=4075
