### ISSUE TITLE
[Bug]  output files are always 10 min in length 

### ISSUE THREAD

**Issue by Jonathan-Hoover** [deezer/spleeter#628]
I'm sorry if this isn't okay to ask here but no matter what I do the output files from this program return audio files that are 10 minutes long and no longer.

 I'd really appreciate some help in figuring out what's going wrong it's most likely my fault,  I've been using the program to remove non-vocal sounds from old casette tape recordings of my grandfather for his kids. 

 any hints would be greatly appreciated and I'm sorry for intruding

**Comment by taylordotfish** [comment]
The default duration is 600 seconds—you need to pass the `-d` option to change it.

For example, to process 30 minutes instead:

```bash
spleeter separate -d 1800 file.wav
```

**Comment by Jonathan-Hoover** [comment]
> The default duration is 600 seconds—you need to pass the `-d` option to change it.
> 
> For example, to process 30 minutes instead:
> 
> ```shell
> spleeter separate -d 1800 file.wav
> ```

Thank you! I'm sorry for the dumb question,
