### ISSUE TITLE
[Bug] Can't get it to start

### ISSUE THREAD

**Issue by rdel327** [deezer/spleeter#63]
Outputting a warning so far.
(spleeter-cpu) Roberts-MBP-2:Desktop USER$ spleeter separate -i someoneinthecrowd.mp3 -p spleeter:2stems -o output
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:spleeter:Extracting downloaded 2stems archive
INFO:spleeter:2stems model file(s) extracted
INFO:spleeter:Loading audio b'someoneinthecrowd.mp3' from 0.0 to 600.0
WARNING:spleeter:module 'ffmpeg' has no attribute 'probe'

ffmpeg was installed using pip, then decided to try brew. Using os x

**Comment by tob-har** [comment]
Similar issue here:

(spleeter-cpu) tobhar:~ t.hartmann$ spleeter separate -i audio_example.mp3 -o audio_output
INFO:spleeter:Loading audio b'audio_example.mp3' from 0.0 to 600.0
WARNING:spleeter:ffprobe error (see stderr output for detail)




See verbose logs here:

(spleeter-cpu) tobhar:~ t.hartmann$ spleeter separate -i audio_example.mp3 -c wav -o audio_output --verbose
INFO:tensorflow:Using config: {'_model_dir': 'pretrained_models/2stems', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': gpu_options {
  per_process_gpu_memory_fraction: 0.7
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1356ab0b8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From /Users/t.hartmann/opt/miniconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/model/functions/unet.py:28: The name tf.keras.initializers.he_uniform is deprecated. Please use tf.compat.v1.keras.initializers.he_uniform instead.

INFO:tensorflow:Apply unet for vocals_spectrogram
INFO:tensorflow:Apply unet for accompaniment_spectrogram
INFO:tensorflow:Done calling model_fn.
WARNING:tensorflow:From /Users/t.hartmann/opt/miniconda3/envs/spleeter-cpu/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
WARNING:tensorflow:From /Users/t.hartmann/opt/miniconda3/envs/spleeter-cpu/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from pretrained_models/2stems/model
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.int32
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.string
INFO:spleeter:Loading audio b'audio_example.mp3' from 0.0 to 600.0
WARNING:spleeter:ffprobe error (see stderr output for detail)


... any help? Idea?

**Comment by mmoussallam** [comment]
You probaly have an invalid ffmpeg installation. `pip` only installs python wrappers,not the actual `ffmpeg` executable.

**Comment by gibe9000** [comment]
I am having a similar problem, getting the same error message

WARNING:spleeter:module 'ffmpeg' has no attribute 'probe'

I installed ffmpeg via a zip from https://ffmpeg.zeranoe.com/builds/
Also made a PATH to the bin folder of ffmpeg but still nothing

**Comment by tob-har** [comment]
It is all about not getting the correct path to input and/or output file/folder.

Just use the complete path to your input audiofile for the terminal commands (like: user/audiofiles/audiofile.wav)

Same for the output folder.

And avoid spaces. Use underscore, minus or no space instead.
Then it should work.
