### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment:[Discussion] your question

### ISSUE THREAD

**Issue by surajk150741** [deezer/spleeter#632]
Hi, I am upgrading the version of tensorflow from 1.14.0 to a value greater than or equal to 2.2 in Anaconda navigator's environment "tsa_course", but I am getting this error:

UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment
argon2-cffi -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
bleach -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
grpcio -> python[version='>=2.7,<2.8.0a0']
h5py -> python[version='<3']
html5lib=1.0.1 -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
 And the list goes on....

Current system: Python 3.7.2, Windows 10, Cython 0.29.23

Can anyone help me update the version of tensorflow in my tsa_course environment

**Comment by romi1502** [comment]
Hi @surajk150741,
This does not seem to be a spleeter related issue, but a tensorflow one, so I suggest you report it on the appropriate github repository.
