### ISSUE TITLE
[Feature] Using provided instrumental for enhanced vocals separation

### ISSUE THREAD

**Issue by LilyStilson** [deezer/spleeter#634]
## Description

What about allowing user to optionally provide an instrumental track for Spleeter to work on? I don't know if it's possible or not, but I think that it would better understand what is going vocals, and it doesn't need to separate accompaniment, because it's already provided.

## Additional information

Currently Adobe Audition can do sort of the same thing (using Sound Model and Sound Remover effect), but it relies on calculations and some in-house algorithm. I think. if there is will be AI involved in process, then vocals separation could be much more accurate and Spleeter won't confuse vocals for instruments.

**Comment by romi1502** [comment]
Hi @LilyStilson,
Indeed adding extra information from the available instrumental track could help separating the vocal track. 
However, this would require quite a different architecture and retraining models to support this feature, so we probably won't include anything like this in spleeter in the near future.
Thanks for the suggestion!
