### ISSUE TITLE
[Discussion] Tensorflow OOM, how to avoid?

### ISSUE THREAD

**Issue by mitsukuri** [deezer/spleeter#64]
Hello, I'm getting Tensorflow OOM errors on my GPU if I don't limit the length of audio to process (`--max-duration`). I've figured out that the upper limit for my hardware is `--max-duration 202`, i.e. 3m22s.

Is there any way to configure Spleeter to raise the max duration while avoiding OOMs?

**Comment by Faylixe** [comment]
No you can't. You need either much more memory or you need to process your track by chunk (splitting manually your track and process each chunk with the library).

**Comment by ofshellohicy** [comment]
when chunk music, the duration around chunk meet bad process
