### ISSUE TITLE
[Feature] Select which tracks to process

### ISSUE THREAD

**Issue by gazugafan** [deezer/spleeter#642]
## Description

I'd like to be able to select which parts of a model to process.

For example, instead of generating both the vocals and accompaniment, generate just the accompaniment. In my project, the vocals aren't necessary, so it seems like only generating the accompaniment would cut the processing time in half.

Maybe this feature already exists? I made a naive attempt to do this by removing "vocals" from the instrument_list in the 2stem config file. This only generated an accompaniment.wav file, as I hoped! But, the result was just the original audio. Neither the vocals or accompaniment were isolated.

Possibly a duplicate of #8

**Comment by romi1502** [comment]
Hi @gazugafan,
it would be possible to generate only the accompaniment part and not the vocals one, but anyway you'll have to go through the whole model for computing the mask (this means the model still has to estimate a vocal spectrogram to be able to estimate the accompaniment separation mask), so you won't cut the processing time in half. In particular, if you're not using GPUs, I expect the computation gain to be quite low. 
The operations you can save are the inverse Fourier transform of the vocals, and possibly the export of the audio waveforms (to whatever supported audio file). For saving on the second one, you can simply use the python API and load

**Comment by gazugafan** [comment]
Yeah, if the speed gains will be minimal, then there's not much point. Thanks for the detailed info!
