### ISSUE TITLE
it show error..on runing,please help me..

### ISSUE THREAD

**Issue by TheOneCrew** [deezer/spleeter#643]
Some people say i need python version 3.7.5,so i download this version python also and use vitrual enviroment to use.I install spletter using cmd in PyCharm.It install without any problem.
I always show the error :
"Usage: spleeter separate [OPTIONS] FILES...
Try 'spleeter separate --help' for help.

Error: Missing argument 'FILES...'."
I am also download spleeter GUI :

i am just waiting and waiting.....
Please help me it has been last 3 weeks,but i dont find any solution.
![sendToLink](https://user-images.githubusercontent.com/72298831/126890701-ffe760f2-5d70-41d1-9615-dae85fad318d.PNG)
![sendToLink2](https://user-images.githubusercontent.com/72298831/126890706-6982d763-c8e0-4b12-9060-a3f4d0d8fc17.PNG)

**Comment by Joldiges** [comment]
@TheOneCrew, the current version of sleepter doesn't use '-i'.  please remove the argument and then it shall work.
