### ISSUE TITLE
to get help for using spleeter

### ISSUE THREAD

**Issue by TheOneCrew** [deezer/spleeter#644]
i also try / and // and "" around file address.It is not working, what am i doing wrong.

**Comment by Joldiges** [comment]
"Not working" is only of the worst phrases in asking for help.
Please give more details.  In what way is it not working?  Any error messages?

**Comment by a122760** [comment]
> i also try / and // and "" around file address.It is not working, what am i doing wrong.

Although you are very vague, I guess I probably know what you are talking about; this is caused by a bug in line 527 of "dataset.py", you can set the configuration file like this: "training_cache": "exp/training_cache", "validation_cache":"exp/validation_cache".
