### ISSUE TITLE
Script blows up wit h errors

### ISSUE THREAD

**Issue by Lexxos** [deezer/spleeter#657]
It seems that your repository is missing very crucial code source on Ubuntu 20.04; to fix:
sudo apt install python3-opencv

**Comment by romi1502** [comment]
As I don't have any troubles running the latest version of spleeter on Ubuntu 20.04 following the [recommended installation steps](https://github.com/deezer/spleeter/blob/master/README.md#quick-start) I close this issue.

**Comment by Lexxos** [comment]
awful developer.
