### ISSUE TITLE
[Discussion] Is it possible to get output in 48000 Hz instead of 44100 and about mono output?

### ISSUE THREAD

**Issue by dilnix** [deezer/spleeter#661]
Isn't it possible to make output the same 48000 Hz for input files with the same sample rate?
Also, isn't it possible to make output same mono (1 channel) as an input file?
Didn't find how to make so from WiKi.
I mean with just a CLI, with setting some parameters on starting "spleeter separate...".

**Comment by MohammedMehdiTBER** [comment]
I guess there is no way but to use a config file and edit it to fit your output needs.

**Comment by dilnix** [comment]
> I guess there is no way but to use a config file and edit it to fit your output needs.

Ok, I understand how to use a config... by option -p with declaring a config file name... but what I don't understand is what this config file must contain to reach my target.
Could somebody show the example?

**Comment by MohammedMehdiTBER** [comment]
> > I guess there is no way but to use a config file and edit it to fit your output needs.
> 
> Ok, I understand how to use a config... by option -p with declaring a config file name... but what I don't understand is what this config file must contain to reach my target.
> Could somebody show the example?

The config file is uploaded in the repos itself:
https://github.com/deezer/spleeter/tree/master/configs
Download the one that you like, depending on the stem.
Don't use this for listening or spreading music. 
I am disowning music in my religion.
This help is just for educational purposes to use it to remove music to listen to vocals only.

**Comment by romi1502** [comment]
Hi @dilnix,
All processing in spleeter is done in stereo at 44.1kHz. So whatever the format of your input, it will be converted to stereo 44.1kHz, and spleeter will output audio files in this format.
There is no option in spleeter to set this at the moment but it should be doable to add it by tweaking the [`save`](https://github.com/deezer/spleeter/blob/master/spleeter/audio/ffmpeg.py) method of the `FFMPEGProcessAudioAdapter`.

**Comment by romi1502** [comment]
Note that you'd better use the `spleeter:2stems-16kHz` config in order to get separation up to 16kHz (instead of 11kHz for the `spleeter:2stems` config).
If you think accompaniment is not good enough and you're ready to trade leftovers against artefacts, you may try to blend the separated accompaniment with the separated vocals (with a quite low gain). This may help a bit, but don't expect miracles.

**Comment by dilnix** [comment]
@romi1502 
Yes, I tried exactly with `spleeter:2stems-16kHz` and it's maybe better, but it's not easily understood by ear.
Thanks for the suggestion, I will try to make some blends with maybe a peak compression too.
But the most I'm looking for is to return not all voice, but parts like "ah", "oh", sneezing, coughing, sighing etc.
If you'll have some ideas about it, please share.
