### ISSUE TITLE
[Discussion] Spleeter using Legacy TF 1.15 and DirectML

### ISSUE THREAD

**Issue by RoARene317** [deezer/spleeter#662]
Is there any plans to support TF 1.15 and DirectML? This is very useful especially for who doesn't have NVIDIA cards.

**Comment by romi1502** [comment]
Hi @RoARene317,
There are old versions of spleeter still available on pypi/conda-forge that support TF 1.15. For instance [spleeter 1.5.4](https://pypi.org/project/spleeter/1.5.4/) uses tensorflow 1.15.2.
Regarding DirectML, there is no plan for supporting it.
