### ISSUE TITLE
[Bug]  output successfully yet incomplete(missing the final one-two minutes)

### ISSUE THREAD

**Issue by gulee100** [deezer/spleeter#664]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

output successfully yet incomplete(missing the final one-two minutes)

## Step to reproduce

1. Installed using `...`
2. Run as `...`
3. Got `...` error

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows / Linux / MacOS / other |
| Installation type | Conda / pip / other             |
| RAM available     | XGo                             |
| Hardware spec     | GPU / CPU / etc ...             |

**Comment by romi1502** [comment]
Hi @gulee100,
Is your processed file longer than 10 minutes? the `-d` or `--duration` parameter makes it possible to limit the duration of the processed audio in the input files. Its default value is 600s (=10min) as a safeguard, so if you don't overwrite it, any file longer than 10 minutes won't be processed entirely.  It may explain your issue.

**Comment by gulee100** [comment]
> Hi @gulee100,
> Is your processed file longer than 10 minutes? the `-d` or `--duration` parameter makes it possible to limit the duration of the processed audio in the input files. Its default value is 600s (=10min) as a safeguard, so if you don't overwrite it, any file longer than 10 minutes won't be processed entirely. It may explain your issue.

Thank you so much for your help!
