### ISSUE TITLE
Is it possible to do fast batch processing using a GPU?

### ISSUE THREAD

**Issue by neonbjb** [deezer/spleeter#668]
I want to use spleeter to clean up a large quantity of audio files (>10M). When running on the GPU, however, there is some bottleneck that is severely constraining the program: I see less than 1% GPU utilization on average.

I can readily reproduce the issue by running this script in a directory with a large number of files and watching the GPU utilization using `nvidia-smi`: https://github.com/deezer/spleeter/issues/44

If I wire up my dataset to the [pytorch variant](https://github.com/tuan3w/spleeter-pytorch), I get >100x more performance. The problem is that those implementations have some bug that causes the model to not perform well.

Is there some trick to improving batch performance on TF?

- Using Spleeter v2.3.0
- Ubuntu
- GPU is RTX 3090. Processor is EPYC 7502.

**Comment by romi1502** [comment]
Hi @neonbjb,
Yes, there seems to be troubles with GPU usage on spleeter v2.3.0. For some reasons I can get the processing to be done on GPU. We need to investigate further what's wrong. In the meantime, an older version (such as 2.2.1) should do the trick: using the docker image `deezer/spleeter-gpu:3.8` (that uses spleeter 2.2.1) with nvidia-docker, I could process more than 3h audio in less than 2 minutes with the 4stems model on a single nvidia Titan X.

**Comment by romi1502** [comment]
Ok, I've managed to make spleeter v2.3.0 work on GPU. 
I just had a CUDA version compatibility issue.
As spleeter v2.3.0 uses tensorflow 2.5, it requires CUDA 11.2 (with proper driver version) + CuDNN 8. So make sure you have a proper CUDA install to make tensorflow 2.5 work.
With this, I could again process more than 3h of audio in less than 2 minutes, with a quite heavy GPU usage.

**Comment by neonbjb** [comment]
Hey, I appreciate the debugging. I tried your suggestion but it did not seem to affect performance. I managed to get what I wanted to done with the torch repo, so I no longer need any help. This is honestly probably just due to my naivete with tensorflow, closing.
