### ISSUE TITLE
[Bug] Typo In README

### ISSUE THREAD

**Issue by rohit-yadav** [deezer/spleeter#67]
Under **Quick start** subheading there is a typo in `git clone https://github.com/Deezer/spleeter`. Instead of the capital **D**, it should be small **d**. 

`git clone https://github.com/deezer/spleeter` -- this is the correct link

Fixing this will allow anyone to clone the repository effortlessly.

**Comment by mmoussallam** [comment]
Hi Rohit.

Both urls are valid (capital of lowercase d) do you have an example configuration where it does make a difference ?

**Comment by rohit-yadav** [comment]
Hello Mmoussallam,

If you try to git clone with the capital D in the link, it will not download and throw an error.

**Comment by Faylixe** [comment]
As seen in associated PR not considering this at the moment. Closing.
