### ISSUE TITLE
[Discussion] raise ValueError

### ISSUE THREAD

**Issue by itubal** [deezer/spleeter#674]
File "/home/josema/.local/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1291, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

Sorry for my English. The system works fine with 2 streams but not for 4 streams. Thankyou for yor attention

**Comment by JalaJalera** [comment]
Did you use the spleeter:4stems preset? I have same problem. It seems that the pretrained model is not on the download page: https://github.com/deezer/spleeter/releases/download/v1.4.0/4stems.tar.gz
yields an error 404 (at least for me)
https://github.com/deezer/spleeter/releases/download/v1.4.0/5stems.tar.gz
and https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
are working fine.
One workaround for you could be to use the 2stems or 5stems preset.
I opned a new issue: https://github.com/deezer/spleeter/issues/675

**Comment by itubal** [comment]
Yes, the download link is broken.
5strem... Good idea. I'll try this in 2 hours.

Enviado desde un Smarphone. Algunas palabras pueden contener fallos de
digitación.

**Comment by JalaJalera** [comment]
Now the Download Link works for me: https://github.com/deezer/spleeter/releases/download/v1.4.0/4stems.tar.gz
Simply extract it to the folder "pretrained_models/4stems/"

**Comment by itubal** [comment]
Thankyou. I'll try in a few minutes.
Thankyou so much

Enviado desde un Smarphone. Algunas palabras pueden contener fallos de
digitación.

**Comment by romi1502** [comment]
This seems to be the same issue as #675 so I close this one
