### ISSUE TITLE
[Discussion] A concise script of Python for Spleeter

### ISSUE THREAD

**Issue by abokhalel2** [deezer/spleeter#679]
I'm trying to make a concise and a short python script to run the Spleeter Project.

My project requires the python code for Spleeter to be easier to read and follow. Everything seems to work well for "2stems vocals" except a small issue. The result of my script seems to add a small noise (I used Audacity to visualize it).

![ScreenShot](https://user-images.githubusercontent.com/12386020/141662784-1688375e-e18c-4b63-aad1-8926fb80f2b3.jpg)

Does anyone know what causes these types of noises? i can't wrap my head around it. I'm worried about the effect that they may cause on the audio results.

Here is my Python code:
https://github.com/abokhalel2/Spleeter-Pytorch

Any suggestions would be greatly appreciated!

**Comment by romi1502** [comment]
Hi @abokhalel2,
from what I understand, your issue is not linked to a bug in Spleeter but in your own code. So I think it should not be reported in Spleeter issues, and I'll close it.
Feel free to reopen and give further details if I got mistaken.
