### ISSUE TITLE
Can I force Spleeter to run only on CPU even if I have a GPU installed?

### ISSUE THREAD

**Issue by Tetsujinfr** [deezer/spleeter#680]
## Description

Can I force Spleeter to run only on CPU even if I have a GPU installed?

## Additional information

I did not see this option in the spleeter --help options. My GPU setup does not run successfully so I wanted to try Spleeter only on CPU but got stuck there. Do not know how to force it to use CPU.
Hopefully a simple flag to change somewhere in the codebase but I would need to know where to search.
Thanks a lot

**Comment by romi1502** [comment]
Hey @Tetsujinfr,
There is no option to force spleeter running on CPU. 
If you don't have a proper CUDA install, spleeter should default to CPU.
If you want to force it, the a good option is to set the `CUDA_VISIBLE_DEVICES` to an empty string in the shell where you'll run spleeter:
```sh
export CUDA_VISIBLE_DEVICES=""
```
Tensoflow should then ignore GPUs and run on CPU.

**Comment by Tetsujinfr** [comment]
Ok thank you, I ll you that trick then. Closing this issue.
