### ISSUE TITLE
[Discussion] Creating Karaoke tracks

### ISSUE THREAD

**Issue by arsaboo** [deezer/spleeter#69]
I was wondering if anyone could help create a simple python program to create karaoke tracks using this. Here's what I did manually, so far:

1. Download the video from youtube into audio and video tracks:
`youtube-dl -f bestvideo+bestaudio https://www.youtube.com/watch?v=U4xPahDjY6k`

2. Manually rename the output files to `audio.webm` and `video.webm` respectively. 

3. Next, use Spleeter to separate vocals from the audio track:
`spleeter separate -i spleeter/audio.webm -p spleeter:2stems -o output`

4. Manually merge the video file and `accompaniment` file using Photoshop. I guess I can use ffmpeg to do that. 

It should be a trivial exercise for anyone with some Python skills.

**Comment by mmoussallam** [comment]
This is not an appropriate place for this discussion. 
A word of advice: You are responsible for your usage of this tool and you should be wary of copyright infringement issues that may arise from what you're suggesting.

**Comment by tlk** [comment]
Experiment with Google Colab: https://gist.github.com/tlk/e4872f9dd8a418a29966c4dafc2664f2
