### ISSUE TITLE
Hello , Can anyone share me requirements to run spleeter-gpu on GPU server . Including CuDa , Cudnn and tensorflow  version

### ISSUE THREAD

**Issue by ravi35663** [deezer/spleeter#690]

**Comment by romi1502** [comment]
Hi @ravi35663
you should no longer use `spleeter-gpu` that is deprecated and just use `spleeter` that support GPU.
With a proper install of CUDA 11.2 and CuDNN 8, `spleeter` should run on GPU.
I've just tested it on a GTX 1080 with Driver 460.84 and CUDA 11.2.

**Comment by ravi35663** [comment]
Hello @romi1502 
Please shared benchmarking that you have mentioned with these details

**Comment by DevOps-Hestabit-1** [comment]
> GTX 1080

Do you have any benchmarking on this, If yes, please share with me

**Comment by DevOps-Hestabit-1** [comment]
is that, spleeter-gpu library deprecated ?
