### ISSUE TITLE
[Bug] Crash on Apple Silicon

### ISSUE THREAD

**Issue by kakyoism** [deezer/spleeter#692]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

Running on M1X, spleeter crashes immediately.

## Step to reproduce

1. Install using `pip install spleeter` in a Rosetta-enabled Terminal
2. Run spleeter 2-stem example
3. Got `Illegal instruction: 4` error

## Output

```bash
$ spleeter separate -p spleeter:2stems -o ~/Desktop/ “my.mp3"
Illegal instruction: 4
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | MacOS |
| Installation type | pip |
| RAM available     | 64GB |
| Hardware spec     | CPU: Apple Silicon M1X |

**Comment by romi1502** [comment]
Hi @kakyoism,
indeed, spleeter does not work as is on Apple Silicon M1 chips, even using a Rosetta terminal.
But we managed to make it work mostly natively on such chips. We'll add it in the README/Wiki soon.
In the meantime you can try the solution of issue #696 which seems to work.
