### ISSUE TITLE
[Feature] Adding new string instruments like violin and cello 

### ISSUE THREAD

**Issue by stenalpjolly** [deezer/spleeter#70]
## Description

Currently there no support for string based instrument. It’s would much appreciated if we can have support for string based instruments like violin and cello

**Comment by veltzerdoron** [comment]
I second that motion, tried all stems on classical music and no separation is done, (flute/ piano would also be nice for something specific I'm working on)

**Comment by Faylixe** [comment]
We only provide model trained for performing separation of specific instrument and string is not included. To do so you need to train your own model with a dedicated dataset for those instrument.
