### ISSUE TITLE
how do you open spleeter

### ISSUE THREAD

**Issue by MetalManZ** [deezer/spleeter#703]
I looked into the folders and I didn't see a .exe file. Can someone please tell me how to open the application?

**Comment by mmoussallam** [comment]
Hi @MetalManZ 

We do not package Spleeter as a windows executable, you'll need to [install it](https://github.com/deezer/spleeter/wiki/1.-Installation) and then use it through a command prompt. Note that there exists some user interfaces built around Spleeter but it's not part of this project and we do not provide any support for them.

Hope this helps, and happy new year.
