### ISSUE TITLE
[Discussion] Can I train a model to separate different types of instruments? 

### ISSUE THREAD

**Issue by go-dustin** [deezer/spleeter#706]
Is this code specific to Vocals, Drums, Bass, Accompaniment or can I train the model to extract different track types? Such as Electric Guitar, Synths, Pads, etc? 

I have a few use cases in mind but the first I'd focus on is splitting drum loops up by different percussion types. So Kick, Snare, High Hats, Pitched drums (Toms, Congos, etc), FX, etc. 

I can easily make a data set of millions of loop variations that I can use train the model. I'm just not sure if the code does anything that is specific to the type of sound being extracted.

**Comment by romi1502** [comment]
Hi @go-dustin,
you can definitely try to separate other instruments than the one of the pre-trainer spleeter models. If the instruments you want to separate have clearly different features (e.g kick vs snare), that should work quite well.

**Comment by go-dustin** [comment]
Thanks @romi1502 this is a very exciting prospect. I believe a good use case for musicians is to split drum loops into their constituent parts, so the parts can be edited individually. I'll report back my findings and provide examples.
