### ISSUE TITLE
[Feature] Progress of process

### ISSUE THREAD

**Issue by aidv** [deezer/spleeter#71]
## Description

I'd love to get some way to get the progress of what's going on with the song.
Say, percentage or ETA.

## Additional information

Having lot's of fun.

**Comment by Faylixe** [comment]
Hi, we will try to dig this in the next iteration of Spleeter. Although I think there is no way to do so (we rely on Tensorflow for the whole operation so it will only depend of mean to display progress with it). If you have option for estimator prediction monitoring do not hesitate to submit PR.
