### ISSUE TITLE
[Bug] Docs are inconsistent with respect to install

### ISSUE THREAD

**Issue by mattpetters** [deezer/spleeter#720]
- [x] I didn't find a similar issue already open. (I did but doesn't seem like anything has been addressed on the situation)
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

The documentation gives conflicting messages about whether or not to use Conda for dependency install. If Conda is "not recommended" as the docs now indicate the steps for alternative install should be laid out (ie; instructions to install dependencies with pip, whatever). `pip install spleeter` is not sufficient.

## Step to reproduce

1. Visit the README or the install document with no prior context and notice how Conda is not recommended and conda commands are still present in the document.

**Comment by dustyny** [comment]
@mattpetters the documentation doesn't say not to use conda it says not to install spleeter using conda. 

"Note that we no longer recommend using conda for installing **spleeter**." 

while the conda command is used to install ffmpeg & libsndfile. ffmpeg & libsndfile are completely different packages and are used by Spleeter but are not a part of the spleeter project. 

"conda install -c conda-forge ffmpeg libsndfile"

**Comment by mattpetters** [comment]
Oh, that clears it up. I think my reading of it was that conda shouldn't be used period. Thanks for this.

**Comment by dustyny** [comment]
Not a problem... I can see how you'd make that mistake..
