### ISSUE TITLE
Downloading Pretrain models to all folders 

### ISSUE THREAD

**Issue by sudheervdm** [deezer/spleeter#723]
I have some file in **C:/Users/myfile.mp3 and D:/myfile.mp3 and E:/myfile.mp3** when i try to split it by command prompt like C:\Users>**spleeter separate -f {filename}/{filename}-{instrument}.{codec} -c "mp3" -b "128" -o output  -p spleeter:2stems-16kHz -i "myfile.mp3"**
D:\>**spleeter separate -f {filename}/{filename}-{instrument}.{codec} -c "mp3" -b "128" -o output  -p spleeter:2stems-16kHz -i "myfile.mp3"**
E:\>**spleeter separate -f {filename}/{filename}-{instrument}.{codec} -c "mp3" -b "128" -o output  -p spleeter:2stems-16kHz -i "myfile.mp3"**

 spleeter is downloading pretrain models to all folders like C:/Users/pretrainmodel, D:/pretrainmodel and E:/pretrainmodel so how to avoid/override or link it to one folder like C:/User/pretrainmodels only. using command prompt to working with spleeter

**Comment by romi1502** [comment]
Hi @sudheervdm,
you can set the `MODEL_PATH` env variable to the folder where you want to store the model, so that `spleeter` will always look in this folder to retrieve the model (or will download it in this folder at the first call).

**Comment by sudheervdm** [comment]
> Hi @sudheervdm, you can set the `MODEL_PATH` env variable to the folder where you want to store the model, so that `spleeter` will always look in this folder to retrieve the model (or will download it in this folder at the first call). Also, be aware that a single call to spleeter with multiple files to separate is more efficient than multiple calls.

Thanks for your Quick Reply. in my case i  am using command prompt version in my windows system. and also i was installed the python directly and run pip install spleeter for install spleeter in my system. so can you a little bit more explain abouyt your answer. thanks in advance

**Comment by sudheervdm** [comment]
@romi1502 Thanks and iSolve the issue. Added ENV as you mentioned in my system environment variable Love You buddy
