### ISSUE TITLE
[Discussion/ Question] "The system cannot find the file specified"

### ISSUE THREAD

**Issue by ffio1** [deezer/spleeter#73]
I installed Spleeter from pip, and installed all the dependencies (or at least I think) but I get an error saying it can't find the file, whilst trying to separate a music track. 

Below I linked the pictures of verbose log, and my file directory

[Imgur](https://imgur.com/a/WVtsExH)

**Comment by enini** [comment]
I have the same question, so I reinstalled spleeter with conda. And spleeter can work in environment spleeter-cpu.

**Comment by ffio1** [comment]
Yeah. I installed it on conda with the gpu spleeter and it worked fine. I
don't know what was going on.

**Comment by enini** [comment]
I don't know too.
By the way, have you tried the audio_example.mp3? I tried it and it seems that the 4 stems way and 5 stems way both give 4/5 same stems, just the same as the original file(I mean the vocal and others haven't been separated correctly...)
Is that my problem??

**Comment by mmoussallam** [comment]
Please use the provided issue template and not external links. There's not much we can do to help without more information.

**Comment by mmoussallam** [comment]
closing this as this is not a question.
Please read carefully the documentation (and the [FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ)) and submit a _Bug_ report if needed.
