### ISSUE TITLE
Hello, how can I generate a callable dynamic library (so file) from spleeter C++?

### ISSUE THREAD

**Issue by KangChou** [deezer/spleeter#747]
Reference project：

[https://github.com/FaceOnLive/Spleeter-Android-iOS](https://github.com/FaceOnLive/Spleeter-Android-iOSl)

[https://github.com/deezer/spleeter](https://github.com/deezer/spleeter)

[https://github.com/gvne/spleeterpp](https://github.com/gvne/spleeterpp)

**Comment by romi1502** [comment]
Hi @KangChou,
This repo does not deal with C++, so please report the issue in the relevant repository.

**Comment by KangChou** [comment]
> ttps://github.com/gvne/spleeterpp

Hello, I got some answers here, but I want to get a production dynamic library that can be called using a concise C++ program, the idea is to just input the dynamic library and audio files or audio streams to achieve musical vocal accompaniment separation. Hope to get your help.

https://github.com/jinay1991/spleeter/issues/3
@romi1502  @jinay1991
