### ISSUE TITLE
[Discussion] Training to split other types of stems

### ISSUE THREAD

**Issue by evamedia** [deezer/spleeter#75]
Just installed and used this tool, and am frankly amazed, but I have an idea that it could be used for.

A lot of BMX (and I assume skateboard) videos use uncleared music and often get removed when uploaded, instead of uploading with no sound, being able to extract the sound of the bike/skateboard and then upload would be great. I could supply the sounds for training, how much would i need to supply, and how do I build the model?

**Comment by johndpope** [comment]
If you fast forward to end result / the owner still has to reupload with adjusted sounds (presumably they already have video minus added sound track) / (or are you planning to post to your own channel?) either way / probably not going to be very fruitful / you mostly going to end up with the copyrighted song layer out in parts.

**Comment by evamedia** [comment]
I already post to my own website (bmxmdb.com) after receiving permission from the video creators, I've been asked specifically not to upload some due to uncleared music, but if I could remove that from the files I already have I could post them. Some of these video's are 20 years old, so little chance of the video minus the sound track existing.

>you mostly going to end up with the copyrighted song layer out in parts.

Not sure I get you, I don't want any of the music, just the bike sounds

**Comment by johndpope** [comment]
If you have same song / you can subtract the wave forms to cancel out song.
