### ISSUE TITLE
尝试过后发现高跟鞋走路的声音、鸟叫的声音还是分离不开呢，是哪里不对吗？

### ISSUE THREAD

**Issue by helloxuejuxi** [deezer/spleeter#758]
尝试过后发现高跟鞋走路的声音、鸟叫的声音还是分离不开呢，是哪里不对吗？2/4/5stems都尝试过了，包括送入spleeter之前将音频采样率转到44.1kHz，还是过滤不掉这些不想要的声音。

**Comment by helloxuejuxi** [comment]
还是缺少鸟鸣和高跟鞋的训练数据？没人来解答一下吗

**Comment by helloxuejuxi** [comment]
来银啊

**Comment by xszqxszq** [comment]
You'd better use English, otherwise it is normal to receive no response as most people here are not Chinese.

**Comment by xszqxszq** [comment]
Pretrained models are not expected to do such separation, therefore you should train by yourself.

**Comment by helloxuejuxi** [comment]
> Pretrained models are not expected to do such separation, therefore you should train by yourself.

Thanks for your reply
