### ISSUE TITLE
[Discussion] A Fool On The Hill : Flute and Voice indistinguishable 

### ISSUE THREAD

**Issue by citron** [deezer/spleeter#76]
Spleeter is great.
Try to split voice and music from "A Fool On The Hill" from The Beatles. You'll notice that Spleeter is not able to separate the flute from the voice.

**Comment by johndpope** [comment]
If you can produce enough training data / here’s a flute / here’s voice  (here’s a different voice)/ you can achieve this. Note this edge case is going to show up everywhere that’s note drums / base / voice / piano.

**Comment by mmoussallam** [comment]
Indeed some instruments are harder to distinguish than other and flute/voice can be such as case.
