### ISSUE TITLE
[Discussion] WARNING:spleeter:[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by gladys0313** [deezer/spleeter#77]
Hello guys,

I'm trying spleeter on a Win10 laptop. When running ``spleeter separate -i spleeter\audio_example.mp3 -p spleeter:2stems -o output`` I got the following error:

``WARNING:spleeter:[WinError 2] The system cannot find the file specified``

I'm sure the file path is correct, so I'm confused about this error. Anyone has idea?

For your information, I didnt install spleeter using "conda" but using "pip" because when using conda I always had the problem of "simplejson finished with status error".

**Comment by Carnageous** [comment]
Are you using the latest version of spleeter (1.4.3)? In 1.4.3 there was a bugfix that had to do with windows paths.

**Comment by gladys0313** [comment]
@Carnageous Yes I'm using the latest version 1.4.3..

**Comment by johndpope** [comment]
I recommend miniconda -> 40mb install as opposed to 1gb with anaconda https://docs.conda.io/en/latest/miniconda.html

Pip install not suppported. 

Also watched for correct path

The example nests the directory and file name together.
If you already cd into spleeter directory
Then you can drop the directory
spleeter\audio_example.mp3

This tripped me up as error thrown was obscure ffmepg error.

**Comment by KewkLW** [comment]
This was shut down once already, stating to read the FAQ... which does not help. There's no help at all actually and this thread will get shut down as well. 

For me the issue was I had not activated the GPU settings.

**Comment by gladys0313** [comment]
> I recommend miniconda -> 40mb install as opposed to 1gb with anaconda https://docs.conda.io/en/latest/miniconda.html
> 
> Pip install not suppported.
> 
> Also watched for correct path
> 
> The example nests the directory and file name together.
> If you already cd into spleeter directory
> Then you can drop the directory
> spleeter\audio_example.mp3
> 
> This tripped me up as error thrown was obscure ffmepg error.

**Comment by gladys0313** [comment]
@johndpope Thanks John, yes I did check the path carefully...

**Comment by gladys0313** [comment]
@KewkLW Thanks for the tip about GPU...in my case since I used pip to install, which should have nothing to do with GPU.....

**Comment by mmoussallam** [comment]
Hi, this is not really a question please use the Bug template instead.

It seems that the `spleeter` command is not recognized by your system which probably means something failed during the install.

On windows we highly recommend that you use Anaconda. If you have issues installing dependencies then you should solve these before trying spleeter

**Comment by qaz10102030** [comment]
Hey, I found the solution for me.
I just download the FFmpeg binary file then set the environment and all fine!

Here is the binary file: https://ffmpeg.zeranoe.com/builds/

**Comment by KewkLW** [comment]
[https://github.com/deezer/spleeter/wiki/1.-Installation](url)

> For Windows users we highly recommend you use a complete Anaconda installation. You may otherwise have to manually install ffmpeg
