### ISSUE TITLE
[Discussion] how to process only accompaniment without vocal ?

### ISSUE THREAD

**Issue by abosaqer** [deezer/spleeter#778]
hi guys 
i want only get accompaniment and not vocal
I think this will reduce the processing time
Do any of you have any idea?

**Comment by romi1502** [comment]
Hi @abosaqer,
Spleeter works by estimating time-frequency masks for each instrument to be separated. To estimate those masks, it needs to estimate model spectrograms for each instrument: for instance, when you perform accompaniment/vocal separation, spleeter needs to estimate a model spectrogram for both the accompaniment and the vocal part.
