### ISSUE TITLE
[Feature] Update dependencies' version

### ISSUE THREAD

**Issue by YuvalEvron** [deezer/spleeter#786]
## Description

Hello,
I am willing to use Spleeter as part of one of my projects, however, many of the dependency packages' versions (e.g. tensorflow, numpy, librosa, typer) are quite old and cause conflicts with the currently installed packages in my project.
Is it possible to update some of them in the next Spleeter version?

**Comment by mmoussallam** [comment]
Hello @YuvalEvron 

That's a timely request! I've just merged #785 and uploaded a newer package version: 2.3.2 that should be much easier to integrate. Let us know if you still encounter issues
