### ISSUE TITLE
[Feature] speaker/singer/vocalist separation

### ISSUE THREAD

**Issue by bartman081523** [deezer/spleeter#792]
## Description

speaker separation, so when we hear different speakers or singers or vocalists, 
every different voice gets a separated audio voice track

**Comment by romi1502** [comment]
Hi @bartman081523,
Thank you for the suggestion.
This is quite a harder problem though especially since it's hard to find data for training and there is no plan of including such a feature in spleeter in the short term.

**Comment by bartman081523** [comment]
> This is quite a harder problem though especially since it's hard to find data for training
Thank you for your answer. 
As I understand, training data for acapella/single voice would be enough, so that no other training data would be required, because the speaker separation is done with spectogram masking. 

I found this paper [VoiceFilter: Targeted Voice Separation by Speaker-Conditioned Spectrogram Masking](https://arxiv.org/abs/1810.04826).
and these github implementations of that paper:
https://paperswithcode.com/paper/voicefilter-targeted-voice-separation-by
maybe you can have a look, whether this is also possible for spleeter, to utilize these libraries/implementations. 
It would be a big feature, also for the applications that utilize spleeter, I would think.
