### ISSUE TITLE
[Bug] Occur OMP:Waring #190 when execute on Docker

### ISSUE THREAD

**Issue by jaus11** [deezer/spleeter#82]
## Description

Can't separate music when execute on Docker

## Step to reproduce

1. Build Docker image according to this page (https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-docker-image)
2. Run Docker image
3. Got `OMP: Warning #190`
4. No file produced in output folder

## Output

```
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:spleeter:Extracting downloaded 2stems archive
INFO:spleeter:2stems model file(s) extracted
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #213: KMP_AFFINITY: x2APIC ids not unique - decoding legacy APIC ids.
OMP: Info #149: KMP_AFFINITY: Affinity capable, using global cpuid info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0,1
OMP: Info #156: KMP_AFFINITY: 2 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #159: KMP_AFFINITY: 2 packages x 1 cores/pkg x 1 threads/core (2 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 1 
OMP: Info #250: KMP_AFFINITY: pid 1 tid 1 thread 0 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 1 tid 47 thread 1 bound to OS proc set 1
INFO:spleeter:Loading audio b'/input/input.mp3' from 0.0 to 600.0
INFO:spleeter:Audio data loaded successfully
OMP: Info #250: KMP_AFFINITY: pid 1 tid 46 thread 2 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 1 tid 67 thread 3 bound to OS proc set 1
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                |  MacOS |             |
| Hardware spec     |  CPU   |

**Comment by romi1502** [comment]
It looks like a silent fail linked to a out of memory condition.

You can try monitoring memory usage using `docker stat`. Check whether the container reaches the memory limit at some point. If it does, it will probably fail. Then a workaround would be to:
- reduce the duration of the processed file using the `-d` option of `spleeter separate` (reducing file duration will require less memory).
and/or:
- increase the memory limit in the docker preferences.

Let us know, if OOM may explain your issue.

**Comment by phillipadsmith** [comment]
> increase the memory limit in the docker preferences.

👍 That worked for me. Increased Docker's memory to 8GB and re-ran the command and it output the stems.

`docker stats` reported that it consumed almost 6GB of that memory to process the 9.5MB audio file.

**Comment by jaus11** [comment]
I could run spleeter by increase Docker's memory, too.
