### ISSUE TITLE
rate must be specified when data is a numpy array or list of audio samples

### ISSUE THREAD

**Issue by wensaochen** [deezer/spleeter#823]
<img width="1351" alt="Screenshot 2023-01-19 at 22 37 53" src="https://user-images.githubusercontent.com/123077918/213470770-8a5487a4-3676-4931-9690-e4a64938efc5.png">

Anyone has ideas of this issue?

**Comment by MrBanhBao** [comment]
It seems like that the 'copy.mp3' does not exists and so loading it fails.

**Comment by wensaochen** [comment]
> 

<img width="1304" alt="Screenshot 2023-01-20 at 09 24 08" src="https://user-images.githubusercontent.com/123077918/213598171-2096faeb-f91a-4c92-a12b-42a2c4598b5e.png">

look at the first part, the file should be loaded.

**Comment by MrBanhBao** [comment]
Normally you just need to specify the rate parameter when playing numpy arrays. You do it like this:
`sr = <number>
Audio(x, rate=sr)`
But you want to play an audio file, so I don't think that will solve your problem.

Looking at you code above. There is a typo in your code. You are downloading file 'Copy.mp3' (with a capital C) and trying to load the file 'copy.mp3' (small c).

**Comment by romi1502** [comment]
Hi @wensaochen,
The error you reported does not seem to be related to spleeter (no spleeter code is involved only ipython one) and then it should not be reported in spleeter issues. I close it then.
