### ISSUE TITLE
[Discussion] I made model, so I wanna use it

### ISSUE THREAD

**Issue by kno3a87** [deezer/spleeter#83]
`spleeter train -p configs/jazz_config.json -d ./train/`
I made model for piano, woodbass, drums for jazz music.

Question:
1.  I can see "INFO:spleeter:Model training done" , but I cant find model
2. How can I use this model? please tell me command like `spleeter separate -i audio_example.mp3 -o audio_output -p spleeter:4stems`

**Comment by romi1502** [comment]
1. The model is saved in a directory set by the `model_dir` option in your json config_file (see the [wiki](https://github.com/deezer/spleeter/wiki/3.-Models#model-description)).

2. You should then be able to use your trained model using `spleeter separate -i audio_example.mp3 -o audio_output -p configs/jazz_config.json`

**Comment by kno3a87** [comment]
1.  I missed it! Thanks
2. I got this error
```
spleeter separate -i Autumn.wav -o Autumn_output -p spleeter/configs/jazz_config.json
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/jazz_model.tar.gz
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/spleeter-cpu/bin/spleeter", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/__main__.py", line 47, in entrypoint
    main(sys.argv)
  File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/__main__.py", line 41, in main
    entrypoint(arguments, params)
  File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/commands/separate.py", line 166, in entrypoint
    estimator = create_estimator(params, arguments.MWF)
  File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/utils/estimator.py", line 36, in create_estimator
    params['model_dir'] = model_provider.get(model_directory)
  File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/model/provider/__init__.py", line 65, in get
    model_directory)
  File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/model/provider/github.py", line 65, in download
    raise IOError(f'Resource {url} not found')
OSError: Resource https://github.com/deezer/spleeter/releases/download/v1.4.0/jazz_model.tar.gz not found
```

**Comment by Faylixe** [comment]
> 1. I missed it! Thanks
> 2. I got this error
> 
> ```
> spleeter separate -i Autumn.wav -o Autumn_output -p spleeter/configs/jazz_config.json
> INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/jazz_model.tar.gz
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/envs/spleeter-cpu/bin/spleeter", line 8, in <module>
>     sys.exit(entrypoint())
>   File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/__main__.py", line 47, in entrypoint
>     main(sys.argv)
>   File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/__main__.py", line 41, in main
>     entrypoint(arguments, params)
>   File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/commands/separate.py", line 166, in entrypoint
>     estimator = create_estimator(params, arguments.MWF)
>   File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/utils/estimator.py", line 36, in create_estimator
>     params['model_dir'] = model_provider.get(model_directory)
>   File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/model/provider/__init__.py", line 65, in get
>     model_directory)
>   File "/home/ubuntu/anaconda3/envs/spleeter-cpu/lib/python3.7/site-packages/spleeter/model/provider/github.py", line 65, in download
>     raise IOError(f'Resource {url} not found')
> OSError: Resource https://github.com/deezer/spleeter/releases/download/v1.4.0/jazz_model.tar.gz not found
> ```

This is actually a bug, sorry about that. We will fix it in the next release that should come next week. Meanwhile as a quick fix you can add an empty file with `.probe` name into your model directory. It will prevent _Spleeter_ from trying to download specified model from _GitHub_.

**Comment by kno3a87** [comment]
Then I add `.probe`, I can separate! Thanks!!!

**Comment by Faylixe** [comment]
We just released a new version that will simply create the probe file after the train command is executed so it will work as expected.
