### ISSUE TITLE
Python3.10 support for pypi package

### ISSUE THREAD

**Issue by mattiadg** [deezer/spleeter#834]
Hi, thank you for the great tool!
I noticed that the latest release on pypi: 2.3.0 has support until python3.9, but the latest version on main supports up to Python3.10. 
Are you planning to upload a new release?

Thanks again

**Comment by romi1502** [comment]
Hi @mattiadg,
Thanks for you question. The latest release on pypi is 2.3.2 and is supposed to support Python3.10.

**Comment by mattiadg** [comment]
Thank you, I will try it out soon

Il ven 10 mar 2023, 11:22 Romain Hennequin ***@***.***> ha
scritto:
