### ISSUE TITLE
[Bug] Is it works on AMD cpus?

### ISSUE THREAD

**Issue by AT0Naka** [deezer/spleeter#84]
## Step to reproduce

1. Installed using Anaconda.
2. Run as `...`
3. Got Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll. 
![Spleeter](https://user-images.githubusercontent.com/24413094/68759414-b0041880-0620-11ea-9053-5053308eb9e6.jpg)
error

## Output

```bash
Share what your terminal says when you run the script (as well as what you would expect).
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | Conda |
| RAM available     | 16GB                             |
| Hardware spec     | Ryzen 5 2600 |

**Comment by mickdekkers** [comment]
I haven't tried Anaconda, but the [Docker image](https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-docker-image) worked fine on my machine. You could try that for now if you want to get it working quickly.

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows 10 Pro 64-bit           |
| Installation type | Docker                          |
| RAM available     | 32GB                            |
| Hardware spec     | AMD Ryzen 9 3900x               |

**Comment by AT0Naka** [comment]
Thanks for your answer!

**Comment by cyanit** [comment]
Ran into the exact same issue on MacOS 10.15 with a Ryzen 3800x, would be awesome if theres a note in the [installation section](https://github.com/deezer/spleeter/wiki/1.-Installation) on that ^^
