### ISSUE TITLE
[Bug] Colab Runtime Disconnected

### ISSUE THREAD

**Issue by nicholasmswift** [deezer/spleeter#88]
## Description

Was having trouble installing for local use, so I decided to try to use the Colab link.

## Step to reproduce

1. Opened Colab environment
2. Replaced the wget command with 
```
from google.colab import files
uploaded = files.upload() 
```
3. Ran all steps in order
4. Uploaded a local mp3 file
5. Ran the rest of the steps
6. Got a successful message from the actual separate function, and files exist in the output directory
7. Tried to listen to the output file and got a "runtime disconnected" error

## Output

`!spleeter separate -i keenanvskel.mp3 -o output/`
Output from the split function
```bash
INFO:spleeter:Loading audio b'keenanvskel.mp3' from 0.0 to 600.0
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:File output/keenanvskel/vocals.wav written
INFO:spleeter:File output/keenanvskel/accompaniment.wav written
```

```
!ls output/keenanvskel
accompaniment.wav  vocals.wav
```

Then I ran this
`Audio('output/keenanvskel/vocals.wav')`
And got this response
`Runtime Disconnected`

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | My laptop is running MacOS, but using Colab |
| Installation type | pip             |
| RAM available     | Got the green checkmark for both RAM and Disk in the Colab environment                             |
| Hardware spec     | unsure |

## Additional context

Not sure if this is an issue with spleeter or with Colab. I love this project conceptually so I was excited to try it out, I saw some other posts online about runtime disconnect errors in Colab, but everything I found seems to only occur if it's running for 15 minutes or more. This whole process was less than 5 minutes, and I've tried multiple times and continually get the same error.

If this is not the correct place for this type of error, or if I am doing something wrong, feel free to close this bug and let me know what next steps I might take. 

Will also attach some screenshots of the environment.

<img width="1273" alt="Screen Shot 2019-11-13 at 6 42 28 PM" src="https://user-images.githubusercontent.com/11081954/68817684-0e90bd00-0648-11ea-8f55-8228f81970d5.png">
<img width="1291" alt="Screen Shot 2019-11-13 at 6 42 41 PM" src="https://user-images.githubusercontent.com/11081954/68817685-0e90bd00-0648-11ea-8c1b-c6a94dafd747.png">
<img width="1277" alt="Screen Shot 2019-11-13 at 6 42 54 PM" src="https://user-images.githubusercontent.com/11081954/68817686-0e90bd00-0648-11ea-8738-3bec1b194081.png">
<img width="1301" alt="Screen Shot 2019-11-13 at 6 43 22 PM" src="https://user-images.githubusercontent.com/11081954/68817688-13ee0780-0648-11ea-8a8e-c468bd32bf79.png">

**Comment by Faylixe** [comment]
Not a Google Colab expert, but we provided the colab so people can try it out without installing the environment. Although, I assume since it is free, then colab provides limited resources in term of CPU and RAM, and turn out thet _Spleeter_ is RAM greedy, and depending of the size of your song it is highly possible that you reach colab RAM limit.

We won't provide assistance for this case as it is purely a colab related issue.

**Comment by matibak** [comment]
Just add `-c mp3` to separate command and you will be able to play the output, since playing `.wav` is more consuming

**Comment by bhaskarmulik** [comment]
Is there a similar way to convert the audio file to mp3 using the python API?
