### ISSUE TITLE
[Discussion] Train using GPU

### ISSUE THREAD

**Issue by kno3a87** [deezer/spleeter#89]
I want train using **GPU**. I do `conda activate spleeter-cpu` and `spleeter train -p configs/jazz_config.json -d ./configs/train`.
Am I doing it right?

**Comment by Faylixe** [comment]
> I want train using **GPU**. I do `conda activate spleeter-cpu` and `spleeter train -p configs/jazz_config.json -d ./configs/train`.
> Am I doing it right?

Well, as the name suggest. `spleeter-cpu` environment use `CPU`. You need to use the provided `spleeter-gpu` environment instead.

**Comment by kno3a87** [comment]
Sorry, I have only `/home/ubuntu/anaconda3/envs/spleeter-cpu`...
