### ISSUE TITLE
OSError: FFMPEG binary (ffmpeg) not found

### ISSUE THREAD

**Issue by ajatau** [deezer/spleeter#9]
Tried running spleeter on on my machine and kept getting this error

`OSError: FFMPEG binary (ffmpeg) not found`

**Comment by mmoussallam** [comment]
Hi,

Indeed, *Spleeter* requires a working FFMPEG install. Check out the [installation instructions](https://github.com/deezer/spleeter/wiki/1.-Installation#using-pip) for more details.
