### ISSUE TITLE
only Stem2 working

### ISSUE THREAD

**Issue by waveydavey0** [deezer/spleeter#91]
Successfully installed on a 1-CPU 1G Ram VM, running Ubuntu 19.04. 
Ran the example with sample audio file, worked ok. 

Uploaded my own audio file (Alison by Elvis Costello, can supply if necessary) 
2stem worked ok, 4 and 5 stem failed. Example output shown: 

# spleeter separate -i audio_example.mp3  -o output/
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
INFO:spleeter:Extracting downloaded 2stems archive
INFO:spleeter:2stems model file(s) extracted
INFO:spleeter:Loading audio b'audio_example.mp3' from 0.0 to 600.0
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:File output/audio_example/vocals.wav written

# spleeter separate -i Alison.mp3  -p spleeter:2stems -o output/
INFO:spleeter:Loading audio b'Alison.mp3' from 0.0 to 600.0
INFO:spleeter:Audio data loaded successfully
INFO:spleeter:File output/Alison/accompaniment.wav written
INFO:spleeter:File output/Alison/vocals.wav written

# spleeter separate -i Alison.mp3  -p spleeter:4stems -o output/
INFO:spleeter:Loading audio b'Alison.mp3' from 0.0 to 600.0
INFO:spleeter:Audio data loaded successfully
Killed

# spleeter separate -i Alison.mp3  -p spleeter:5stems -o output/
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/5stems.tar.gz
INFO:spleeter:Extracting downloaded 5stems archive
INFO:spleeter:5stems model file(s) extracted
INFO:spleeter:Loading audio b'Alison.mp3' from 0.0 to 600.0
INFO:spleeter:Audio data loaded successfully
Killed

# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"

I would *really* like to be able to extract the bass !

**Comment by Faylixe** [comment]
You don't have enough memory. Please read FAQ.

**Comment by waveydavey0** [comment]
Did read FAQ, did not spot memory requirements! 
Answer fixed my problem, thanks. 
Superb project, amazing bit of software. Will make learning new songs for band much easier.
