### ISSUE TITLE
spleeter installation on Windows 10 : ffmpeg module not found

### ISSUE THREAD

**Issue by krauspe** [deezer/spleeter#93]
## Step to reproduce

1. Installed using 

`git clone https://github.com/Deezer/spleeter
conda env create -f spleeter/conda/spleeter-cpu.yaml

conda activate spleeter-cpu
'
3. Got `ModuleNotFoundError: No module named 'ffmpeg'` error

## Output

```
(spleeter-gpu) E:\DATA\PROG\spleeter>python -m spleeter separate -i audio_example.mp3 -p spleeter:2stems -o output
Traceback (most recent call last):
  File "D:\Programme\Anaconda3\envs\spleeter-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Programme\Anaconda3\envs\spleeter-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\DATA\PROG\spleeter\spleeter\__main__.py", line 51, in <module>
    entrypoint()
  File "E:\DATA\PROG\spleeter\spleeter\__main__.py", line 47, in entrypoint
    main(sys.argv)
  File "E:\DATA\PROG\spleeter\spleeter\__main__.py", line 41, in main
    entrypoint(arguments, params)
  File "E:\DATA\PROG\spleeter\spleeter\commands\separate.py", line 160, in entrypoint
    audio_adapter = get_audio_adapter(arguments.audio_adapter)
  File "E:\DATA\PROG\spleeter\spleeter\utils\audio\adapter.py", line 136, in get_audio_adapter
    return get_default_audio_adapter()
  File "E:\DATA\PROG\spleeter\spleeter\utils\audio\adapter.py", line 124, in get_default_audio_adapter
    from .ffmpeg import FFMPEGProcessAudioAdapter
  File "E:\DATA\PROG\spleeter\spleeter\utils\audio\ffmpeg.py", line 14, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'
```

## Environment

| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | Conda          |
| RAM available     | 16GB                             |
| Hardware spec     | GTX1050/ CPU core i7 7700.             |

ffmpeg is actually installed in conda env 'spleeter-gpu'

**Comment by Faylixe** [comment]
The problem here is not the lack of `ffmpeg` but `ffmpeg-python` library which is supposed to be installed as well. Did you experience any error / warning during Conda installation ?

**Comment by krauspe** [comment]
I ddidn't see any, but maybe I missed it.
How can I solve this ?

**Comment by Faylixe** [comment]
Maybe try to reinstall _Spleeter_ environment from provided YAML file. Otherwise we now have a public package on `conda-forge`, we will soon replace environment based file documentation by installation package. Your can try it by using following command : 

```bash
conda install -c conda-forge spleeter 
``

**Comment by krauspe** [comment]
Ok thanks , this seems to work , now I have another problem but this is caused by the fact I'm sitting behind a proxy and thus the download of the model archive. 
I configured conda for using a proxy, but I don't know what spleeter does ...
Sorry it's off topic, but  maybe you have an idea ...

**Comment by Faylixe** [comment]
> Ok thanks , this seems to work , 

Good to know :)

> now I have another problem but this is caused by the fact I'm sitting behind a proxy and thus the download of the model archive failed.
> I configured conda for using a proxy, but I don't know what spleeter does ...
> Sorry it's off topic, but maybe you have an idea ...

We are using _Python_ `requests` library for downloading model through HTTP. You should check related issues on web (it probably relies on system configured proxy or possibly environment variable).

**Comment by krauspe** [comment]
Thanks again ! :-)
