### ISSUE TITLE
[Feature] Ability to set output mp3 bitrate as an option

### ISSUE THREAD

**Issue by ravi-annaswamy** [deezer/spleeter#95]
## Description

When mp3 output format is chosen, Spleeter should have either an option of specifying a bit rate say 256K or it should default to a high rate. Currently it exports at 64kbps.

## Additional information

When I use this command line:
spleeter separate -i audio_example.mp3 -o output/ -c mp3

on colab or on my mac, the output mp3 files default to 64kbps. 
I have tried this on various mp3 with as high input bitrate as 256K and the output mp3 is always 64kbps.

I do not see a way (maybe I have not looked carefully) to pass from the command line or  even modify the ffmpeg wrapper.

The mp3 quality is far lower than wav output because of this low bitrate. Please let me know if this is a default setting on ffmpeg install.

**Comment by Faylixe** [comment]
Thanks for the suggestion. Indeed you can't not specify `bitrate` parameters at the moment.  As you suggest it should so we will add it to the next `Spleeter` release. Meanwhile you can by pass this by using `Separator` API from Python code directly, where the provided separation method allows to specify a bitrate in addition of the audio codec to use for export.

**Comment by ravi-annaswamy** [comment]
Thank you for prompt response and the suggested alternate Felix 
This open source is going to revolutionize music as more detailed instrument separation models are built by users.

Very happy to see sigsep stalwarts Fabian participating to extend this too in addition to the excellent breakthroughs they have done already with open unmix.

We are living in a time where python open source deep learning and high storage and compute are giving us heavenly gifts

Big thanks 
Ravi

**Comment by ravi-annaswamy** [comment]
Faylixe,

(apologize for mistyping your name on iphone initiated message above, as Felix)

Temporarily, I am converting wave to high bit rate mp3 using ffmpeg so I can update in Colab without my own fork (yet).

You guys have really made a breakthrough.

I will share an example of a mix and unmix from a Tamil legend Ilaiyaraja soon and share why I am saying so.

Ravi

**Comment by Faylixe** [comment]
The new version is released and have the new bitrate option for separate command.

**Comment by ravi-annaswamy** [comment]
Thanks I will check this out
