### ISSUE TITLE
[Discussion] Demo Colab notebook with 2 min song snippet (Aadum Neram by Ilaiyaraja 1988)

### ISSUE THREAD

**Issue by ravi-annaswamy** [deezer/spleeter#98]
Spleeter team, 

I took spleeter 2stem and 5stem models for a test drive on a composer I simply love.

I have created a notebook with step by step conversion of karaoke and then 5 stem, converting to high quality mp3 and added my observations on each of the 5 tracks. 

As I have noted, this output is truly more coherent and confident than commercial option I tried!

https://colab.research.google.com/github/ravi-annaswamy/spleeter/blob/master/spleeter_demo_ra.ipynb

It is one click test run and will produce tracks in sub folders as shown. I will also upload the snippets onto my git for people who dont want to take trouble running the code, but want to see results.

I am truly very impressed by the technology and outputs and the generosity of your sharing. 

This technology of source separation will become a boon to musicians, composers, arrangers and producers and entertain people in new ways.

Note: If you think this discussion is out of scope for git discussion, please feel free to close or I can delete.

Thanks
Ravi

**Comment by ravi-annaswamy** [comment]
For those curious to hear the separation results without running colab, I have added the karaoke/voice 2stem here:
https://github.com/ravi-annaswamy/spleeter/tree/master/output_2stem/aadum_neram_raja_example

and the five stem here:
https://github.com/ravi-annaswamy/spleeter/tree/master/output_5stems/aadum_neram_raja_example

**Comment by Faylixe** [comment]
Out of scope indeed, we do not share nor reference people experiments for legal reasons.

Glad you enjoy Spleeter though :).
